api/aperture/policy/language/v1/policy.proto, api/gen/openapiv2/aperture.swagger.yaml, api/gen/proto/go/aperture/policy/language/v1/policy.pb.go, docs/gen/policies/swagger.md
Resolves: #143
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/160)
=> Expand doc comments for policies

pkg/otel/components.go, pkg/otel/config.go, plugins/service/aperture-plugin-fluxninja/otel/provide.go
* Add fast batching for local metrics
* Add slow batching for FN plugin metrics
* Fix debug extensions not being loaded when FN plugin is enabled
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/200)
=> Fix Controller OTEL pipelines

api/aperture/classification/v1/extractor.proto, api/aperture/classification/v1/ruleset.proto, api/aperture/common/labelmatcher/v1/labelmatcher.proto, api/gen/openapiv2/aperture.swagger.yaml, api/gen/proto/go/aperture/classification/v1/extractor.pb.go, api/gen/proto/go/aperture/classification/v1/ruleset.pb.go, api/gen/proto/go/aperture/common/labelmatcher/v1/labelmatcher.pb.go, docs/gen/classification/swagger.md, docs/gen/policies/swagger.md
Glitches were caused by table-of-contents logic which in absence of
title was trying to take x first characters of description, resulting in
eg. yaml snippets cut in half.
This commits avoid glitches by **not** using dot on first sentence, so
that go-swagger knows that the first sentence is a title.
Resolves: https://github.com/fluxninja/aperture/issues/202
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/204)
=> Fix markdown glitches in generated classifiers documentation

pkg/flowcontrol/metrics.go, pkg/jobs/job-metrics.go, pkg/metrics/schema.go, pkg/policies/dataplane/actuator/concurrency/load-shed-actuator.go, pkg/policies/dataplane/actuator/concurrency/scheduler/wfq_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/212)
=> Add metrics names to common schema

pkg/otelcollector/metricsprocessor/processor.go
cc @DariaKunoichi @kwapik
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/250)
=> Add comment why histogram might already exists in metricsprocessor

manifests/charts/demo-app/templates/deployment.yaml
* Demo app comes up successfully on one node cluster after this change.
* Pod anti affinity constraint for demo app is now preferred instead of required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/286)
=> Soft pod anti affinity for demo app

manifests/k8s/Tiltfile, manifests/k8s/tilt/portforward.sh
kubectl port-forward might loose the connection and not recover
We monitor the health of the connection ourselves
and restart the port-forward in case of issues.
Tested with a stresstest script which can reliably trigger the issue:
```python
#!/usr/bin/env python3
import datetime
import http.client
for _ in range(100000):
conn = http.client.HTTPConnection("localhost:3000")
conn.request("GET", "/")
conn.getresponse()
conn.close()
print(datetime.datetime.now())
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/293)
=> Workaround kubectl port-forward connectivity issues

docs/content/concepts/policies/policy-blueprints.md, manifests/k8s/Tiltfile, manifests/k8s/tanka/environments/tilt/apps/demoapp/mixins.libsonnet, manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet, manifests/k8s/tanka/lib/apps/demoapp/main.libsonnet, manifests/k8s/tilt/portforward.sh, pkg/flowcontrol/envoy/authz_test.go, pkg/policies/controlplane/validator_test.go, tools/load_generator/scenarios/load_test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/298)
=> rename demo app services

manifests/charts/istioconfig/values.yaml, manifests/k8s/tanka/environments/tilt/apps/demoapp/mixins.libsonnet, manifests/k8s/tanka/jsonnetfile.json, manifests/k8s/tanka/jsonnetfile.lock.json, manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet, pkg/flowcontrol/common/metrics.go, pkg/metrics/schema.go, pkg/otelcollector/metricsprocessor/processor.go, pkg/policies/dataplane/actuators/concurrency/load-shed-actuator.go, tools/load_generator/scenarios/load_test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/299)
=> Improve panels in the playground grafana

api/aperture/common/labelmatcher/v1/labelmatcher.proto, api/aperture/common/selector/v1/selector.proto, api/aperture/policy/language/v1/classifier.proto, api/aperture/policy/language/v1/policy.proto, api/gen/openapiv2/aperture.swagger.yaml, api/gen/proto/go/aperture/common/labelmatcher/v1/labelmatcher.pb.go, api/gen/proto/go/aperture/common/selector/v1/selector.pb.go, api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go, api/gen/proto/go/aperture/policy/language/v1/policy.pb.go, docs/content/cloud/plugin.md, docs/content/concepts/flow-control/flow-control.md, docs/content/concepts/flow-control/fluxmeter.md, docs/content/concepts/flow-control/label/classifier.md, docs/content/concepts/flow-control/label/label.md, docs/content/concepts/flow-control/selector.md, docs/content/concepts/flow-control/service.md, docs/gen/policies/gen.yaml, docs/gen/policies/policy.md
When documenting flow classifiers, I realized we refer to flow labels in
various places, but never defined what it was
Preview: https://deploy-preview-54--aperture-tech-docs.netlify.app/docs/development/concepts/flow-control/label/
---
This page is now the source of truth about flow labels.
Previously it was partially documented in selector reference, not
selector just links to Flow Label page.
Also:
* Pulled out Service out of Selector.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/294)
=> Add Flow Label to concepts in docs

README.md
For some reason GH mobile app does not support relative paths to images in dual theme mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/340)
=> Fix themes in GH mobile app

.circleci/continue-workflows.yml, docs/gen/config/aperture-agent/swagger.md, docs/gen/config/aperture-controller/swagger.md, docs/gen/policies/policy.md, docs/tools/swagger/swagger-templates/config.gotmpl
Rendering of definition lists (dl/dt/dd) was producing invalid markdown/html, causing docusaurus to fail.
* fix closing dl tags,
* add missing spacing around dd tags.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/354)
=> Fix broken generated controller documentation

api/aperture/common/selector/v1/selector.proto, api/aperture/policy/language/v1/policy.proto, api/gen/openapiv2/aperture.swagger.yaml, api/gen/proto/go/aperture/common/selector/v1/selector.pb.go, api/gen/proto/go/aperture/policy/language/v1/policy.pb.go, docs/content/concepts/flow-control/actuators/rate-limiter.md, docs/content/concepts/flow-control/actuators/scheduler.md, docs/content/concepts/flow-control/label/classifier.md, docs/content/concepts/flow-control/label/label.md, docs/content/concepts/flow-control/selector.md, docs/gen/config/aperture-agent/swagger.md, docs/gen/config/aperture-controller/swagger.md, docs/gen/policies/gen.yaml, docs/gen/policies/policy.md, docs/tools/swagger/swagger-templates/config.gotmpl
We were providing custom heading ids, but the way it was done, was not
understood by docusaurus and docusaurus was generating its own ids anyway.
* Provide custom heading ids the way docusaurus expects it,
* update all heading-links.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/356)
=> Fix heading ids in generated docs

pkg/otelcollector/consts.go, pkg/otelcollector/metricsprocessor/processor.go, pkg/otelcollector/metricsprocessor/processor_test.go
Closes: GH-267
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/351)
=> Update telemetry schema with workflows

tools/load_generator/scenarios/load_test.js
When loading the traffic using the load_test scenario scripts: `time="2022-09-08T16:41:23Z" level=error msg="ReferenceError: sleep is not defined\n\tat file:///test/load_test.js:48:10(54)\n\tat native\n" executor=ramping-vus scenario=guests source=stacktrace
`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/383)
=> Fix sleep reference error in load test scenario

docs/content/concepts/flow-control/flow-control.md, docs/content/concepts/flow-control/label/classifier.md, docs/content/concepts/flow-control/label/label.md
* Removed intro paragraphs (as they're already present in introduction).
* Explained how flow control splits between policies and dataplane components.
* Explained what are control points.
TODO:
(but these could be done in subsequent PRs)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/381)
=> Expand top-level Flow Control concept

docs/content/concepts/flow-control/label/classifier.md, docs/content/concepts/flow-control/label/label.md, pkg/otelcollector/metricsprocessor/processor.go, pkg/policies/controlplane/validator_test.go, pkg/selectors/labels.go, pkg/selectors/labels_test.go, pkg/selectors/selectors_suite_test.go, playground/tanka/apps/demoapp/mixins.libsonnet
Make labels to be consistent with OTEL semantics
Resolves #341 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/380)
=> Rename request flow labels according to OTEL semantic conventions

docs/content/reference/configuration/agent.md, docs/content/reference/configuration/controller.md, docs/content/reference/configuration/policies.md, docs/gen/config/agent/metadata, docs/gen/config/controller/metadata, docs/gen/policies/metadata, docs/tools/swagger/swagger-templates/config.gotmpl
It's not too useful as we have ToC on rhs sidebar and also the Concepts
sections serves as a kind of "high-level ToC".
Also:
* Remove title from gotmpl – it's already in `metadata`, which we
prepend.
* Don't show Reference section if it's empty.
* Inject small intro to generated configuration pages, with backlinks to
get-started & concepts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/445)
=> Remove the Objects Index from generated docs

docs/content/concepts/flow-control/flow-classifier.md, docs/content/get-started/installation/agent/envoy/istio.md, manifests/charts/istioconfig/templates/envoy_filter.yaml
Ext authz's request body buffering was causing troubles with
client-streaming APIs, such as some ETCD apis used by Aperture Agent
(which communicates through envoy when deployed as sidecar). Disabling
request body buffering until we figure out a better solution.
Fixes https://github.com/fluxninja/cloud/issues/5862
See https://github.com/fluxninja/aperture/issues/479
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/480)
=> Disable ext_authz request body buffering by default

pkg/otel/config.go, plugins/service/aperture-plugin-fluxninja/otel/otel_test.go, plugins/service/aperture-plugin-fluxninja/otel/provide.go
Metrics scraped by prometheus have sampling rate determined by the scrape interval.
We don't want to send high sampled metrics to the FN Cloud, so in the plugin now duplicates the scraping config and changes the scrape interval.
This PR also changes the base scrape config to use only globally set scrape interval, instead of specyfing it per scrape target.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/481)
=> Split scraping metrics for FN plugin

docs/content/get-started/installation/_category_.yml, docs/content/get-started/playground.md
Reversed the position of Installation and Playground. Now Playground will be first and Installation will be second. 
cc @jaidesai-fn
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/526)
=> position change for installation and playground

cmd/aperture-agent/Dockerfile, cmd/aperture-controller/Dockerfile, pkg/info/build.sh, pkg/plugins/build.sh
Add `GIT_COMMIT_HASH` and `GIT_BRANCH` in the script as earlier it was passed as an argument in the Dockerfile which was not given while running Tiltfile. Now this changes will directly take all the required values from the script and no need to pass it as the argument.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/547)
=> add missing git commit hash and git branch in the script

pkg/info/build.sh
Add check for the git repo in the build script . As the recent changes made in #547 is failing CI in the Cloud repo. So added a check to only run the git command if we have the `.git` dir or else it will take is as the ARG  and also set it as ENV as previously in Cloud repo. 
cc @kwapik , @hdkshingala
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/549)
=> add check for the git repo in the build script

manifests/charts/aperture-controller/templates/controller.yaml
Added Init containers to check the health of embedded Etcd and Prometheus before starting the Controller container.to prevent unwanted controller pod restarts.
Fixes https://github.com/fluxninja/cloud/issues/5304
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/551)
=> Added Init containers for Etcd and Prometheus in controller

docs/content/references/configuration/agent.md, docs/content/references/configuration/controller.md, docs/gen/config/agent/config-swagger.yaml, docs/gen/config/controller/config-swagger.yaml, go.mod, go.sum, manifests/charts/istioconfig/README.md, manifests/charts/istioconfig/templates/envoy_filter.yaml, manifests/charts/istioconfig/values.yaml, operator/config/crd/bases/fluxninja.com_agents.yaml, operator/config/crd/bases/fluxninja.com_controllers.yaml, operator/controllers/agent/config_test.tpl, operator/controllers/agent/configmaps_test.go, operator/controllers/agent/daemonset.go, operator/controllers/agent/daemonset_test.go, operator/controllers/agent/services.go, operator/controllers/agent/services_test.go, operator/controllers/constants.go, operator/controllers/controller/config_test.tpl, operator/controllers/controller/configmaps_test.go, operator/controllers/controller/deployment.go, operator/controllers/controller/deployment_test.go, operator/controllers/controller/services.go, operator/controllers/controller/services_test.go, operator/controllers/mutatingwebhook/agent_pod.go, operator/controllers/mutatingwebhook/agent_pod_test.go, pkg/otel/components.go, pkg/otel/config.go, pkg/otelcollector/otelcollector.go
This commit switches Aperture to use OTEL fork with custom OTLP receiver.
Receiver uses Aperture's GRPC server to listen for OTLP data.
Included in this PR:
* Changes in OTEL configuration.
* Changes in Istio Config chart - only one port to be configured. Breaking change.
* Changes in operator.
Ref: GH-488
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/577)
=> Unify OTEL ports with main server

manifests/charts/aperture-controller/README.md, manifests/charts/aperture-controller/templates/controller.yaml, manifests/charts/aperture-controller/values.yaml
Used a different image for Prometheus readiness check as the earlier one was updated last night and `curl` was removed from it.
Have made the images and init containers configurable so that user can also change the images if they want to.
Fixes #658
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/659)
=> Fixed controller init container image issue

cmd/aperture-agent/agent/otel-component.go
The Agent Group Processor was misplaced before the metrics processor, which was filtering out the `agent_group` attribute.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/700)
=> Fix agent_group population in logs

.circleci/config.yml, .dockerignore, operator/Dockerfile, playground/Tiltfile
This should avoid spurious rebuilds in Tilt caused by stray files.
It definitely made Tilt less sluggish on my machine.
* Added .dockerignore.
* Added it to path-filtering mapping, to ensure everything still builds.
* Added `test` subdir to updated-aperture triggers, I guess it was missing.
* In addition to .dockerignore, ignored `operator` dir for agent and  demoapp (operator is for some reason > 1MB and bloats the docker  context).
* Use caching in operator Dockerfile (as we do in other Dockerfiles).
=> Add .dockerignore and use caching in operator Dockerfile

cmd/aperture-agent/Dockerfile, cmd/aperture-controller/Dockerfile, playground/Tiltfile
Also, removed the "operator" ignore (introduced in #744) from agent in playground Tiltfile
– looks like this is actually needed by plugin.
Interestingly, playground wasn't broken due to failed plugin build, as the
plugin isn't needed there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/753)
=> Start checking for plugin build errors in Dockerfiles 🙃

playground/Tiltfile
This should help avoid refreshing the "(Tiltfile)" resource on code
changes (which happens even in manual mode!).
Watching code changes are handled by docker image watchers, so directly
watching these files is not necessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/755)
=> Stop watching code directly from Tiltfile

pkg/flowcontrol/common/flowcontrol.go, pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go, pkg/policies/dataplane/actuators/concurrency/scheduler/wfq.go, pkg/policies/dataplane/actuators/concurrency/scheduler/wfq_test.go, pkg/policies/dataplane/actuators/rate/rate-limiter.go, pkg/policies/dataplane/engine.go, pkg/policies/dataplane/iface/engine.go, pkg/policies/dataplane/iface/limiter.go, pkg/policies/mocks/mock_engine.go, pkg/policies/mocks/mock_limiter.go
Grpc client timeout is pulled by scheduler from Context.Deadline() and
is used to cap the timeout computed by `tokens*factor`. Note that a lot
things can happen before request is received and processed by scheduler,
so the capped timeout can end up a lot smaller than original client
timeout (even zero or negative). Also, as a temporary hack, timeouts
smaller than 5ms are capped to 0 (this is to avoid running heapAudits
too often).
To support this, now requestContext.timeout == 0 means "don't attempt to
enqueue" and "default timeout" is now removed from scheduler
Resolves #671
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/779)
=> Cap request timeout in scheduler by grpc client timeout

cmd/aperture-agent/agent/otel-component.go, docs/content/concepts/flow-control/flow-label.md, pkg/otelcollector/rollupprocessor/config.go, pkg/otelcollector/rollupprocessor/factory.go, pkg/otelcollector/rollupprocessor/processor.go, pkg/otelcollector/rollupprocessor/processor_test.go
Resolves #535 
- It adds 0.19% of total agent runtime (3% of rollupprocessor itself). IMO acceptable and not worth optimizing further (at least right now)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/782)
=> rollupprocessor: Apply per-batch attribute cardinality limit

playground/Tiltfile
Remove redundant condition  - always point to local SDKs in Tiltfile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/823)
=> playground: minor tweaks in Tiltfile

pkg/otelcollector/consts.go, pkg/otelcollector/metricsprocessor/internal/check_response_labels.go, pkg/otelcollector/metricsprocessor/internal/check_response_labels_test.go, pkg/otelcollector/metricsprocessor/internal/envoy_labels.go, pkg/otelcollector/metricsprocessor/internal/envoy_labels_test.go, pkg/otelcollector/metricsprocessor/internal/internal_suite_test.go, pkg/otelcollector/metricsprocessor/internal/labels_filter.go, pkg/otelcollector/metricsprocessor/internal/sdk_labels.go, pkg/otelcollector/metricsprocessor/internal/sdk_labels_test.go, pkg/otelcollector/metricsprocessor/internal/status.go, pkg/otelcollector/metricsprocessor/internal/status_test.go, pkg/otelcollector/metricsprocessor/processor.go, pkg/otelcollector/metricsprocessor/processor_test.go, pkg/policies/dataplane/engine_test.go, pkg/policies/dataplane/iface/flux-meter.go, pkg/policies/dataplane/resources/fluxmeter/flux-meter.go, pkg/policies/mocks/mock_flux_meter.go
This introduces `aperture.response_status` column in telemetry. It mirrors the implementation of `response_status` label for metrics.
This also extends above logic to include `1xx`, `2xx`, and `3xx` codes as OK instead of only `2xx` codes.
Besides this, some cleanup is done:
1. Above logic is moved from `FluxMeter` to OTEL package. **This changes FluxMeter interface!**
2. A log of logic is moved from `metricsprocessor` to `metricsprocessor/internal` for better visibility and easier separation of functions which are called directly in metricsprocessor and helpers,
3. The above made creating UT much easier, so this PR also includes some.
Ref: https://github.com/fluxninja/cloud/issues/6788
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Response status in telemetry

pkg/otelcollector/metricsprocessor/internal/check_response_labels.go, pkg/otelcollector/metricsprocessor/internal/check_response_labels_test.go, pkg/otelcollector/metricsprocessor/processor.go, pkg/otelcollector/metricsprocessor/processor_test.go
This fixes regression introduced in https://github.com/fluxninja/aperture/pull/828.
Dynamic Telemetry Flow Labels were added before labels filtering, which led them to be incorrectly filtered out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/835)
=> Fix telemetry labels propagation

pkg/otelcollector/metricsprocessor/internal/envoy_labels.go, pkg/otelcollector/metricsprocessor/processor.go
* Workload latency in case of Envoy is calculated as:
```
workload_latency = response_latency - aperture_latency
```
* Workload Latency can become negative in case of connection reset
* If the connection is aborted by Client or Server Envoy immediately terminates the connection for the other endpoint.
* In the Access Log, status code is set as 0 and `response_latency` is set as zero.
* If Authz call to Aperture Agent had succeeded for this request, then aperture_latency is greater than zero.
* This would lead the `workload_latency` to be computed as negative.
* Ignore negative workload latency I.E. don't populate the workload latency column
* Publish Prometheus metrics for flux-meter or workload latency only if the metric column is found
- - -
This change is [<img …
=> Ignore negative workload latency

.circleci/scripts/helm_release.sh
We were using HTTP for communicating with GitHub which is incorrect as it requires providing the token which expires after some time.
Switched to using the SSH as we already store the SSH Keys for Aperture in CircleCi
Fixes #768
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/769)
=> Switched to SSH instead of HTTP for GitHub operations

manifests/charts/aperture-agent/Chart.lock, manifests/charts/aperture-agent/Chart.yaml, manifests/charts/aperture-controller/Chart.lock, manifests/charts/aperture-controller/Chart.yaml
With 2.0.0 an incompatible change was made to image construction logic
See: https://github.com/bitnami/charts/issues/11858#issuecomment-1296892579
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/849)
=> Downgrade bitnami/common to 1.17.1

pkg/panichandler/panichandler.go, plugins/service/aperture-plugin-sentry/sentry/sentrywriter.go
Sentry runs it's own stack capture therefore it's better to run the handler in the same go routine that panic'ed. Otherwise Sentry is unable to distinguish crashes from one another.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/875)
=> panichandler: process panic handlers in the same go routine

docs/content/get-started/playground.md
Closes: #889 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/890)
=> Fix Wrong link associated in playground docs

playground/tanka/lib/apps/aperture-grafana/main.libsonnet
This increases level of detail in charts, because default interval (15s)
resulted in effectively capping interval in queries to 1m.
Before (start & stop of workload generator):
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/908)
=> playground grafana: Set scrape interval in prometheus data source

sdks/aperture-java/src/main/java/com/fluxninja/aperture/example/ArmeriaClient.java, sdks/aperture-java/src/main/java/com/fluxninja/aperture/example/ArmeriaServer.java
Fix https://github.com/fluxninja/aperture/issues/891
This PR fix the first part of the issue mention by @hasit  . Where ENV variable where missing from armeria client and server due to which aperture-java sdk was failing on Tilt playground when user clicked on `trigger library example`
as discuss with @krdln , raising this PR... second part will be done by @IridiumOxide soon.
cc @krdln 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/913)
=> Add ENV variable for armeria client and server

docs/content/get-started/playground.md, docs/content/get-started/policies/blueprints.md, docs/content/tutorials/flow-control/basic-concurrency-limiting.md
* Dry run docs
* Add links to versioned Blueprints in GitHub
* Fix playground `cd` command
* Depends on [Tech docs PR](https://github.com/fluxninja/aperture-tech-docs/pull/97)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/914)
=> Dry run docs and link versioning

docs/content/get-started/policies/blueprints.md, docs/content/introduction.md
* Version of Aperture is versioned with the docs and exported as a variable.
* Links, install commands etc. can be templated based on the version variable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/920)
=> Docs: Aperture version is self-contained inside docs

.circleci/config.yml
Added `--allow-multiple-definition` flag for fixing the `multiple definition` error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/923)
=> Fixed multiple definition error on build

pkg/alerts/alert.go, pkg/log/log.go, pkg/log/log_suite_test.go, pkg/log/samplers.go, pkg/log/samplers_test.go, pkg/otelcollector/alertsreceiver/processor.go, pkg/otelcollector/helpers.go, pkg/otelcollector/metricsprocessor/internal/check_response_labels.go, pkg/otelcollector/metricsprocessor/internal/sdk_labels.go, pkg/otelcollector/metricsprocessor/processor.go, pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go, pkg/policies/flowcontrol/actuators/concurrency/load-actuator.go, pkg/policies/flowcontrol/resources/classifier/classification-engine.go, pkg/policies/flowcontrol/service/envoy/authz.go, pkg/watchdog/watchdog.go
by using zerolog.BurstSampler instead of zerolog.RandomSampler. This
ensures that one-off and low-frequency events are always logged.
* Added log.NewRatelimitingSampler() helper that creates
a zerolog.BurstSampler with sane defaults.
* Added log.Autosample() that automates creation of per-message
BurstSampler variables (this is slightly less performant, so it's not
used on datapath).
Also:
* Added log.Bug(), whic is like Panic() (intended for "impossible"
cases), but for "continuable" errors. Currently it's just Autosample()
Warn() + "bug" label, but in future we should add more visibility, like
sentry reporting.
Drive-by:
* Downgraded various non-critical logs from Error to Warn.
* Removed sampling from Trace() logs, as it seems a bit contradictory.
- - -
This change is [<img …
=> Improve visibility of sampled logs

.circleci/continue-workflows.yml, sdks/aperture-java/.circleci/config.yml, sdks/aperture-java/.circleci/continue-workflows.yml
This is required to maintain separate releasing process for `aperture-java` and `aperture`.
In such setup all the publishing is done from the `aperture-java` repository and we can have separate tags.
Closes: GH-926
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/935)
=> Move aperture-java publishing jobs to SDK

sdks/aperture-java/build.gradle.kts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/931)
=> Make Gradle build java SDK compatible with JDK 1.8

pkg/log/log.go, pkg/log/samplers.go, pkg/net/grpc/helpers.go, pkg/policies/flowcontrol/service/check/check.go, pkg/policies/flowcontrol/service/envoy/authz.go, pkg/policies/flowcontrol/service/envoy/authz_test.go
Added warnings on client IP retrieval failure and entity lookup failure.
Also, converted these failures to fail-early, so they're more
dicsoverable. We might lose some things (like stats) by not processing
such request further, but since we don't have any metadata about
services, such information was not too helpful.
This is a step forward to #882.
Drive-by:
* Ripped out comments suggesting that on nil EntityCache we do some sort of fallback service detection via Host – this logic is long gone now.
* Entity cache is assumed to be non-nil.
* Added helpers in grpc package to simplify "log and return grpc error reusing the same message".
* Refactored if-else to switch-case in authz Check, as `DecisionType != REJECTED` was weird to read.
* Removed Eventually() in authz tests, it's no longer …
=> Start warning on entity lookup failure in authz and flowcontrol

.codespellignore, operator/controllers/agent/reconciler.go, operator/controllers/constants.go, operator/controllers/controller/reconciler.go, operator/main.go
Signed-off-by: Chirayu Kapoor <dev.csociety@gmail.com>
Fixes: https://github.com/fluxninja/aperture/issues/883
Created an event to be generated by the Agent and Controller if in case the minimum Kubernetes version is not satisfied.
To grab the current Kubernetes version followed the same method as kubectl: https://github.com/kubernetes/kubectl/blob/393c40f5c4acbe48edbc70f8c8696bb623744b76/pkg/cmd/version/version.go#L139
aperture-agent-manager log:
```
1.6685863398395433e+09	DEBUG	events	Kubernetes version v1.25.0 is not supported. Please use a kubernetes cluster with version v1.27.0 or above	{"type": "Warning", "object": {"kind":"Agent","namespace":"aperture-agent","name":"agent","uid":"ffe0db7d-fcf5-4685-84b2-da04ae7534f6","apiVersion":"fluxninja.com/v1alpha1","resourceVersion":"14668896" …
```
=> Added the functionality to check for the minimum supported kubernetes version

docs/content/references/configuration/controller.md
Typo in the `controller.md` file .
Needed `Controller` and Agent was written.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/952)
=> docs : Fix typo in the reference section for controller 

pkg/otelcollector/enrichmentprocessor/processor.go, pkg/otelcollector/helpers.go, pkg/otelcollector/tracestologsprocessor/processor.go
Follow up to #956. Noticed these other helpers when closing the editor
:laughing:.
Callbacks passed to these functions were always infallibe.  Also,
early-return in such iteration is a bad idea anyway. If a need for
fallibility arises in the future, it could be implemented like in
IterateLogRecords.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/958)
=> otelcollector/helpers: Remove unused fallibility from iterate helpers

cmd/aperture-agent/agent.go, cmd/sdk-validator/main.go, pkg/discovery/kubernetes/kubernetes_discovery.go, pkg/discovery/kubernetes/provide.go, pkg/discovery/static/provide.go, pkg/discovery/static/static_discovery.go, pkg/discovery/static/static_discovery_test.go, pkg/entitycache/entity_cache.go, pkg/mocks/mock-trackers.go, pkg/notifiers/tracker.go, pkg/policies/flowcontrol/provide.go, pkg/policies/flowcontrol/service/check/check.go, pkg/policies/flowcontrol/service/check/check_test.go, pkg/policies/flowcontrol/service/check/provide.go, pkg/policies/flowcontrol/service/envoy/authz.go, pkg/policies/flowcontrol/service/envoy/authz_test.go, pkg/policies/flowcontrol/service/provide.go, pkg/policies/flowcontrol/servicegetter/servicegetter.go, test/aperture_suite_test.go
Previous attempt (#943) was partially reverted as it was overeager. This time
it's emitting only a warning. (and only in some cases)
Start warning on failed IP to entity lookup, but only when service
discovery is actually enabled (when service discovery is disabled,
failure to do entity lookup is normal condition and glob-policies can
still work).
This required making service discovery registration "more formal".
Previously, service discovery simply wrote to Trackers, which made it
impossible to differentiate between discovery not-working vs being
disabled. This commit introduces EntityTrackers, which manages service
discoveries and hands out EventWriters.
Also:
* Extracted EventWriter interface from Trackers.
* Extracted shared "IP to services" logic to ServiceGetter.
* Fixed obtaining …
=> Warn on unknown entity (take two)

pkg/metrics/schema.go, pkg/policies/flowcontrol/provide.go, pkg/policies/flowcontrol/servicegetter/metrics.go, pkg/policies/flowcontrol/servicegetter/provide.go, pkg/policies/flowcontrol/servicegetter/servicegetter.go
Adds a `service_lookups_total` metric which tracks IP-to-services lookups (via
entity cache). To differentiate between successful and failed lookups,
status=OK/Error label can be used.
Resolves #882
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/997)
=> Add metrics for IP-to-services lookups

pkg/distcache/logwriter.go, pkg/log/samplers.go
* Move all Info logs from Olric to Debug, as they are too noisy.
* Make sampled logs appear once per 5 minutes instead of once per 5 seconds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1000)
=> Make logs less noisy

sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Constants.java, sdks/aperture-java/version.gradle.kts
As we are moving in lockstep, to avoid confusion, the Aperture Java SDK will follow the same versioning as Aperture main repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1001)
=> Bump Aperture Java SDK to 0.13.0

sdks/aperture-java/README.md
Update Java SDK badge to point to `com.fluxninja.aperture/aperture-java-core` instead of obsolete `com.fluxninja.aperture/aperture-java`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1003)
=> Update Java SDK badge

pkg/alerts/alert.go, pkg/alerts/alert_test.go, pkg/otelcollector/consts.go, pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go, pkg/policies/controlplane/components/alerter.go
* Add helpers for alert channels, so it is not set directly in alert labels.
* Make severity helpers typed, so severity values are unified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1018)
=> Add channel and severity helpers to alerts

pkg/policies/controlplane/components/constant.go, pkg/policies/controlplane/policy.go, pkg/policies/controlplane/runtime/circuit.go, pkg/policies/controlplane/runtime/circuit_test.go, pkg/policies/controlplane/sim/circuit.go, pkg/policies/controlplane/sim/circuit_test.go, pkg/policies/controlplane/sim/components.go, pkg/policies/controlplane/sim/helpers.go, pkg/policies/controlplane/sim/sim_suite_test.go
Added sim.Circuit which can be used to simulate a circuit using given Inputs, capturing listed output signals. Circuit can be defined as list of ConfiguredComponents or parsed from yaml.
Drive-by: Simplify circuit.NewCircuitWithOptions
Resolves #649 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1019)
=> Add basic unit-test framework for testing circuits

cmd/aperture-agent/agent/otel-component.go, docs/content/references/configuration/agent.md, docs/content/references/configuration/controller.md, docs/gen/config/agent/config-swagger.yaml, docs/gen/config/controller/config-swagger.yaml, pkg/metrics/schema.go, pkg/otelcollector/config.go, pkg/otelcollector/rollupprocessor/config.go, pkg/otelcollector/rollupprocessor/factory.go, pkg/otelcollector/rollupprocessor/processor.go, pkg/otelcollector/rollupprocessor/processor_test.go, pkg/otelcollector/rollupprocessor/rollupprocessor_suite_test.go, pkg/policies/flowcontrol/engine.go
Without flow label keys sorted, the rollup was not working properly, as
different order of items was treated as different rollup key.
This changes granularity of data going to FN Cloud from 1 to 10 seconds.
This is needed to have some meaningful rollups.
For better observability in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1027)
=> Improve OLAP telemetry rollup

pkg/otelcollector/rollupprocessor/processor.go, pkg/otelcollector/rollupprocessor/rollup.go
Rollup struct was used both as "single rollup" and "group of rollups".
Splitted it into RollupGroup and Rollup to avoid confusion.
Also, removed mapstructure annotations to avoid confusion that it'as
loaded from config (it's not).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1029)
=> refactor: Clean up rollup types initialization

blueprints/examples/latency-gradient/example.jsonnet, pkg/alerts/alert.go, pkg/alerts/alert_test.go, pkg/otelcollector/alertsexporter/exporter.go, pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go, pkg/policies/controlplane/components/alerter.go
* Properly marshal `alert_channels` alert label to OTEL logs
* Drive-By: remove unused jsonnet import
* Add trace logging to Alertmanager exporter
* Add resolve timeout helpers to Alerts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1034)
=> Fix alerts channel marshall & add resolve timeout helpers

Makefile
Using github.com/alecthomas/participle as a dependency causes `multiple definition` error in linker. This fix allows such multiple definitions when linking.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1039)
=> Fix linker in `make go-test`

docs/content/introduction.md
The front matter fields are preferred and used by Docusaurus, e.g., `og:description`, `og:image`. These are the fields used in social media thumbnails.
Reference - https://docusaurus.io/docs/next/seo#:~:text=Docusaurus%20is%20a%20static%20site,discover%20your%20content%20more%20easily.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1049)
=> Add image and description to Introduction page

docs/content/get-started/installation/controller.md, manifests/charts/aperture-controller/README.md, manifests/charts/aperture-controller/templates/_helpers.tpl, manifests/charts/aperture-controller/templates/ingress.yaml, manifests/charts/aperture-controller/values.yaml
Added support for Ingress to expose etcd and prometheus endpoints in the Controller chart and steps for the same.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1051)
=> Added steps for exposing the etcd and prometheus outside of the cluster

.circleci/continue-workflows.yml, packaging/aperture-agent.yaml
RPM is not allowing `-` in package name and nfpm is only replacing the first `-` in version with `~` so replaced it manually for both.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1057)
=> Fixed the hyphen issue in rpm package name

.circleci/continue-workflows.yml
There is a race between component tag being created, and compund tag being created.
Since we only need the former,
we now get the commit count since latest aperture-agent component tag.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1063)
=> Fix baremetal package building

.circleci/post-release.yaml
When the pipeline is running as part of pre-release jobs, it is not detecting the existing release and instead creating a new one.
Hence, moving it to post-release so that it can detect the release and just upload the packages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1064)
=> Moved release bare metal packages to post-release pipeline

.circleci/continue-workflows.yml, .circleci/post-release.yaml, .circleci/scripts/update_environment.sh, .opsninja.yaml
Currently whenever new changes are merged to cloud main . Demo cluster is update. Similarly this PR will do the update on  `customer demo cluster` whenever new changes are merged to aperture main
The PR has been tested by making minor changes to the files to run the CI . 
Can confirm that it is updating the hash on [argo-manfiests](https://github.com/fluxninja/argo-manifests/commit/dd66e330a58d6b415ad0efd1f2e48d8b000cb119) repo. 
Closes https://github.com/fluxninja/cloud/issues/7810
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1103)
=> Update aperture on customer demo cluster when changes merged to main

manifests/charts/aperture-agent/templates/rbac.yaml, manifests/charts/aperture-controller/templates/rbac.yaml, operator/config/rbac/role.yaml, operator/controllers/agent/clusterrole.go, operator/controllers/agent/clusterrole_test.go, operator/controllers/agent/config_test.tpl, operator/controllers/agent/configmaps_test.go, operator/controllers/agent/reconciler.go, operator/controllers/agent/reconciler_test.go, operator/controllers/controller/clusterrole.go, operator/controllers/controller/clusterrole_test.go, operator/controllers/controller/reconciler.go, operator/controllers/controller/reconciler_test.go
There were duplicate and non-required permissions present in the agent and controller ClusterRole via operator so removed them so that the agent and controller only gets the required permissions in Kubernetes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1088)
=> Cleaned up RBAC permissions in operator for agent and controller

playground/Tiltfile
The condition for creating `controller-service` resource in tilt was incorrect and due to that policy was not getting created when only `aperture-controller` is started on tilt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1121)
=> Corrected resource dependency in tilt file when only controller is started

.gitignore, docs/content/concepts/flow-control/flow-classifier.md, docs/content/concepts/flow-control/flow-label.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1132)
=> docs: add links to introspection APIs for flowcontrol preview

.circleci/continue-workflows.yml, cmd/aperture-agent/Dockerfile, cmd/aperture-controller/Dockerfile, pkg/info/build.sh, pkg/plugins/build.sh, playground/Tiltfile
Fix  https://github.com/fluxninja/aperture/issues/758
Add `--race` flag which build the agent and controller binary passing `go build --race ....` flag.
Usage:
```
tilt up -- --race
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/922)
=> Enable race detection for agent and controller using `--race` flag in tilt dev environment

docs/content/get-started/installation/agent/kubernetes/sidecar.md, operator/controllers/agent/daemonset.go, operator/controllers/agent/daemonset_test.go, operator/controllers/agent/hook.go, operator/controllers/agent/hook_test.go, operator/controllers/agent/old_hook_test.tpl, operator/controllers/agent/reconciler.go, operator/controllers/agent/reconciler_test.go, operator/controllers/constants.go
User has to uninstall and recreate the Agent CR currently to change the installation mode to Sidecar.
With this change, they can just modify the existing CR to change the installation mode and operator will handle the rest.
Restarting all the pods on changing the installation is not feasible so added event in the CR to indicate the same.
Fixes #896 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1089)
=> Added support for changing agent installation mode without re-creation of CR

pkg/info/build.sh
In some places we use the `build.sh` script with `sh` not `bash`. This change updates the if condition to work in both environments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1157)
=> Make `build.sh` work with `sh`

blueprints/examples/static-rate-limiting/gen/dashboards/example.json, blueprints/lib/1.0/blueprints/static-rate-limiting/dashboard.libsonnet
Updated query to use `sum by` to reduce the number of fields for the `Rate Limiter` panel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1161)
=> Update query for rate limit dashboard

pkg/policies/controlplane/components/pulse-generator_test.go
Thought it would be low-effort and helpful to cover https://github.com/fluxninja/aperture/pull/1163 by some tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1168)
=> Add UT for PulseGenerator

blueprints/scripts/generate_all.sh, docs/content/apertureVersion.js, docs/content/concepts/flow-control/flow-control.md, docs/content/get-started/flow-control/sdk/overview.md, docs/content/get-started/installation/agent/bare_metal.md, docs/content/get-started/policies/applying-policies.md, docs/content/get-started/policies/blueprints.md, docs/content/references/bundled-blueprints/latency-gradient-concurrency-limiting.md, docs/content/references/bundled-blueprints/signals-dashboard.md, docs/content/references/bundled-blueprints/static-rate-limiting.md
Remove `v` so that links work on development docs. After pushing this [PR](https://github.com/fluxninja/aperture/pull/1160). Links on development docs are failing . Now the `v` has been handled in the version.js script itself.
Refer this PR for more info https://github.com/fluxninja/aperture-tech-docs/pull/146
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1169)
=> Remove v so that links work on development docs

pkg/utils/goleak.go
Wondered why most unit tests take 5s to run :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1186)
=> tests: Remove unconditional sleep in leak detector

cmd/sdk-validator/main.go, cmd/sdk-validator/validator/common.go
Allow the SDK validator to validate auto-instrumentated services
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1199)
=> SDK validator updates

.circleci/config.yml, .circleci/continue-workflows.yml, cmd/sdk-validator/validator/common.go
SDK validator updates expected `http.target` label to be present and so only worked for traffic control points.
This change makes it work for feature control points with no labels set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1208)
=> Make SDK validator reject Check requests from feature control points

plugins/service/aperture-plugin-fluxninja/otel/provide.go
This prevents overwriting extensions configured in base OTEL config, with the configuration in FN plugin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1252)
=> Do not overwrite OTEL extensions in FN plugin (#1252

.circleci/continue-workflows.yml, .golangci.yaml, .pre-commit-config.yaml, .tool-versions, cmd/aperture-agent/Dockerfile, cmd/aperture-controller/Dockerfile, go.mod, operator/Dockerfile, playground/demo_app/Dockerfile, playground/demo_app/go.mod, playground/graphql_demo_app/Dockerfile, playground/graphql_demo_app/go.mod, sdks/aperture-go/Dockerfile, sdks/aperture-go/go.mod, tools/go/go.mod
This bumps Golang to the latest 1.20 version.
Also, it unifies all Docker builder images to `golang:1.20-bullseye` and final images from `alpine` to `debian:bullseye-slim` (except for operator, as it is recommended to use `distroless` there). This should remove any `glibc` and `musl` compatibility issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1260)
=> Bump Golang to 1.20 (#1260

cmd/aperture-agent/Dockerfile, cmd/aperture-controller/Dockerfile, pkg/policies/controlplane/circuitfactory/graph.go, playground/demo_app/Dockerfile, playground/graphql_demo_app/Dockerfile, sdks/aperture-go/Dockerfile
Newly used `debian-slim` images do not have root certs installed by default.
Drive-by: Fix lint error from new linter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1266)
=> Add missing root certs to images (#1266

cmd/aperture-agent/Dockerfile, cmd/aperture-controller/Dockerfile
This prevents overwriting each others caches when both main binary and plugin binaries are build at the same time.
Ref: GH-1270
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1272)
=> Separate main binary and plugin caches

cmd/aperturectl/cmd/blueprints/pull.go, cmd/aperturectl/cmd/blueprints/root.go, docs/content/get-started/aperture-cli/aperturectl_blueprints.md, docs/content/get-started/aperture-cli/aperturectl_blueprints_generate.md, docs/content/get-started/aperture-cli/aperturectl_blueprints_list.md, docs/content/get-started/aperture-cli/aperturectl_blueprints_pull.md, docs/content/get-started/aperture-cli/aperturectl_blueprints_remove.md, go.mod, go.sum
When `latest` is used as a version for blueprints, resolve it to
the latest stable version and fetch it instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1263)
=> Resolve latest blueprints version to latest stable release

pkg/info/build.sh
The options which we were using to get the rfc-3339 date format with `date` command was not valid so I have updated it with a generic command compatible on both OS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1287)
=> Use generic command in build.sh for linux and macos

cmd/aperturectl/cmd/installation/agent.go, cmd/aperturectl/cmd/installation/controller.go, cmd/aperturectl/cmd/installation/istioconfig.go, cmd/aperturectl/cmd/installation/utils.go
Improved error handling for `aperturectl install` and `aperturectl uninstall` to not throw the error per resource failure but collect them and print at the end.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1329)
=> Improved error handling for aperturectl install/uninstall

pkg/policies/controlplane/components/promql/promql.go
Fixed the job name issue when 2 policies with promql are started.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1331)
=> Fixed same job name issue for promql

cmd/aperturectl/cmd/apply/dynamic-config.go, cmd/aperturectl/cmd/apply/policy.go, cmd/aperturectl/cmd/apply/root.go, cmd/aperturectl/cmd/blueprints/generate.go, cmd/aperturectl/cmd/tui/checkbox.go, docs/content/reference/aperturectl/apply/apply.md, docs/content/reference/aperturectl/apply/dynamic-config/dynamic-config.md
We were getting some nil pointer panics in `aperturectl generate --apply` due to recent changes in `aperturectl apply` command so fixed that and re-added the TUI which was removed during the same change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1340)
=> Fixed nil pointer panic in aperturectl generate

cmd/aperture-agent/agent/otel-config.go, pkg/otelcollector/consts/consts.go
All metrics coming from Prometheus like scrapers have `service.name` label. This adds such label to kubelet metrics, which are not gathered by Prometheus like scraper. This allows better metrics handing in FluxNinja ARC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1341)
=> Add `service.name` label to custom metrics

cmd/aperture-agent/agent/otel-config.go, cmd/aperture-agent/agent/provider.go
This label is required to avoid metrics with same set of labels and timestamp to be pushed to FluxNinja ARC. It causes errors in the metrics backend.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1350)
=> Propagate `instance` in user defined metrics

pkg/cache/cache.go, pkg/otelcollector/metricsprocessor/processor_test.go, pkg/policies/flowcontrol/service/controlpoints/controlpoints.go, plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
GetAll returned the same map as cache uses internally. This map can then
be accessed by GetAll's caller without any synchronization, risking a
data race with Put. To avoid the race, a copy is made and returned.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1373)
=> Avoid data race in cache.GetAll

docs/content/concepts/integrations/flow-control/components/concurrency-limiter.md, pkg/policies/controlplane/components/integrator.go
Integrator assumed max port (and earlier min port) to have valid values in order to calculate sum. These ports should be optional.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1393)
=> integrator: max inport should be optional

cmd/aperturectl/cmd/blueprints/root.go
`aperturectl` was throwing error for `blueprints generate` when the cache directory is not present due to relPath is getting generated after executing pull command and we were generating the `blueprintsDir` path before that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1415)
=> Fixed issue of aperturectl failing on first execution

operator/controllers/agent/config_test.tpl, operator/controllers/agent/configmaps_test.go, operator/controllers/controller/configmaps_test.go
The Configmap test for agent was failing. The main reason was the sequence in which the actual and expected file was getting generated. 
Use the `MatchYAML` which will handle the `key ordering` and other checks. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1428)
=> fix: make confimap test more robust

cmd/aperturectl/cmd/apply/root.go, cmd/aperturectl/cmd/utils/utils.go, docs/content/reference/aperturectl/apply/apply.md
This should make aperturectl use the same config as kubectl
> For configuration, kubectl looks for a file named config in the
> $HOME/.kube directory. You can specify other kubeconfig files by setting
> the KUBECONFIG environment variable or by setting the --kubeconfig flag.
BTW, we call the flag `--kube-config`, should we make it `--kubeconfig`?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1426)
=> aperturectl: Take KUBECONFIG env var into account

playground/Tiltfile, playground/tanka/apps/aperture-agent/mixins.libsonnet, playground/tanka/apps/aperture-controller/mixins.libsonnet, scripts/precommit/check_tanka_show.sh
Now, users can use the `--enable-cloud-plugin` flag on aperture tilt playground and see the  telemetry data from agent and controller will be gathered in our cloud product at this url (https://aperture.latest.dev.fluxninja.com/)
Closes https://github.com/fluxninja/aperture/issues/1361
Usage :
```
tilt up -- --enable-cloud-plugin
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1412)
=> Enable cloud plugin using  API key 

operator/controllers/agent/config_test.tpl, operator/controllers/agent/configmaps_test.go, operator/controllers/controller/configmaps_test.go, operator/controllers/utils.go
We were facing issues in ConfigMap tests as it required the config fields to be in the exact order.
With this change, we need to just add new fields in config and tests should pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1435)
=> Made map comparison order safe in ConfigMap tests

pkg/config/log.go
We observed that Sentry was not getting logs and not showing any crashes on dashboard.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1438)
=> Fixed issue with sentry processing logs

.circleci/continue-workflows.yml
Increased the default timeout for image building to `20m` instead of `10m`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1449)
=> Increased default no output timeout for CircleCI image build

pkg/config/log.go
If we don't enable the sentry plugin, it was trying to add `nil` in log writer which is causing nil pointer panics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1458)
=> Added nil check for using provided writers in logger

pkg/policies/infra/actuators/podscaler/pod-scaler.go
* Wait for previous scale operation to cancel before starting a new one
* Retry scale operation with backoff
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1472)
=> Robust scale actuation

docs/content/reference/configuration/agent.md, docs/content/reference/configuration/controller.md, docs/content/reference/policies/spec.md, docs/gen/config/agent/metadata, docs/gen/config/controller/metadata, docs/gen/policy/metadata, docs/tools/swagger/swagger-templates/config.gotmpl
* Removed noisy table of contents sections with dummy operations from
policy docs.
* Removed "Properties" header. Didn't provide too much value and ate
space.
* Injected "schema-docs" class to policy, agent and controller pages, so
they can be styled differently.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1475)
=> docs: gen: Tweaks to policy documentation generation

playground/Tiltfile, playground/scenarios/autoscaling/dashboards/main.jsonnet, playground/scenarios/autoscaling/metadata.json, playground/scenarios/demo-app/dashboards/main.jsonnet, playground/scenarios/demo-app/metadata.json, playground/scenarios/graphql-example-1/dashboards/main.jsonnet, playground/scenarios/graphql-example-1/metadata.json, playground/scripts/render-dashboard.sh, playground/tanka/lib/apps/aperture-grafana/main.libsonnet
Grafana dashboards will be generated using the same policy blueprints bundle instead of static one from `lib/apps`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1474)
=> Generate dashboards from blueprints in playground

cmd/aperture-agent/agent/provider.go
Without this label, there could be duplicate metrics when container restarts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1502)
=> Add missing `process_uuid` label to custom metrics

pkg/cache/cache.go, pkg/cache/cache_suite_test.go, pkg/cache/cache_test.go
Right now, the period is hardcoded to 30s (so effective expiry is 30s–1m). We
can make it configurable in the future, if we want, but I didn't feel it's a
must have.
Resolves #1345
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1504)
=> Add simple epoch-based expiry to cache.Cache

operator/controllers/agent/daemonset_test.go, operator/controllers/controller/deployment_test.go, operator/controllers/mutatingwebhook/agent_pod_test.go, operator/controllers/utils.go, operator/controllers/utils_test.go, pkg/jobs/job-group.go, pkg/jobs/jobs_test.go, pkg/notifiers/fx-driver.go, pkg/platform/platform.go, pkg/platform/readiness.go, pkg/policies/controlplane/policy-factory.go, pkg/status/status-service.go, pkg/watchdog/watchdog.go, test/readiness_test.go
- Add platform's readiness status under `/system/readiness/component/platform` path to mark agent as ready
- Rename status paths
- Rename `subsystem` -> `system`
- Rename `jg` -> `job-group`
- Add test for platform readiness status
=> Add readiness system in status registry

pkg/status/status-service.go, test/aperture_suite_test.go, test/readiness_test.go
In this change, we check for components under `/system/readiness` to all be ready. If any of the components are not ready, we fail the test. This check needs to pass 2 times repeatedly before we can pass the test because some of the OTEL components might not be ready yet.
=> Update readiness test in aperture test suite

plugins/service/aperture-plugin-fluxninja/otel/otel_test.go, plugins/service/aperture-plugin-fluxninja/otel/provide.go
Scrape interval for metrics sent to FN ARC is 10 seconds. Having batching set at the same value (10 seconds) may lead to two data points for the same metrics sent in the same batch and thus rejected.
=> Reduce metrics batching time

plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
Agents know only about Control Points present on their Nodes, so all of them need to report CPs to FN ARC instead of only Agent Leader doing so.
=> Report Flow Control Points by all Agents

playground/Tiltfile
Fixed the issue where even after setting `--only`, tilt was starting scenarios.
Examples:
```
tilt up -- --only agent controller
tilt up -- --only agent controller istio
```
CC: @sudhanshu456 
**Release Notes:**
- New Feature: Added support for `--only` flag to Tilt.
- Bug fix: Fixed an issue where scenarios were still starting even after setting `--only`.
=> Fixed only flag not working properly in tilt

playground/Tiltfile, playground/scripts/deps_install.sh
Bug fix: Fixed the issue with chart rendering when helm repo is missing. 
- Updated `helm dependency build` command to `helm dependency update`.
- Removed unused function `refresh_chart_dependencies`.
=> Fixed the charts render when helm repo is missing

docs/content/get-started/integrations/flow-control/sdk/javascript/manual.md
Closes https://github.com/fluxninja/aperture/issues/1575
Documentation: Added hyperlink to NPM package page for Aperture Javascript SDK in the documentation.
=> docs: add js-sdk npm link to docs

Makefile
**Purpose:** This pull request adds a new feature to the Makefile that copies policy CRD. 
- New Feature: Adds support for copying policy CRD in the Makefile.
=> Update makefile to copy policy CRD

.dockerignore, cmd/aperture-agent/Dockerfile, cmd/aperture-controller/Dockerfile
This pull request updates the Dockerfiles to use `build-config.yaml` instead of `config.yaml`. It also modifies the `.dockerignore` file to include `cmd/*/build-config.yaml` and exclude `*.yaml`. This change is a `Chore` that improves the build process.
=> Use per-cmd build-config.yaml in Dockerfiles

pkg/info/build.sh
This pull request adds a script to build a Go binary and inject build-time variables, which is used in every Dockerfile requiring version endpoint. 
- Chore: Adds `build.sh` script for building Go binaries with build-time variables.
=> Restore build.sh in info package

extensions/sentry/provide.go
Bug fix: This pull request adds a nil pointer check in setupSentryWriter function to prevent any potential issues.
=> Add nil pointer check in setupSentryWriter

pkg/discovery/kubernetes/provide.go, pkg/discovery/kubernetes/service-discovery.go, pkg/metrics/schema.go
New Feature: This pull request adds the ability to export metrics for pod count in Kubernetes clusters. Users can now monitor their clusters more effectively with this new feature. Various Kubernetes metrics such as namespace name, node name, status, replicaset name, daemonset name, statefulset name, job name, cronjob name, and deployment name have also been added.
=> Export metrics for with pod count

pkg/discovery/kubernetes/provide.go, pkg/discovery/kubernetes/service-discovery.go, pkg/metrics/schema.go
Reverts fluxninja/aperture#1588
While we discuss the trade-offs of making this change.
Revert: This pull request reverts a previous change while discussing its trade-offs. The changes include removing unused imports and dependencies, removing Prometheus registry and election dependency from FxInSvc, updating newServiceDiscovery function call, removing podCounter and election fields, and removing k8s metrics constants.
=> Revert "Export metrics for with pod count"

.circleci/scripts/docker_build.sh, .dockerignore, cmd/aperture-agent/Dockerfile, cmd/aperture-controller/Dockerfile, pkg/config/koanf-unmarshaller.go, pkg/otelcollector/rollupprocessor/processor_test.go, scripts/build_aperturectl.sh
Aperture Agent/Controller version was not properly passed to the Docker image.
Also, this PR changes `context.TODO` to `context.Background` in OTEL tests. This changes is used as trigger to build new Aperture images with proper versions.
This pull request fixes the Aperture Agent/Controller version that was not properly passed to the Docker image. Additionally, it changes `context.TODO` to `context.Background` in OTEL tests, which triggers building new Aperture images with proper versions.
- Bug fix: Fixed Aperture Agent/Controller version not being properly passed to Docker image.
- Test: Replaced `context.TODO()` with `context.Background()` in OTEL tests.
- Chore: Added support for passing directory path as argument and added check for git directory before setting git …
=> Fix Aperture Version build arg

.circleci/post-release.yaml, .circleci/scripts/compile.sh
Sets correct env var for compiling the binary for NFPM
This pull request fixes packaging releases by setting the correct environment variable for compiling the binary for NFPM. It also updates the `git push` command with the `--set-upstream` flag. This is a bug fix that ensures the binary is compiled correctly and can be packaged for release.
=> Fix packaging releases

.dockerignore, cmd/aperturectl/cmd/build/build.go
We were checking non-empty so even when we pass commit and branch, it was setting them to unknown as the .git directory was not copied and the git command was throwing errors.
Bug fix: Fixed an issue where builds were not getting the correct commit and branch information due to errors thrown by the git command. The changes include updating the `getLdFlags` function to find the git commit hash and branch separately, and adding `.git` to the list of files that should not be ignored by Docker.
=> Fixed an issue of builds not getting commit and branch

pkg/platform/platform.go
This change allows easier debugging when app is being stopped because of received signal like SIGTERM.
- Log received signals before stopping the app for improved debugging 🛠️
> Oh, signals we receive, 📡
> In logs, we now believe. 📚
> Debugging made a breeze, 💨
> With this PR, we're pleased! 😊
=> Log received signal before stopping app

api/aperture/policy/language/v1/flowcontrol.proto, api/aperture/policy/language/v1/policy.proto, api/buf.lock, api/gen/proto/go/aperture/policy/language/v1/flowcontrol.pb.go, api/gen/proto/go/aperture/policy/language/v1/policy.pb.go, blueprints/gen/jsonschema/_definitions.json, cmd/aperturectl/cmd/apply/policy.go, cmd/aperturectl/cmd/blueprints/generate.go, cmd/aperturectl/cmd/compile.go, cmd/aperturectl/cmd/root.go, cmd/aperturectl/cmd/utils/utils.go, cmd/aperturectl/main.go, docs/content/assets/openapiv2/aperture-controller.swagger.yaml, docs/content/assets/openapiv2/aperture.swagger.yaml, docs/content/reference/policies/spec.md, docs/gen/policy/policy.yaml, docs/tools/swagger/process-go-tags.go, docs/tools/swagger/swagger-templates/config.gotmpl, pkg/config/validator.go, pkg/policies/controlplane/validator.go, pkg/policies/controlplane/validator_test.go, pkg/webhooks/policyvalidator/validator.go
Release Notes:
- Deprecates outdated fields and functions
- Adds validation tags to improve code quality
- Updates error messages for better clarity
- Adds new flags to the CLI tool
- Improves Swagger validation with deprecation warnings
> "Deprecated fields are now gone,  
> Validation tags have been put on.  
> Error messages are clear and bright,  
> CLI tool has new flags in sight.  
> With Swagger, warnings now appear,  
> This PR brings good changes near."
=> Deprecated warnings/errors in aperturectl and docs

cmd/sdk-validator/main.go, sdks/aperture-java/dockerfiles/javaagent/armeria/Dockerfile, sdks/aperture-java/dockerfiles/javaagent/netty/Dockerfile, sdks/aperture-java/dockerfiles/middlewares/armeria-tls/Dockerfile, sdks/aperture-java/examples/armeria-example/src/main/java/com/fluxninja/example/ArmeriaClient.java, sdks/aperture-java/examples/armeria-example/src/main/java/com/fluxninja/example/ArmeriaServer.java, sdks/aperture-java/examples/netty-example/src/main/java/com/fluxninja/example/NettyServer.java, sdks/aperture-java/examples/netty-example/src/main/java/com/fluxninja/example/ServerInitializer.java, sdks/aperture-java/examples/spring-example/src/main/java/com/fluxninja/example/SpringBootApp.java, sdks/aperture-java/examples/spring-example/src/main/java/com/fluxninja/example/controller/AppController.java, sdks/aperture-java/examples/spring-example/src/main/java/com/fluxninja/example/filter/ApertureFeatureFilter.java, sdks/aperture-java/examples/standalone-example/src/main/java/com/fluxninja/example/App.java, sdks/aperture-java/examples/tomcat-example/src/main/java/com/fluxninja/example/filter/ApertureFeatureFilter.java, sdks/aperture-java/javaagent/README.md, sdks/aperture-java/javaagent/agent/src/main/java/com/fluxninja/aperture/instrumentation/Config.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDKBuilder.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Constants.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ApertureFilter.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ApertureFilter.java, sdks/aperture-java/version.gradle.kts
Release Notes:
- New Feature: Adds TLS configurability to the Java SDK, allowing users to provide SSL certificate and key files.
- Documentation: Updates various Dockerfiles, examples, and documentation files to support this change.
> "Secure connections now abound,
> With TLS configurability newly found.
> No more worries of data theft,
> Our Java SDK is now top-notch."
=> Add TLS configurability to Java SDK

.pre-commit-config.yaml, .tool-versions
with the latest version for circleci cli the validate command fails if there in no workflow to run in yaml file.
Updated the pre-commit hooks to handle the know error. https://github.com/fluxninja/pre-commit-hooks/pull/28
Tested it on local
Release Notes:
- Bug fix: Upgraded CircleCI CLI version to `0.1.25638` and added a check for known errors to handle validation errors when there is no workflow to run in the YAML file.
> "CircleCI validation, oh what a pain,
> But fear not, this PR has come to our gain.
> With an upgrade and a check, 
> We can now validate without a wreck."
=> fix: upgrade circleci cli and add check for know errors

.github/workflows/openai-review.yml
**Chore:**
- Updated `.github/workflows/openai-review.yml` to use `gpt-4` as the `openai_heavy_model`
- Set `max_files_to_summarize` parameter to 40
- Simplified `concurrency` section in the workflow file
> 🎉 A new model takes the stage, 🤖
> GPT-4, our code review sage. 🧙‍♂️
> With limits raised and simplified flow, 📈
> Our GitHub Actions swiftly grow! 🚀
=> update reviewer to use gpt-4

cmd/aperture-agent/config/types.go, docs/content/get-started/integrations/metrics/rabbitmq.md, docs/content/reference/configuration/agent.md, docs/gen/config/agent/config-swagger.yaml, extensions/integrations/otel/rabbitmqreceiver/rabbitmqreceiver.go, manifests/charts/aperture-agent/templates/agent.yaml, manifests/charts/aperture-controller/templates/controller.yaml, operator/config/crd/bases/fluxninja.com_agents.yaml
- Support for environment variables in `CustomMetricsConfig` and RabbitMQ configurations 🌍
- Improved RabbitMQ receiver module loading 🐇
> 🎉 Environment variables, now we can use,
> In configs, they bring flexibility to choose.
> RabbitMQ receiver, always ready to load,
> A better experience, this update bestowed. 🚀
=> Documented ways to use environment variables in rabbitmq OTEL receiver

.circleci/continue-workflows.yml
**Bug fix:**
- Prevents uploading packages to GCP for darwin OS by adding an OS check in `.circleci/continue-workflows.yml`
> 🎉 No more darwin uploads, we say,
> 🛠️ A bug fix that saves the day!
> 🌐 To GCP, packages now go,
> 🚀 With gcloud commands, smooth as a bow. 🏹
=> fix: add check for darwin to upload packages

pkg/policies/controlplane/validator.go
Closes: GH-1690
- Added mutex-protected map for FluxMeter names to prevent duplicates in the validation process
> 🎉 A map now stands, guarding our land,
> 🛡️ Mutex-protected, duplicates detected,
> 🌟 FluxMeter names, no more the same,
> 🚀 Our code's refined, a brighter future designed. 🎉
=> Handle multiple definitions of FluxMeter with same name

cmd/aperturectl/cmd/blueprints/root.go, cmd/aperturectl/cmd/root.go
Disabled the help of pflags to get the correct output with `aperturectl -h`
There was an issue with remote URLs as uri for aperturectl blueprints command which is fixed.
- Added support for remote URLs as URIs in `aperturectl blueprints` command
- Disabled pflags help for correct output with `aperturectl -h`
> 🌐 Remote URLs, now we embrace, 🤗<br>
> For blueprints, a wider space. 🚀<br>
> With pflags help, no more collide, 🛠️<br>
> A better experience, we provide! 🎉
=> Fixed aperturectl help and blueprints uri issue

docs/content/get-started/integrations/flow-control/sdk/java/armeria.md, docs/content/get-started/integrations/flow-control/sdk/java/auto-instrumentation.md, docs/content/get-started/integrations/flow-control/sdk/java/netty.md, docs/content/get-started/integrations/flow-control/sdk/java/springboot.md, docs/content/get-started/integrations/flow-control/sdk/java/tomcat.md, sdks/aperture-java/javaagent/README.md, sdks/aperture-java/javaagent/agent/src/main/java/com/fluxninja/aperture/instrumentation/Config.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDKBuilder.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ApertureFilter.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ApertureFilter.java
Also rename 'blockedPaths' to 'ignoredPaths'
- Renamed `blockedPaths` to `ignoredPaths` across SDK libraries and documentation
- Added support for path ignoring in Armeria, Netty, Spring Boot, and Tomcat integrations
- Provided code snippets demonstrating the new functionality
> 🎉 With paths ignored, we've soared, 🚀
> In Armeria, Netty, and more! 🌟
> From blocked to ignored, we've roared, 🦁
> A better SDK is now in store! 🛠️
=> Add information on path ignoring to SDK libraries documentation

sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Constants.java, sdks/aperture-java/lib/netty/src/main/java/com/fluxninja/aperture/netty/ApertureServerHandler.java, sdks/aperture-java/lib/netty/src/main/java/com/fluxninja/aperture/netty/NettyUtils.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ApertureFilter.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ServletUtils.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ApertureFilter.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ServletUtils.java, sdks/aperture-java/version.gradle.kts
- Added support for custom control point names in `CheckHTTPRequest` across various classes and methods.
> 🎉 A new feature we bring, with joy and cheer,
> Custom control points now appear,
> In requests they'll shine, so bright and clear,
> Enhancing our library, a milestone to revere! 🌟
=> Add control point name configurability to servlet filters and netty

.circleci/continue-workflows.yml, .pre-commit-config.yaml, pkg/metrics/schema.go, pkg/policies/autoscale/kubernetes/discovery/autoscale-control-points.go, pkg/policies/autoscale/kubernetes/discovery/provide.go
- Added Prometheus metrics and improved error handling to the Kubernetes Control Point Discovery module
- Introduced a `podNotifier` struct for leader change notifications
**Chore:**
- Updated Python version in CircleCI workflows
- Updated pre-commit hook versions and added codespell hook
> 🎉 A new dawn rises, metrics now gleam,
> 🌟 With pod notifiers, our code's a dream.
> 🐍 Python updated, hooks refined,
> 🚀 This PR's changes, truly shine!
=> Export metrics with pod count

.circleci/continue-workflows.yml
**Release Notes:**
- Chore: Update `circleci/gcp-gcr` orb to version 0.15.1
- Refactor: Modify job parameters, cache saving, and workflows
- Documentation: Provide a checklist for testing, documentation, and breaking changes
> 🎉 A new orb version we embrace,
> With job parameters in place.
> Cache saving and workflows refined,
> And checklists to keep in mind. 🚀
=> Update circleci/gcp-gcr orb to v0.15.1

blueprints/blueprint-assets-generator.py, cmd/aperturectl/cmd/blueprints/generate.go, cmd/aperturectl/cmd/blueprints/list.go, cmd/aperturectl/cmd/blueprints/values.go, cmd/aperturectl/cmd/root.go, cmd/aperturectl/cmd/utils/globals.go, cmd/aperturectl/cmd/utils/utils.go, pkg/policies/controlplane/components/ema.go, scripts/jsonnet-lib-gen.py
- Support for handling deprecated blueprints with a `deprecation_message` property
- Options to allow or disallow deprecated blueprints in various commands
- Improved error messages for invalid blueprint names
**Refactor:**
- Introduced a new `utils` package and removed unused variable
**Style:**
- Removed unused import and multiline string in `scripts/jsonnet-lib-gen.py`
> 🎉 Deprecated blueprints, we now embrace, 📚
> With options and warnings, keeping pace. 🚀
> Error messages improved, code refined, 🛠️
> A utils package added, intertwined. 🌟
=> blueprints: deprecation tooling

docs/content/get-started/integrations/metrics/aerospike.md, docs/content/get-started/integrations/metrics/apache-web-server.md, docs/content/get-started/integrations/metrics/chrony.md, docs/content/get-started/integrations/metrics/couchdb.md, docs/content/get-started/integrations/metrics/expvar.md, docs/content/get-started/integrations/metrics/f5-bigip.md, docs/content/get-started/integrations/metrics/haproxy.md, docs/content/get-started/integrations/metrics/httpcheck.md, docs/content/get-started/integrations/metrics/memcached.md, docs/content/get-started/integrations/metrics/microsoft-sql-server.md, docs/content/get-started/integrations/metrics/mongodb.md, docs/content/get-started/integrations/metrics/mysql.md, docs/content/get-started/integrations/metrics/nginx.md, docs/content/get-started/integrations/metrics/nsxt.md, docs/content/get-started/integrations/metrics/oracledb.md, docs/content/get-started/integrations/metrics/postgresql.md, docs/content/get-started/integrations/metrics/rabbitmq.md, docs/content/get-started/integrations/metrics/redis.md, docs/content/get-started/integrations/metrics/riak.md, docs/content/get-started/integrations/metrics/sap-hana.md, docs/content/get-started/integrations/metrics/snowflake.md, docs/content/get-started/integrations/metrics/sshcheck.md, docs/content/get-started/integrations/metrics/vcenter.md, docs/content/get-started/integrations/metrics/zookeeper.md, docs/content/reference/aperturectl/build/agent/agent.md, docs/content/reference/aperturectl/build/controller/controller.md
- Added documentation for integrating metrics from various sources using Aperture Agent's receiver extensions.
> 🎉 A myriad of metrics we bring, 📊
> From many sources, they now spring. 🌱
> With Aperture Agent by our side, 🤖
> In data-driven insights, we confide. 💡
=> Add docs for receivers that support metrics type

.tool-versions
Due to https://github.com/tilt-dev/tilt/issues/6102
@openai: ignore
=> playground: downgrade tilt to 0.32.0

api/Makefile, api/buf.gen.aperture-grpc-ecosystem.yaml, api/buf.gen.aperture-langs.yaml
- Remove the deprecated remote plugin, move to newly added official community plugin
- Ref: https://github.com/bufbuild/plugins/issues/489
- Break up apreture buf gen file because `buf generate` now complains if there are more than 10 remote plugins
- langs for languages remote plugins
- grpc-ecosystem for grpc-ecosystem related remote plugins
=> Use the `community/mitchellh-go-json` remote plugin

.github/workflows/languagetool.yaml, .github/workflows/openai-review.yml, .github/workflows/vale.yml
**Chore:**
- Restrict GitHub Actions workflows to `main` branch pull requests
> 🎉 Oh, the joy of a focused run, 🏃‍♂️<br>
> On `main` branch, our tasks are done. 🌟<br>
> With filters set, resources saved, 💾<br>
> Our workflows now well-behaved! 🥳
=> actions: target branch to main for some actions

pkg/policies/controlplane/runtime/circuit.go
**Refactor:**
- Optimized `Circuit` setup function by removing a duplicate call to `prometheus.Labels` constructor in `pkg/policies/controlplane/runtime/circuit.go`.
> 🎉 A duplicate call we did find, 🕵️‍♂️
> In the Circuit setup, it was left behind. 🚧
> With swift action, we made it right, 🛠️
> Now our code is clean and light! 💡
=> Fix metrics

.github/styles/Vocab/FluxNinja/accept.txt, docs/content/concepts/flow-control/flow-label.md, docs/content/concepts/flow-control/flow-selector.md, docs/content/get-started/integrations/flow-control/sdk/sdk.md, docs/content/reference/configuration/agent.md, docs/content/reference/configuration/controller.md, docs/content/reference/observability/prometheus-metrics/common.md, docs/gen/config/agent/config-swagger.yaml, docs/gen/config/controller/config-swagger.yaml, docs/gen/config/extensions/fluxninja/extension-swagger.yaml, docs/tools/swagger/swagger-templates/config.gotmpl, extensions/fluxninja/extconfig/extconfig.go, operator/config/crd/bases/fluxninja.com_agents.yaml, operator/config/crd/bases/fluxninja.com_controllers.yaml, pkg/net/grpc/client.go, pkg/net/grpc/server.go, pkg/net/grpcgateway/grpcgateway.go
Fix the terminology of gRPC.
- Updated terminology from "GRPC" to "gRPC" across documentation files, comments, and struct names.
> 🎉 gRPC now spelled right, we see,
> Consistency throughout the spree,
> Docs and code aligned with glee,
> Celebrate this change with me! 🥳
=> GRPC -> gRPC

operator/api/common/common_types.go, operator/config/crd/bases/fluxninja.com_agents.yaml, operator/controllers/agent/configmaps.go, operator/controllers/agent/reconciler.go, operator/controllers/utils.go
**Bug fix:**
- Improved handling of Controller client certificate in Agent's configuration
- Ensured correct certificate setting even when sidecar is disabled
- Updated key name for Controller client certificate in ConfigMap data
> 🎉 A bug we did smite, 🐛
> With certificates set right, 🔐
> Sidecar or not, 🚗
> The Agent's got what it sought! 🤖
=> Fixed an issue with operator failing to set controller cert correctly in agent

.github/workflows/openai-review.yml
- Chore: Removed `max_files_to_summarize` option from OpenAI Reviewer workflow
> 🎉 A change so small, yet it stands tall,
> Removing limits, we now can call.
> The workflow's free, to summarize all,
> Embrace the update, let's have a ball! 🥳
=> reviewer: remove redundant option

operator/api/common/common_types.go, operator/config/crd/bases/fluxninja.com_agents.yaml, operator/controllers/agent/reconciler.go, operator/controllers/namespace/reconciler.go
**Bug fix:**
- Fixed controller client cert issue in agent sidecar mode
- Improved validation for optional fields in `ControllerClientCertConfig`
- Enhanced reconciliation process for config map, handling endpoints and deletion of resources installed for DaemonSet mode of Agent
> 🎉 A bug we've slain, sidecar mode's gain, 🚀
> Validation improved, our code further soothed. 🛠️
> Reconciliation refined, endpoints aligned, 🌐
> Farewell to resources, DaemonSet forces. 🗑️
=> Fixed controller client cert issue in agent sidecar mode

README.md
**Security:**
- Removed CircleCI token from the build status badge in README.md
> 🎉 Secrets hidden, safe and sound,
> No more tokens to be found.
> With a simple change we cheer,
> Our project's security is now clear! 🛡️
=> Drop circleci token from build status badge to fix it

pkg/policies/controlplane/runtime/circuit.go
We delete some metrics for invalid readings. So they get deleted twice.
Deleting a deleted metric is not bad, so we can just handle this and log
in setup.
- Improved error handling in circuit setup function by logging errors during metrics deletion and returning nil instead of multi-error when no errors are present.
> 🎉 Oh, rejoice, for we have caught the bug! 🐛
> In circuit setup, it hid snug. 🌿
> With better logs, we now unveil 📜
> The errors that once made us fail. 💪
=> Don't pass metric deletion error in circuit

.circleci/continue-workflows.yml, .circleci/post-release.yaml, sdks/aperture-java/.circleci/config.yml, sdks/aperture-java/.circleci/continue-workflows.yml, sdks/aperture-java/dockerfiles/aperture-java-all/Dockerfile, sdks/aperture-java/dockerfiles/example/Dockerfile, sdks/aperture-java/javaagent/README.md, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Constants.java, sdks/aperture-java/version.gradle.kts
**Chore:**
- Updated build command to use `./gradlew` in CircleCI configuration files, Dockerfiles, and README.md
- Bumped version number from `1.3.0` to `1.4.0`
> 🎉 A gradle wrapper we now embrace, 🛠️<br>
> In CircleCI, Docker, and README's space. 📖<br>
> With version numbers on the rise, 🚀<br>
> Our code's journey reaches new highs! 🌟
=> Use gradlew instead of gradle in aperture-java CI checks

docs/content/get-started/installation/agent/agent.md, docs/content/get-started/installation/agent/kubernetes/namespace-scoped/namespace-scoped.md, docs/content/get-started/installation/agent/kubernetes/operator/daemonset.md, docs/content/get-started/installation/agent/kubernetes/operator/sidecar.md, docs/content/get-started/installation/controller/controller.md, docs/content/get-started/installation/controller/namespace-scoped/namespace-scoped.md, docs/content/get-started/installation/controller/operator/operator.md, manifests/charts/aperture-controller/Chart.lock, manifests/charts/aperture-controller/Chart.yaml, manifests/charts/aperture-controller/templates/operator-pre-delete-hook.yaml, manifests/charts/aperture-controller/templates/operator-rbac.yaml, manifests/charts/aperture-controller/templates/post-install-hook.yaml, manifests/charts/aperture-controller/values.yaml, playground/Tiltfile
- Updated default prometheus to use StatefulSet to fix the upgrade issue
- Update Etcd chart to v8.9.0
- Added post-install job to delete resource from previous release
- Updated docs
- Improved installation instructions for Aperture Agent and Controller in Kubernetes
- Added warning messages to discourage upgrading between installation modes
**Bug fix:**
- Fixed Prometheus upgrade issue by using StatefulSet
- Updated Etcd chart to v8.9.0 and added post-install job
> 🎉 A smoother install, we've paved the way,
> For Agent and Controller, come what may.
> With warnings in place, and upgrades refined,
> Our users rejoice, peace of mind they find. 🚀
=> Improvemts and fixes in the upgrade process

pkg/config/defaults.go, pkg/config/defaults_test.go, pkg/config/duration.go, pkg/config/timestamp.go
Improve the defaults handling code.
- Support for default values on maps and slices in configuration
- Updated `ExampleBasic` struct fields for better testing
> 🎉 A new dawn for our config, we cheer! 🥳
> Maps and slices now have defaults, oh dear! 🗺️🔪
> ExampleBasic has grown, no fear! 💪
> Celebrate the changes, far and near! 🎊
=> support defaults on maps

.circleci/post-release.yaml
- Chore: Updated `gcp-gcr` orb version in CircleCI configuration for Python 3.11 compatibility.
> 🎉 A small change, yet so wise,
> For Python 3.11, we now optimize.
> With orbs updated, we celebrate,
> Our CircleCI config, up-to-date! 🚀
=> Update gcp-gcr CircleCI org for Python 3.11 compatibility

docs/content/get-started/installation/agent/kubernetes/namespace-scoped/namespace-scoped.md, docs/content/get-started/installation/agent/kubernetes/operator/daemonset.md, docs/content/get-started/installation/agent/kubernetes/operator/sidecar.md, docs/content/get-started/installation/controller/namespace-scoped/namespace-scoped.md, docs/content/get-started/installation/controller/operator/operator.md, manifests/charts/aperture-agent/templates/agent-cm.yaml
- Added `--version` flag to `aperturectl uninstall` commands for Aperture Agent and Aperture Controller installation documentation.
> 🎉 A flag was born today, so bright and clear, 🌟
> To help uninstall with version, bringing cheer! 😄
> Aperture's docs now shine with added grace, ✨
> For users to follow, in their software chase. 🏃‍♂️💨
=> Minor changes in installation docs

pkg/policies/controlplane/components/sma.go, pkg/policies/controlplane/components/sma_test.go
Make output as invalid when invalidCount >= window.
**Bug fix:**
- Improved handling of invalid readings in the Simple Moving Average (SMA) filter
- Updated test case to simulate invalid reading scenario
> 🎉 Oh, rejoice and celebrate! 🥳
> For we've fixed a bug, no time to wait. 🐛
> The SMA filter now stands tall, 💪
> Handling invalid readings, one and all. 📈
=> Fix SMA behaviour

pkg/metrics/schema.go, pkg/policies/autoscale/kubernetes/discovery/autoscale-control-points.go, pkg/policies/autoscale/kubernetes/discovery/provide.go
- Add `AgentGroupLabel` for better agent group identification in metrics
- Update `podCounter` metric, `newAutoScaleControlPoints`, and `newPodNotifier` functions to support `agentGroup` parameter
- Modify `provideAutoScaleControlPoints` function to include `AgentInfo` argument and create `PodNotifier` with `AgentGroup` value
> 🎉 A new label takes the stage, 🏷️
> Agent groups now engage. 🤖
> Metrics refined, code aligned, 📊
> Our autoscaling knowledge, we gauge! 🚀
=> Add agent group label to metrics

sdks/aperture-go/example/main.go, sdks/aperture-go/sdk/client.go
**Refactor:**
- Updated context handling in `StartFlow` method of `apertureClient` struct
- Removed duration parameter from `HTTPMiddleware` function call
- Adjusted related methods to use the new `StartFlow`
> 🎉 A refactor's here, a change so grand,
> Contexts handled with a skillful hand.
> Duration gone, but middleware thrives,
> Our code evolves, like bees in their hives. 🐝
=> Refactor context handling in `StartFlow`

sdks/aperture-go/sdk/client.go, sdks/aperture-go/sdk/const.go
**Refactor:**
- Removed default timeout value and unused constants in aperture-go SDK
- Timeout value now taken from `Options` struct
> 🎉 A timeout once set in stone, 🪨
> Now flexible, it has grown. 🌱
> Constants gone, no longer bound, 🗑️
> In `Options`, the value is found. 🔍
=> Remove default timeout in aperture-go

playground/Tiltfile
- Added Prometheus selector to PVC selectors for Kubernetes controller
> 🎉 A new dawn rises, with metrics in sight,
> Prometheus joins the fray, a powerful knight.
> Our Kubernetes controller now gains more might,
> With PVC selectors updated, we take flight! 🚀
=> Playground delete prometheus pvc on tilt down

.circleci/continue-workflows.yml
**Chore:**
- Updated CI pipeline to install Python pre-requisites based on the `tools` parameter
- Modified string values in `cmd/aperturectl/main.go` for testing purposes
> 🎉 A pipeline tweak, a test name change,
> 🚀 Our code's journey, an ever-wider range.
> 🛠️ With tools in place, and tests refined,
> 🌟 This PR shines, as progress we find.
=> Added required pre-requisites to install Python in CI

api/aperture/policy/language/v1/flowcontrol.proto, api/aperture/policy/language/v1/label_matcher.proto, api/buf.lock, api/gen/proto/go/aperture/policy/language/v1/flowcontrol.pb.go, api/gen/proto/go/aperture/policy/language/v1/label_matcher.pb.go, blueprints/gen/jsonschema/_definitions.json, docs/content/assets/openapiv2/aperture-agent.swagger.yaml, docs/content/assets/openapiv2/aperture-controller.swagger.yaml, docs/content/assets/openapiv2/aperture.swagger.yaml, docs/content/reference/policies/spec.md, docs/gen/policy/policy.yaml, pkg/otelcollector/consts/consts.go, pkg/policies/flowcontrol/service/checkhttp/checkhttp.go, playground/resources/demo-app/app/app.go, playground/scenarios/demo-app-fan-in/dashboards/main.jsonnet, playground/scenarios/demo-app-fan-in/load_generator/test.js, playground/scenarios/demo-app-fan-in/metadata.json, playground/scenarios/demo-app-fan-in/policies/weighted-service-protection-cr.yaml, playground/scenarios/demo-app-fan-in/policies/weighted-service-protection.yaml
Update source, destination services label
- Rename source_service, destination_service -> source_fqdns, destination_fqdns
- Add new scenario
k6 -> svc1 -> svc3, k6 -> svc2 -> svc3
- add new policy to give higher priority to guest flow from svc1 than guest flow from svc2
- Fix label_matcher
Make label_exists not required
- Update example
- Added a new scenario to prioritize guest flow from svc1 over svc2
- Updated label matching and removed `label_exists` requirement
**Refactor:**
- Renamed `source_service` and `destination_service` to `source_fqdns` and `destination_fqdns`
**Test:**
- Updated k6 script with a new scenario and label matcher changes
> 🎉 A new scenario takes the stage,
> Prioritizing flows, an update we gauge.
> Labels match with ease, no need to exist,
> …
=> Weighted scenario

pkg/policies/controlplane/components/flowcontrol/loadscheduler/adaptive-load-scheduler.go
```
Bug fix:
- Added nil checks for omitempty fields in AdaptiveLoadScheduler and set default values
- Ensured safe access to Gradient field properties
```
> 🎉 In this PR we find delight,
> As nil checks make our code right.
> With safety ensured, we forge ahead,
> On a path where no errors are bred. 🚀
=> Added nil check for omitempty fields in AdaptiveLoadScheduler

blueprints/policies/feature-rollout/base/dashboard.libsonnet
```
Bug fix:
- Updated Prometheus metric name in dashboard.libsonnet
```
> 🎉 A metric's name has changed, we've fixed it with no strain! 📊
> In dashboard.libsonnet, the update was made,
> Now our monitoring will not fade. 🌟
=> Corrected metrics name in feature_rollout scenario dashboard

api/aperture/policy/language/v1/flowcontrol.proto, api/gen/proto/go/aperture/policy/language/v1/flowcontrol.pb.go, blueprints/gen/jsonschema/_definitions.json, docs/content/assets/openapiv2/aperture-controller.swagger.yaml, docs/content/assets/openapiv2/aperture.swagger.yaml, docs/gen/policy/policy.yaml, pkg/policies/controlplane/components/flowcontrol/loadscheduler/adaptive-load-scheduler.go
Make the fields required instead of relying on nil pointer checks and setting default behavior manually.
- Make `gradient`, `alerter`, `Parameters`, and `Alerter` fields required in `AdaptiveLoadScheduler`
- Set default value for `AlertName` if not provided
> 🎉 With fields required, we stand tall,
> No more nil checks, we've fixed them all.
> A default alert name, now in place,
> Our scheduler's stronger, keeping pace. 🚀
=> make parameters and alerter required fields in AdaptiveLoadScheduler

.circleci/continue-workflows.yml, scripts/install_asdf_tools.sh, scripts/install_go_tools.sh, scripts/invalidate_asdf_ci_cache.sh
**Chore:**
- Update CircleCI cache paths and keys for better organization
- Add `asdf reshim helm` command to `install_helm_plugins` function in `install_asdf_tools.sh`
- Modify `install_go_tools.sh` to download jsonnet dependencies using `aperturectl`
> 🎉 Cache paths renamed, daily now they're called,
> Helm plugins reshimmed, with asdf enthralled.
> Jsonnet deps fetched, aperturectl stands tall,
> A PR full of changes, we celebrate them all! 🚀
=> circleci: move cache paths around

cmd/aperture-agent/agent/otel-config.go, pkg/policies/controlplane/policy.go, pkg/policies/controlplane/resources/classifier/classifier.go, pkg/policies/controlplane/resources/telemetry-collectors/telemetry-collectors.go, pkg/policies/paths/paths.go
Prevent clash in telemetry collector etcd paths across policies
**Bug fix:**
- Prevent clashes in telemetry collector etcd paths across policies by updating the path and key functions
- Update `NewClassifierOptions` function call to use an integer index instead of int64
> 🎉 No more clashes, our paths are clear,
> With updated keys, we have nothing to fear.
> A small change in type, but a big win,
> Our code is now stronger, let the celebration begin! 🥳
=> telemetry resource: update etcd path to use policy name

cmd/aperture-agent/agent/otel-config.go, pkg/distcache/provider.go, pkg/etcd/client/client.go, pkg/etcd/election/election.go, pkg/net/grpc/server.go, pkg/net/http/server.go, pkg/otelcollector/otelcollector.go, pkg/utils/helpers.go
Shutdown process when OTel configuration has issues.
**Bug fix:**
- Improved shutdown handling in various parts of the codebase
- Updated `Shutdown` function to use `log.Panic` instead of `log.Error`
**Refactor:**
- Replaced direct calls to `Shutdowner.Shutdown` with utility function `utils.Shutdown`
> 🎉 A graceful exit we now embrace,
> With Shutdown's touch, a safer space.
> Refactored code, a cleaner slate,
> In this PR, we celebrate! 🥳
=> shutdown process when otel config is incorrect

pkg/utils/helpers.go
```
Bug fix:
- Changed log level from `Panic` to `Error` in the `Shutdown` function of pkg/utils/helpers.go
```
> 🎉 Hooray for this change, so small and neat,
> No more panic, just errors we'll meet.
> A smoother shutdown, that's what we cheer,
> With every release, progress is near! 🚀
=> do not panic on shutdown errors

sdks/aperture-java/dockerfiles/aperture-java-all/Dockerfile, sdks/aperture-java/dockerfiles/example/Dockerfile
```
Chore:
- Added `clean` command to Gradle build process in sdks/aperture-java/dockerfiles/aperture-java-all/Dockerfile and sdks/aperture-java/dockerfiles/example/Dockerfile
```
> 🎉 A clean slate, a fresh start,
> With Gradle builds, we play our part.
> Cache errors, now at bay,
> Our Dockerfiles lead the way. 🚀
=> Add gradle clean to dockerfiles to prevent cache errors

blueprints/dashboards/signals/dashboard.libsonnet, docs/content/reference/policies/assets/monitoring/signals-dashboard.json
- Added `sub_circuit_id` variable to Prometheus queries in signals dashboard
- Introduced new template for querying available sub-circuit IDs
> 🎉 A new feature takes the stage,
> With `sub_circuit_id`, we engage.
> Queries refined, templates combined,
> In our signals dashboard, they're now aligned. 🚀
=> Add `sub_circuit_id` variable to singals dashboard

pkg/otelcollector/infra-meter/infra-meter.go
Fixes #1925
```
Bug fix:
- Ensure infraMeter.Pipeline is not nil and set to an empty InfraMeter_MetricsPipeline if needed
```
> 🎉 No more nil, we've had our fill,
> A safer check, in code we'll inject,
> With this PR, we pave the way,
> For cleaner code, hip hip hooray! 🚀
=> Stop crashing agent on implicit infra meter pipeline

blueprints/policies/auto-scaling/base/config-defaults.libsonnet, blueprints/policies/auto-scaling/pod-auto-scaler/gen/definitions.json, blueprints/policies/auto-scaling/pod-auto-scaler/gen/values-required.yaml, blueprints/policies/auto-scaling/pod-auto-scaler/gen/values.yaml, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency/gen/definitions.json, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency/gen/values-required.yaml, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency/gen/values.yaml, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql/gen/definitions.json, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql/gen/values-required.yaml, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql/gen/values.yaml, docs/content/applying-policies/auto-scale/load-based-auto-scaling/assets/policy.yaml, docs/content/reference/policies/bundled-blueprints/policies/auto-scaling/pod-auto-scaler.md, docs/content/reference/policies/bundled-blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency.md, docs/content/reference/policies/bundled-blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql.md
- Added default alert parameters to auto-scaler blueprint
- Updated `AutoScalerScalingParameters` object with `scale_in_alerter` and `scale_out_alerter`
- Fixed default alert parameters in auto-scaler blueprint documentation
> 🎉 Scaling up and down, we've got it right,
> With new alert parameters, our code takes flight.
> Auto-scaler blueprint, now more complete,
> A better experience, we're proud to meet! 🚀
=> Fixed default alert parameters in auto-scaler blueprint

docs/content/get-started/integrations/flow-control/gateway/nginx.md, gateways/lua/aperture-kong-plugin-0.1.0-1.rockspec, gateways/lua/aperture-nginx-plugin-0.1.0-1.rockspec, gateways/lua/aperture-plugin/access.lua, gateways/lua/aperture-plugin/headers.lua, gateways/lua/kong/handler.lua, playground/resources/nginx/nginx_config.conf
- Added support for modifying response headers in Nginx and Kong plugins
- Introduced `aperture-plugin.headers` module to handle header modifications
> 🎉 A new feature takes the stage,
> Modifying headers, all the rage.
> Nginx and Kong now unite,
> To make responses just right. 🚀
=> Add headers from denied_response in actual response headers

pkg/k8s/provide.go, pkg/policies/autoscale/kubernetes/actuators/podscaler/pod-scaler.go, pkg/policies/autoscale/kubernetes/discovery/provide.go
```
New Feature:
- Support running outside Kubernetes cluster
- Return nil client if not in a Kubernetes environment
- Disable Kubernetes AutoScaler when not running inside a cluster
- Skip AutoScaler creation and control point discovery if the Kubernetes client is unavailable
```
> 🎉 Outside the cluster, we now can run,
> With AutoScaler disabled, it's still fun! 🚀
> Nil clients returned, no more dismay,
> Our code adapts, come what may! 😄
=> Disable building Kubernetes Discovery when outside the cluster

cmd/aperturectl/cmd/agents.go, cmd/aperturectl/cmd/apply/dynamic-config.go, cmd/aperturectl/cmd/apply/policy.go, cmd/aperturectl/cmd/apply/root.go, cmd/aperturectl/cmd/autoscale/control-points.go, cmd/aperturectl/cmd/blueprints/generate.go, cmd/aperturectl/cmd/delete/policy.go, cmd/aperturectl/cmd/delete/root.go, cmd/aperturectl/cmd/discovery/entities.go, cmd/aperturectl/cmd/flowcontrol/control-points.go, cmd/aperturectl/cmd/utils/controller.go, docs/content/reference/aperturectl/agents/agents.md, docs/content/reference/aperturectl/apply/apply.md, docs/content/reference/aperturectl/apply/dynamic-config/dynamic-config.md, docs/content/reference/aperturectl/apply/policy/policy.md, docs/content/reference/aperturectl/auto-scale/auto-scale.md, docs/content/reference/aperturectl/auto-scale/control-points/control-points.md, docs/content/reference/aperturectl/blueprints/generate/generate.md, docs/content/reference/aperturectl/delete/delete.md, docs/content/reference/aperturectl/delete/policy/policy.md, docs/content/reference/aperturectl/discovery/discovery.md, docs/content/reference/aperturectl/discovery/entities/entities.md, docs/content/reference/aperturectl/flow-control/control-points/control-points.md, docs/content/reference/aperturectl/flow-control/flow-control.md, docs/content/reference/aperturectl/flow-control/preview/preview.md
There was an issue where even if we provide `--controller` flag, it was trying to connect to kubernetes.
Also, added support for insecure controller communication.
Also, --kube flag is now default for all subcommands and can be omitted.
- Added support for insecure controller communication and skipping TLS certificate verification
**Bug fix:**
- Fixed issue where `--controller` flag was not being used to connect to the controller
- Made `--kube` flag default for all subcommands, allowing it to be omitted
- Updated documentation to reflect changes in code and new features
> 🎉 A flag once lost, now found and secure,
> Insecure connections, we can endure.
> With kube as default, our commands are free,
> Documentation updated, a joyous decree! 🥳
=> Fixed aperturectl apply when controller address is provided

cmd/aperturectl/cmd/delete/policy.go, cmd/aperturectl/cmd/delete/root.go
```
Bug fix:
- Fixed a nil pointer error in `aperturectl delete` command by updating the way kubeRestConfig is obtained
- Added a check for "Policy not found" error and logged it as an info message
- Removed unnecessary import and modified variable declarations for better maintainability
```
> 🎉 Hooray for the fix, no more crash we'll see,
> With pointers tamed, our code roams free.
> A policy check, logs now clear,
> Embrace the change, release notes cheer! 🥳
=> Fixed nil pointer error on aperturectl delete

.github/styles/Vocab/FluxNinja/accept.txt, docs/content/faq.md
Readded the FAQ skeleton (https://github.com/fluxninja/aperture/issues/1951)
and expanded some answers.
~~Some things I'm unsure about, added comments/TODOs.~~
[:framed_picture: Preview](https://github.com/fluxninja/aperture/blob/faq-reborn/docs/content/faq.md)
Resolves #1951 
- Expanded FAQ section in `docs/content/faq.md` with new questions and answers related to Aperture's usage, rate limiting, request rejection, flow label uniqueness, delays in server availability, and Kubernetes cluster requirements.
**Style:**
- Updated `.github/styles/Vocab/FluxNinja/accept.txt` with additional vocabulary.
> 🎉 A wealth of knowledge we now share,
> In our FAQ, answers everywhere! 📚
> Rate limits, requests, and more,
> FluxNinja's wisdom, we adore! 💡🥳
=> Re-add FAQ with expanded answers

sdks/aperture-java/lib/core/build.gradle.kts, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Flow.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/TrafficFlow.java
- Added `rejectReason()` method to `Flow` and `TrafficFlow` classes for retrieving reject reason value
**Chore:**
- Added dependency on `httpcore` library version 4.4.16
> 🎉 A new feature we bring, with grace,
> To help developers in their chase.
> Reject reasons now in sight,
> And dependencies set just right. 🚀
=> Add simple method for retrieving reject values to flow classes

docs/content/get-started/integrations/flow-control/sdk/python/manual.md, sdks/aperture-py/aperture_sdk/client.py, sdks/aperture-py/aperture_sdk/const.py, sdks/aperture-py/aperture_sdk/flow.py, sdks/aperture-py/pyproject.toml
- Added `FlowResult` enum with `Accepted`, `Rejected`, and `Unreachable` values
- Updated `result()` method to return `FlowResult` value based on decision type
- Modified `success()` method to check for `Unreachable` result
**Bug fix:**
- Updated default RPC timeout to 200 milliseconds
- Added `fail_open` parameter to `decorate` function
- Handled case where `timeout` is 0 in `start_flow` function
- Updated Python SDK manual to reflect changes in flow control logic
> 🎉 A new dawn for flow control, we see,
> With `FlowResult` enum, as easy as one, two, three.
> Unreachable or not, we now can tell,
> And celebrate this PR, where improvements dwell. 🚀
=> Aperture py changes

playground/resources/java-demo-app/Dockerfile, playground/resources/java-demo-app/config.yaml, playground/scenarios/java-service-protection/metadata.json, playground/tanka/charts/java-demo-app/templates/deployment.yaml, playground/tanka/charts/java-demo-app/templates/service.yaml, playground/tanka/charts/java-demo-app/values.yaml
Closes: GH-1950
```
New Feature:
- Added JMX Prometheus Java agent for monitoring
- Included `config.yaml` file for JMX exporter configuration
```
> 🎉 A new dawn rises, metrics in sight,
> With JMX Prometheus, our app takes flight.
> Monitoring enabled, insights we'll gain,
> For better performance, and less growing pain. 🚀
=> Add prometheus-jmx javaagent to java demo app, expose port

docs/content/architecture/architecture.md
- [X ] Documentation is changed or added
- Added a new section heading for the "Aperture Controller" in architecture.md
> 🎉 A new section takes its place,
> In architecture.md, it finds its space.
> Aperture Controller, shining bright,
> Our docs now guide with clearer light. 📚✨
=> Fix Aperture Controller heading

sdks/aperture-java/examples/standalone-example/src/main/java/com/fluxninja/example/App.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/HttpUtils.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/RpcUtils.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Constants.java, sdks/aperture-java/lib/netty/src/main/java/com/fluxninja/aperture/netty/ApertureServerHandler.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ServletUtils.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ServletUtils.java, sdks/aperture-java/version.gradle.kts
- Updated method for retrieving rejection reason in libs and examples
**Chore:**
- Updated library version in `Constants.java` and `version.gradle.kts`
> 🎉 A new method we embrace,
> For rejection reasons, we now trace.
> With updated libs, our code takes flight,
> Enhancing our project, shining bright! ✨
=> Use new flow rejection reason retrieval in libs and examples

sdks/aperture-go/sdk/middlewares/grpc.go, sdks/aperture-go/sdk/middlewares/http.go, sdks/aperture-go/sdk/middlewares/utils.go
Added util methods for generating the CheckHTTPRequest as we also need it in the Traefik integration
**Refactor:**
- Extracted `PrepareCheckHTTPRequestForGRPC` and `PrepareCheckHTTPRequestForHTTP` functions for generating `CheckHTTPRequest` objects in gRPC and HTTP requests
- Added utility methods for creating `CheckHTTPRequest` in aperture-go, improving modularity and maintainability
> 🎉 A refactor so grand, we stand in awe,
> Modular code, a sight to adore.
> With gRPC and HTTP aligned,
> Maintainability, we shall find. 🚀
=> Added util methods for generating CheckHTTPRequest in aperture-go

docs/content/get-started/setting-up-application/manual-control-points.md, docs/content/integrations/flow-control/sdk/java/armeria.md, docs/content/integrations/flow-control/sdk/java/auto-instrumentation.md, docs/content/integrations/flow-control/sdk/java/netty.md
- Fixed broken links in Armeria and Netty integration documentation
- Updated front matter in auto-instrumentation documentation
> 📚 Docs are shining bright,
> 🛠️ Broken links now right,
> 🎉 Celebrate the change,
> 🌟 Our knowledge, rearrange!
=> docs: fix link

docs/content/integrations/flow-control/envoy/istio.md, manifests/charts/istioconfig/README.md, manifests/charts/istioconfig/values.yaml
```
New Feature:
- Added `workloadSelector` parameter to Istioconfig chart for applying EnvoyFilter to specific workloads
- Updated documentation with steps and examples for using `workloadSelector` in Istioconfig chart
```
> 🎉 With selectors now in place, we steer,
> To workloads that need us most near.
> A filter applied, with precision and grace,
> Our Istioconfig finds its rightful space. 🚀
=> Added steps for using workloadSelector in istioconfig chart

docs/content/applying-policies/quota-scheduler/external-rate-limiting.md
- Fixed a broken link in the quota-scheduler external rate limiting policy documentation
> 🎉 A broken link no more, we've mended the lore,
> In our docs now restored, users can explore! 📚
=> fix broken link

playground/resources/java-demo-app/build.gradle.kts, playground/resources/java-demo-app/src/main/resources/application.properties, playground/resources/wavepool-generator/apps-v1.Deployment-wavepool-graphql-generator.yaml, playground/scenarios/java-service-protection/metadata.json, playground/scenarios/java-service-protection/policies/service-protection-cr.yaml, playground/scenarios/java-service-protection/policies/service-protection.yaml, playground/tanka/apps/java-demo-app/mixins.libsonnet
Ref: GH-2009
- Added JMX metrics collection for Prometheus
- Enabled automatic timing of requests for the metrics endpoint
> 🎉 Oh, what a glorious day! 🌟
> Metrics now pave our way. 📊
> With JMX in hand, 🤲
> Our app's performance we'll understand. 💡
> Rejoice, for Prometheus is here to stay! 🚀
=> Add inframeter for collecting jmx metrics from prometheus

pkg/policies/controlplane/components/variable.go
Ref #2052 
```
- Improved performance in `pkg/policies/controlplane/components/variable.go` by adding an early return statement to avoid unnecessary computation.
```
> 🎉 A leap in code, swift and wise,
> 🚀 With early returns, performance flies!
> 🌟 Optimized, our code now gleams,
> 😄 For better software, we all dream!
=> Fixed issue of incorrect value of setpoint constant variable

pkg/policies/flowcontrol/actuators/load-scheduler/load-scheduler.go, pkg/policies/flowcontrol/actuators/quota-scheduler/quota-scheduler.go, pkg/policies/flowcontrol/actuators/rate-limiter/rate-limiter.go, pkg/policies/flowcontrol/actuators/regulator/regulator.go, pkg/policies/flowcontrol/actuators/workload-scheduler/scheduler.go, pkg/policies/flowcontrol/engine.go, pkg/policies/flowcontrol/iface/limiter.go, pkg/policies/mocks/mock_limiter.go, pkg/rate-limiter/global-token-bucket/global-token-bucket.go, pkg/rate-limiter/iface.go, pkg/rate-limiter/lazy-sync/lazy-sync.go, pkg/rate-limiter/test/rate-limiter_test.go, pkg/scheduler/global-token-bucket.go, pkg/scheduler/load-multiplier-token-bucket.go, pkg/scheduler/scheduler.go, pkg/scheduler/token-bucket.go, pkg/scheduler/wfq.go, pkg/scheduler/wfq_test.go, pkg/scheduler/windowed-counter.go
Now that we have global token buckets, we need to release locks before accessing the token bucket in order to unblock parallel requests.
**Refactor:**
- Updated locking mechanisms in various flow control actuators and schedulers to unblock parallel requests
- Added `context.Context` parameter to `Limiter`, `RateLimiter`, and `Scheduler` interfaces for better lock handling
**Test:**
- Modified `MockLimiter`, `MockRateLimiter`, and `MockScheduler` methods to include a `context.Context` parameter
> 🎉 Parallel requests now fly, 🚀
> Unblocked, soaring through the sky. 🌌
> Locks released with context's grace, 🔓
> Our code performs at a swifter pace! 💨
=> wfq: refactor locking

pkg/policies/controlplane/crwatcher/watcher.go, pkg/policies/controlplane/iface/policy.go, pkg/policies/controlplane/provider.go
- Introduced `PolicyMessage` type with custom JSON marshaling and unmarshaling
- Replaced `syncv1.PolicyWrapper` with `iface.PolicyMessage` for improved policy handling
> 🎉 A new dawn for policies, we cheer,
> With `PolicyMessage`, the path is clear.
> Farewell to `syncv1.PolicyWrapper`, old friend,
> Embrace the change, as new features ascend! 🚀
=> Use custom PolicyMessage for passing policies to be wrapped

cmd/aperturectl/cmd/utils/controller.go
```
Bug fix:
- Fixed a minor typo in the log message of cmd/aperturectl/cmd/utils/controller.go
```
> 🎉 A tiny typo fixed, our code now shines,
> With every letter in its place, it gracefully aligns.
> A small change indeed, but worth the cheer,
> For clarity and precision, we hold so dear. 🌟
=> Fixed typo in aperturectl log

docs/content/reference/configuration/agent.md, docs/gen/config/agent/config-swagger.yaml, go.mod, go.sum, operator/config/crd/bases/fluxninja.com_agents.yaml, pkg/dist-cache/config/config.go, pkg/dist-cache/provider.go, pkg/rate-limiter/global-token-bucket/global-token-bucket.go
Remove key lock in global token bucket as that is taken within olric
- Added `sync_replication` configuration option for global token bucket
**Refactor:**
- Removed unnecessary key lock in `takeN` function of `GlobalTokenBucket`
> 🎉 A new config option we bring,
> To make our token bucket sing! 🎶
> Sync replication, now in sight,
> And a refactor to make things right! ✨
=> global token bucket: remove key lock

pkg/dist-cache/provider.go, pkg/dist-cache/service-discovery.go
Closes: GH-2094
- Added timeout to DistCache client status check
- Introduced configurable service name for ServiceDiscovery
> 🎉 A timeout now in place, we race 🏁
> To keep our cache checks at a steady pace ⏱️
> With service names now free to roam 🌐
> Our discovery finds its way back home 🏠
=> Fix DistCache timeout error

pkg/dist-cache/provider.go, playground/scenarios/quota-scheduler/policies/quota-scheduler-cr.yaml, playground/scenarios/quota-scheduler/policies/quota-scheduler.yaml
```
Bug fix:
- Removed unnecessary call to `dc.client.Stats` in `ProvideDistCache` function
- Added deferred call to `utils.Shutdown` for proper Olric instance shutdown
```
> 🎉 A bug we found, a fix we made,
> In the cache provider, improvements laid.
> Stats call removed, shutdown ensured,
> Our code's performance and health secured. 🚀
=> Do not get stats in ProvideDistCache

pkg/policies/controlplane/policy-service.go, pkg/policies/controlplane/provider.go, pkg/policies/paths/paths.go
- Added support for policy metadata in API-created policies
- Modified `UpsertPolicy` and `DeletePolicy` functions in policy-service.go to handle policy metadata in etcd
- Updated provider.go to retrieve policy metadata from etcd if not present in the policy message
> 🎉 A new feature's here, so grand,
> Policy metadata now at hand! 📜
> Upsert, delete, and provide,
> With etcd by our side. 🌟
=> Support policies metadata for policies created by api

sdks/aperture-java/examples/armeria-example/src/main/java/com/fluxninja/example/ArmeriaClient.java, sdks/aperture-java/examples/armeria-example/src/main/java/com/fluxninja/example/ArmeriaServer.java, sdks/aperture-java/examples/spring-example/src/main/java/com/fluxninja/example/filter/ApertureFeatureFilter.java, sdks/aperture-java/examples/standalone-example/src/main/java/com/fluxninja/example/App.java, sdks/aperture-java/examples/tomcat-example/src/main/java/com/fluxninja/example/filter/ApertureFeatureFilter.java, sdks/aperture-java/javaagent/agent/src/main/java/com/fluxninja/aperture/instrumentation/Config.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPClient.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPService.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureRPCClient.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureRPCService.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/HttpUtils.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/RpcUtils.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDKBuilder.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Flow.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/FlowDecision.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/TrafficFlow.java, sdks/aperture-java/lib/netty/src/main/java/com/fluxninja/aperture/netty/ApertureServerHandler.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ApertureFilter.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ServletUtils.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ApertureFilter.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ServletUtils.java
ApertureSDKBuilder.setDuration -> ApertureSDKBuilder.setFlowTimeout
Flow.rejectReason -> Flow.getRejectionHttpStatusCode
**Refactor:**
- Renamed `ApertureSDKBuilder.setDuration` to `ApertureSDKBuilder.setFlowTimeout`
- Renamed `Flow.rejectReason` to `Flow.getRejectionHttpStatusCode`
- Changed enum value name from `FlowResult` to `FlowDecision`
> 🎉 A new chapter unfolds, with names refined and bold,
> The code now speaks clearer, its purpose well told. 🚀
> With enums and methods, in harmony they stand,
> A refactor to celebrate, for a future grand! 🌟
=> Java SDK: Rename methods to be more descriptive

sdks/aperture-java/examples/standalone-example/src/main/java/com/fluxninja/example/App.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Flow.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/TrafficFlow.java
- Added `shouldRun()` method to `Flow` and `TrafficFlow` classes
- Introduced `failOpen` instance variable and `withNoFailOpen()` method for disabling fail-open behavior
> 🎉 A new feature we bring, with logic so fine,
> To control the flow, in this code of mine.
> Fail-open behavior, now we can tame,
> With `shouldRun()` and `withNoFailOpen()`, our code shall never be the same! 🚀
=> Java SDK: Add shouldRun() method to Flow classes

sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDKBuilder.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Constants.java
- Added default agent host and port to ApertureSDKBuilder
- Introduced logging statements for unset agent host and port
> 🎉 A builder's tale, now more robust,
> With defaults in place, we can trust. 🛠️
> Logging warns when values are missed,
> Ensuring connections will persist. 🔌✨
=> Java SDK: Creation of Aperture SDK without specifying Agent host/port

blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency/gen/definitions.json, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency/gen/values-required.yaml, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency/gen/values.yaml, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql/gen/definitions.json, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql/gen/values-required.yaml, blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql/gen/values.yaml, blueprints/policies/service-protection/average-latency/gen/definitions.json, blueprints/policies/service-protection/average-latency/gen/values-required.yaml, blueprints/policies/service-protection/average-latency/gen/values.yaml, blueprints/policies/service-protection/base/config-defaults.libsonnet, blueprints/policies/service-protection/base/policy.libsonnet, blueprints/policies/service-protection/promql/gen/definitions.json, blueprints/policies/service-protection/promql/gen/values-required.yaml, blueprints/policies/service-protection/promql/gen/values.yaml, docs/content/reference/policies/bundled-blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency.md, docs/content/reference/policies/bundled-blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql.md, docs/content/reference/policies/bundled-blueprints/policies/service-protection/average-latency.md, docs/content/reference/policies/bundled-blueprints/policies/service-protection/promql.md
**Refactor:**
- Changed the source of `overload_confirmations` in service protection policy
- Removed default values for some fields in XML files
- Updated default values in blueprint documentation
> 🎉 A change so small, yet profound,
> Refactoring code, making it sound.
> Docs updated too, with care,
> Celebrate this PR, a breath of fresh air! 🌬️
=> Fix confirmation generation in service protection blueprint

sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDKBuilder.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDKException.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Flow.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/FlowDecision.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/FlowStatus.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/TrafficFlow.java
- Added methods to `ApertureSDKBuilder` for setting hostname, port number, and root certificate file
- Introduced a method to build an `ApertureSDK` object using the configured parameters
- Added missing Javadoc comments to various classes and methods in the Aperture Java SDK
> 🎉 A new dawn for Aperture SDK,
> With settings flexible as can be! 🌟
> Hostname, port, and cert we set,
> And Javadocs make it complete. 📚
> Rejoice, developers, far and wide,
> For now, with ease, you shall glide! 🚀
=> Java SDK: Add missing javadoc comments

docs/content/get-started/get-started.md, docs/content/integrations/integrations.md, docs/content/use-cases/auto-scale/auto-scale.md, docs/content/use-cases/use-cases.md
- Shift Integration to 4th position bringing up Get-Started and Use-Cases
- Rename Auto Scale to Auto Scaling within Use-Cases section
- Moved Integrations section to the 4th position in side menu
- Renamed Auto Scale to Auto Scaling in Use-Cases section
> 🎉 A shift in docs, a change so small,
> Yet clarity blooms, for one and all.
> Integrations rise, Auto Scaling's new name,
> Our docs now refined, user ease is our aim. 🌟
=> Refactor and rename in documentation side menu

sdks/aperture-java/examples/armeria-example/build.gradle.kts, sdks/aperture-java/examples/netty-example/build.gradle.kts, sdks/aperture-java/examples/spring-example/build.gradle.kts, sdks/aperture-java/examples/standalone-example/build.gradle.kts, sdks/aperture-java/examples/standalone-traffic-flow-example/build.gradle.kts, sdks/aperture-java/examples/tomcat-example/build.gradle.kts, sdks/aperture-java/javaagent/agent/build.gradle.kts, sdks/aperture-java/lib/core/build.gradle.kts
**Chore:**
- Updated logging dependencies in multiple example projects and agent project
- Added `org.slf4j:slf4j-simple:1.7.0` as a runtime dependency
- Changed logging dependency in core project
- Replaced `slf4j-simple` with `slf4j-api`
> 🎉 A logging update, oh so fine! 🌟
> In our code, it now does shine. ✨
> With SLF4J, we stand tall, 🌳
> Logging messages for one and all! 📜
=> Fix Java SDK logging imports

sdks/aperture-java/examples/spring-example/src/main/java/com/fluxninja/example/filter/ApertureFeatureFilter.java, sdks/aperture-java/examples/standalone-example/src/main/java/com/fluxninja/example/App.java, sdks/aperture-java/examples/standalone-traffic-flow-example/src/main/java/com/fluxninja/example/App.java, sdks/aperture-java/examples/tomcat-example/src/main/java/com/fluxninja/example/filter/ApertureFeatureFilter.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPClient.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPService.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureRPCClient.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureRPCService.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/HttpUtils.java, sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/RpcUtils.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDKBuilder.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDKException.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Constants.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Flow.java, sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/TrafficFlow.java, sdks/aperture-java/lib/netty/src/main/java/com/fluxninja/aperture/netty/ApertureServerHandler.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ApertureFilter.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ServletUtils.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ApertureFilter.java, sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ServletUtils.java, sdks/aperture-java/version.gradle.kts
**Refactor:**
- Made `flow.end()` argumentless and exception-free
- Updated error handling and flow control structures
- Added logger to some classes
**Chore:**
- Updated dependency version in `version.gradle.kts`
> 🎉 With graceful ease, the code now flows,
> Exception-free, as the river goes.
> Error handling refined, a logger aligned,
> A new chapter begins, with these changes combined. 🚀
=> Make flow.end() argumentless and exception-free

playground/Tiltfile
Add latest version for agent/controller on Tilt
```
sachinmaurya@sachin:~/fluxninja/aperture (add-agent-version)$ curl localhost:8080/v1/info/version
{"version":"v2.5.0-rc.1", "service":"aperture-agent", "build_host":"buildkitsandbox", "build_os":"linux/amd64", "build_time":"2023-06-13T12:23:52+00:00", "git_branch":"unknown", "git_commit_hash":"unknown"}
```
cc @DariaKunoichi 
```
New Feature:
- Automatically fetch and use the latest version of agent/controller from git tags
- Add support for enabling the `-race` flag during build when `race_arg` is True
```
> 🎉 A new dawn rises, with versions fetched,
> The latest and greatest, our code now etched.
> With race flags enabled, we stand secure,
> This PR brings changes, both bright and pure. 🌟
=> add agent/controller version on tilt

cmd/aperture-agent/agent/otel-config.go, cmd/aperture-agent/config/types.go, cmd/aperture-controller/config/types.go, cmd/aperture-controller/controller/otel-component.go, cmd/aperture-controller/controller/otel-config.go, docs/content/reference/configuration/agent.md, docs/content/reference/configuration/controller.md, docs/gen/config/agent/config-swagger.yaml, docs/gen/config/controller/config-swagger.yaml, operator/config/crd/bases/fluxninja.com_agents.yaml, operator/config/crd/bases/fluxninja.com_controllers.yaml, operator/controllers/agent/config_test.tpl, operator/controllers/agent/configmaps_test.go, operator/controllers/controller/config_test.tpl, operator/controllers/controller/configmaps_test.go, pkg/otelcollector/config/builtin_config.go, pkg/otelcollector/consts/consts.go
To decrease load on Prometheus in large scale this makes pushing high cardinality platform metrics optional.
- Added optional high cardinality metrics filter processor to OpenTelemetry pipeline for Aperture agent and controller
- Introduced configuration options to disable publishing high cardinality Aperture platform metrics to Prometheus
- Updated documentation with new configuration options for disabling high cardinality metrics in agent and controller
> 🎉 High cardinality, no more a foe,
> With filters in place, our metrics will flow.
> Prometheus breathes easy, the load is light,
> Scaling up smoothly, we conquer the night! 🚀
=> Filter out high cardinality platform metrics

scripts/install_go_tools.sh
Made installation of go tools be done in the background as the background implementation seems flaky in our CI.
=> Don't install go tools in a background loop

blueprints/dashboards/flow-control/adaptive-load-scheduler/dashboard.libsonnet, playground/scripts/deps_install.sh
We had support for adding `overload_confirmations` in the `Service Protection` blueprints but we were not plotting them in the Grafana dashboard and were loosing some visibility.
```
New Feature:
- Added support for plotting overload confirmation signals in Grafana dashboard
Bug fix:
- Improved helm dependency update command to check for 'wrong version' dependencies
Chore:
- Removed line skipping tool installation in CircleCI job
```
> 🎉 A new feature takes the stage,
> Overload signals now engage.
> Helm's watchful eye grows keener,
> CircleCI's job a bit cleaner. 🚀
=> Added dashboard panels for overload confirmation signals

pkg/otelcollector/consts/consts.go, pkg/otelcollector/metricsprocessor/internal/check_response_labels.go
- Added support for QuotaScheduler processing in the OpenTelemetry Collector
- Introduced new constants related to quota schedulers and their dropping counterparts
> 🎉 A scheduler's tale, now unfolds,
> With quotas managed, and stories told.
> New labels added, updates embraced,
> In OpenTelemetry, performance traced. 🚀
=> Add QuotaScheduler processing to CheckResponse label adding

manifests/charts/aperture-controller/Chart.lock, manifests/charts/aperture-controller/Chart.yaml, manifests/charts/aperture-controller/values.yaml
Reverting the prometheus upgrade as it is just a Helm chart version change and underneath, the Prometheus version is same `v2.33.5`.
This update is breaking the upgrade procedure for Aperture Controller so we can handle this later when the actual prometheus is also updated
=> Revert "Update helm dependencies in aperture-controller chart (#2163)"

.circleci/config.yml
Fix path filtering in CI, so Aperture is build/tested also when extensions are changed.
**Chore:**
- Update CI path filtering to include `extensions` directory
> 🎉 Extensions now in sight,
> CI builds them day and night.
> With every change, we test,
> Ensuring Aperture's at its best! 🚀
=> Fix path filters for aperture build

sdks/aperture-js/package-lock.json, sdks/aperture-js/package.json
While testing, I accidently unpublished v1.0.0 and now it is not allowing me to re-publish it so have to release a new version.
=> Patched the aperture-js SDK version

go.mod
We are facing issue while importing api module on cloud as v2.0.0 is superseding the main version
=> Use dummy commit version for api module

manifests/charts/aperture-agent/templates/operator-mutatingwebhook.yaml, manifests/charts/aperture-agent/values.yaml, manifests/charts/aperture-controller/templates/operator-mutatingwebhook.yaml, manifests/charts/aperture-controller/templates/post-install-hook.yaml, manifests/charts/aperture-controller/values.yaml
There are three small fixes in this PR
1) The default value of `MutatingWebhookConfiguration.webhooks.rules.scope` is `'*'`. However, it watches the namespaced resources only. Therefore, the result of `kubectl diff` detects a skew with the result of `helm template`, with the attempt to restore the default value.
2) Empty `pullSecrets` lists are ignored by `kubectl diff`. On the other hand, Helm does not provide a mechanism to remove default values from a dependency chart - they can only be replaced by other values.
3) The `ttlSecondsAfterFinished` deletes the post-install hook Job after 10 seconds. However, the Job is not annotated with `hook-delete-policy`. Therefore Argo CD is willing to restore the job.
The changes were tested by deploying a chart with locally modified dependencies
``` …
```
=> Making Controller and Agent charts GitOps-friendlier
