fluxninja/aperture

- .circleci/continue-workflows.yml
- manifests/k8s/tanka/jsonnetfile.json
- manifests/k8s/tanka/jsonnetfile.lock.json
- manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/181)
> Update code for aperture-mixin repo rename

- pkg/metrics/schema.go
- pkg/otelcollector/metricsprocessor/processor.go
- pkg/otelcollector/metricsprocessor/processor_test.go
- pkg/policies/dataplane/engine.go
- pkg/policies/dataplane/engine_test.go
- pkg/policies/dataplane/fluxmeter/flux-meter.go
- pkg/policies/dataplane/iface/engine.go
- pkg/policies/dataplane/iface/flux-meter.go
- pkg/policies/mocks/mock_engine.go
- pkg/policies/mocks/mock_flux_meter.go
Closes: GH-5422
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/162)
> Status code labels in FluxMeter

- manifests/k8s/tanka/jsonnetfile.json
- manifests/k8s/tanka/jsonnetfile.lock.json
- manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
- update tilt deployment to use latest aperture-blueprints
- Fix url to aperture prometheus
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/191)
> Some fixes to aperture grafana deployment

- manifests/k8s/Tiltfile
- manifests/k8s/tanka/environments/tilt/apps/aperture-grafana/dashboards/json-example.json
- manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
- operator/controllers/configmaps_test.go
- operator/controllers/controller_config_with_fluxninja_plugin_test.tpl
- operator/controllers/controller_config_without_fluxninja_plugin_test.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/192)
> Replace all instances of agent-prometheus with aperture-prometheus

- docs/content/concepts/flow.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/201)
> Flow is not flow control

- .pre-commit-config.yaml
- manifests/k8s/tanka/jsonnetfile.lock.json
- manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/216)
> precommit fix

- scripts/manage_tools.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/234)
> Fix tools install

- .circleci/continue-workflows.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/238)
> Fixed DockerHub latest tag issue

- .github/workflows/combine-prs.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/244)
> Fix combine PRs script

- docs/content/concepts/policies/policy-blueprints.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/248)
> Improve blueprint docs

- manifests/k8s/tanka/lib/apps/k6-operator/k6/crd/bases/k6.io_k6s.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/239)
> Updated K6 CRD

- docs/content/developers/cla.md
- manifests/charts/aperture-operator/templates/_helpers.tpl
- manifests/charts/aperture-operator/values.yaml
- manifests/k8s/README.md
- manifests/k8s/Tiltfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/251)
> Fix CLA rendering and improve aperture-operator handling

- manifests/charts/agent/Chart.yaml
- manifests/charts/aperture-operator/Chart.yaml
Add appVersion in Helm chart and fix version typo
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/253)
> add app and helm chart version

- docs/content/cloud/_category_.yml
- docs/content/cloud/plugin.md
Ref: GH-[5886](https://github.com/fluxninja/cloud/issues/5886)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/252)
> Add FluxNinja Cloud section to docs

- manifests/charts/aperture-operator/templates/_helpers.tpl
- manifests/charts/aperture-operator/templates/agent.yaml
- manifests/charts/aperture-operator/templates/controller.yaml
- manifests/charts/aperture-operator/templates/pre-delete-hook.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/258)
> Added null checks for values in chart

- manifests/k8s/README.md
- manifests/k8s/kind-config.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/259)
> Add Kind cluster configuration file

- tools/demo_app/README.md
- tools/demo_app/app/app.go
- tools/demo_app/cmd/demo_app/main.go
- Set demoapp latency default to 50ms
- Make demoapp latency configurable via env vars
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/273)
> Make demoapp latency configurable

- manifests/k8s/tanka/jsonnetfile.lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/301)
> update blueprint jsonnet

- .circleci/continue-workflows.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/303)
> Updated CircleCi to release docker hub images from main only

- .circleci/config.yml
- .gitignore
- manifests/k8s/tilt/portforward.sh
- nfpm.yaml
- packaging/aperture-agent.yaml
closes: GH-254
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/295)
> Add basic agent packaging flow

- libsonnet/1.0/_gen/v1/languagev1ratelimiter.libsonnet
- libsonnet/scripts/jsonnet-lib-gen.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/309)
> Fix libsonnet python scripts

- .tool-versions
- manifests/k8s/tanka/jsonnetfile.lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/313)
> add tilt to tools

- README.md
- playground/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/315)
> Update Playground docs and its link in README

- manifests/charts/istioconfig/templates/envoy_filter.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/326)
> Fixes for envoy filters

- .github/CODEOWNERS
- nfpm.yaml
- packaging/aperture-agent.service
- packaging/aperture-agent.yaml
- packaging/post-install.sh
closes: GH-311
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/328)
> Add systemd service to package

- manifests/charts/istioconfig/templates/envoy_filter.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/332)
> Bring back v3 OTLP extension

- .pre-commit-config.yaml
- Makefile
- manifests/charts/Makefile
- scripts/precommit/helmlint.sh
using helm lint in pre-commit 
PS: The earlier [PR](https://github.com/fluxninja/aperture/pull/305) got close as I was trying to delete some older commit and mistakenly deleted all commits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/306)
> add helm lint in pre-check

- .pre-commit-config.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/335)
> add pre-commit check for circleci files

- .pre-commit-config.yaml
- README.md
- operator/README.md
- pkg/otelcollector/loggingexporter/README.md
- pkg/otelcollector/rollupprocessor/README.md
- pkg/policies/dataplane/resources/classifier/extractors/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/337)
> Fixed pre-commit

- docs/Makefile
- docs/content/concepts/flow-control/actuators/rate-limiter.md
- docs/content/concepts/flow-control/actuators/scheduler.md
- docs/content/concepts/flow-control/label/classifier.md
- docs/content/concepts/flow-control/label/label.md
- docs/content/concepts/flow-control/selector.md
- docs/gen/config/aperture-agent/swagger.md
- docs/gen/config/aperture-controller/swagger.md
- docs/gen/policies/policy.md
Resolves: https://github.com/fluxninja/cloud/issues/5898
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/338)
> Document Flow Classifier concept

- .pre-commit-config.yaml
- scripts/precommit/install_tools.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/342)
> pre-commit: install tools

- api/buf.lock
- docs/content/concepts/flow-control/fluxmeter.md
- docs/content/concepts/flow-control/selector.md
- docs/content/setup/_category_.yml
- docs/content/setup/installation/agent/agent.md
- docs/content/setup/istio.md
- docs/content/setup/playground.md
Added playground docs
Updated numbering for some pages 
Changed Setup -> Get Started
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/347)
> Playground docs

- api/buf.gen.yaml
- api/gen/proto/go/aperture/common/config/v1/config_properties_wrapper.pb.json.go
- api/gen/proto/go/aperture/common/entitycache/v1/entitycache.pb.json.go
- api/gen/proto/go/aperture/common/info/v1/info.pb.json.go
- api/gen/proto/go/aperture/common/labelmatcher/v1/labelmatcher.pb.json.go
- api/gen/proto/go/aperture/common/peers/v1/peers.pb.json.go
- api/gen/proto/go/aperture/common/selector/v1/selector.pb.json.go
- api/gen/proto/go/aperture/common/status/v1/status.pb.json.go
- api/gen/proto/go/aperture/common/watchdog/v1/watchdog.pb.json.go
- api/gen/proto/go/aperture/flowcontrol/v1/envoy.pb.json.go
- api/gen/proto/go/aperture/flowcontrol/v1/flowcontrol.pb.json.go
- api/gen/proto/go/aperture/plugins/fluxninja/v1/heartbeat.pb.json.go
- api/gen/proto/go/aperture/policy/decisions/v1/decisions.pb.json.go
- api/gen/proto/go/aperture/policy/language/v1/classifier.pb.json.go
- api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.json.go
- api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/352)
> add back emit_defaults flag

- playground/README.md
- scripts/aperture_dev_cluster.sh
Add Installation script for 3 nodes kind cluster.
Update aperture installation Readme for  k8s.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/197)
> update k8s deployment readme and add kind cluster script

- manifests/charts/aperture-agent/templates/agent.yaml
- operator/controllers/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/358)
> Fixed missing API Key env variable

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/361)
> fix: release circleci filters

- .circleci/config.yml
- .circleci/post-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/360)
> Create remote repository tagging and protobuf pushing jobs

- plugins/service/aperture-plugin-fluxninja/otel/provide.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/373)
> Fix FN plugin constructor params

- docs/gen/config/aperture-controller/config-swagger.yaml
- docs/gen/config/aperture-controller/swagger.md
- pkg/flowcontrol/envoy/baggage/baggage.go
- pkg/flowcontrol/envoy/baggage/baggage_suite_test.go
- pkg/policies/controlplane/validator.go
- pkg/policies/dataplane/resources/classifier/classifier.go
- pkg/policies/dataplane/resources/classifier/classifier_test.go
- pkg/policies/dataplane/resources/classifier/compiler/compiler.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/385)
> extract compiler to a separate package for classifiers

- manifests/charts/aperture-agent/templates/agent.yaml
- manifests/charts/aperture-controller/templates/controller.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/393)
> Fixed YAML rendering issue for lists in charts

- docs/content/concepts/flow-control/label/classifier.md
- pkg/policies/controlplane/validator_test.go
- pkg/policies/dataplane/resources/classifier/classifier_test.go
- pkg/policies/dataplane/resources/classifier/compiler/compiler.go
- pkg/policies/dataplane/resources/classifier/extractors/compile.go
- playground/tanka/apps/demoapp/mixins.libsonnet
Also, document explicitely this limitation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/391)
> Fail classifier compilation on invalid flow label names

- pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
- playground/Tiltfile
- playground/browser/go.mod
- playground/browser/go.sum
- playground/browser/main.go
- playground/tanka/jsonnetfile.lock.json
- tools/load_generator/scenarios/load_test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/399)
> Update Tilt config and blueprints

- docs/content/get-started/installation/controller.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/406)
> Added pointer to install policy using blueprints under get started

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/408)
> change the chart version

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/409)
> Move screenshot to playground

- docs/content/get-started/installation/controller.md
- [-] Documentation is changed or added
Updated the link of the Policy under `Apply Policy` section to the main Policy page under `Concepts`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/413)
> Updated policy link to the first page of policy section

- pkg/policies/controlplane/circuit-factory.go
- pkg/policies/controlplane/circuit.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/396)
> Fix policy compiler

- docs/content/get-started/installation/agent/kubernetes/daemonset.md
- docs/content/get-started/installation/agent/kubernetes/sidecar.md
- docs/content/get-started/installation/controller.md
- operator/controllers/agent_reconciler.go
- operator/controllers/controller_reconciler.go
Added required configuration details in the installation for the controller and Agent to run it without FluxNinja Cloud Plugin.
Also, removed error return on Controller and Agent deletion from Operator as we can't do much when the Objects are not getting deleted for some reasons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/415)
> Fixed controller installation issues and updated docs

- api/aperture/policy/language/v1/fluxmeter.proto
- api/aperture/policy/language/v1/policy.proto
- api/gen/openapiv2/aperture.swagger.yaml
- api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
- api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
- docs/content/concepts/flow-control/flux-meter.md
- docs/content/concepts/flow-control/selector/selector.md
- docs/content/concepts/policy/circuit.md
- docs/content/concepts/policy/resources.md
- docs/content/get-started/blueprints.md
- docs/content/reference/configuration/policies.md
- docs/gen/policies/gen.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/417)
> Fix typos and add backlinks to Policy concept docs

- pkg/otelcollector/metricsprocessor/processor.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/419)
> Fix float parse warning

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
Made the helm chart version change to align with the aperture release version . For now the Aperture app version and chart version will remain same. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/421)
> first helm version release chart changes

- .github/pull_request_template.md
- playground/Tiltfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/424)
> make k6 start after controller has started

- README.md
- api/aperture/policy/language/v1/classifier.proto
- api/aperture/policy/language/v1/fluxmeter.proto
- api/aperture/policy/language/v1/policy.proto
- api/gen/openapiv2/aperture.swagger.yaml
- api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go
- api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
- api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
- docs/content/concepts/flow-control/flow-classifier.md
- docs/content/concepts/flow-control/flow-label.md
- docs/content/concepts/policy/circuit.md
- docs/content/concepts/service.md
- docs/content/reference/configuration/agent.md
- docs/content/reference/configuration/controller.md
- docs/content/reference/configuration/policies.md
- docs/gen/config/agent/config-swagger.yaml
- docs/gen/config/controller/config-swagger.yaml
- docs/gen/policies/gen.yaml
- operator/config/crd/bases/fluxninja.com_agents.yaml
- operator/config/crd/bases/fluxninja.com_controllers.yaml
- pkg/net/listener/listener.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/428)
> Fix typos in docs

- docs/content/get-started/installation/agent/kubernetes/daemonset.md
- pkg/otelcollector/rollup.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/433)
> fix typos suggested by codespell

- README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/435)
> Use markdown syntax to display playground image

- docs/content/get-started/blueprints.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/436)
> tweak blueprint docs

- docs/content/get-started/blueprints.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/437)
> More blueprint fixes

- plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
- plugins/service/aperture-plugin-fluxninja/otel/otel_suite_test.go
- plugins/service/aperture-plugin-fluxninja/otel/otel_test.go
- plugins/service/aperture-plugin-fluxninja/otel/provide.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/446)
> Add FN plugin OTEL tests

- plugins/service/aperture-plugin-fluxninja/otel/otel_test.go
Bringing up platform in plugin UT is not necessary and can lead to data race when tests are ran in parallel.
Closes: GH-447
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/450)
> Do not bring up platform in plugin UT

- cmd/circuit-generator/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/455)
> Move circuit-generator to cmd directory

- .circleci/continue-workflows.yml
- README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/464)
> Fossa circleci

- pkg/net/tlsconfig/server.go
- pkg/otel/config.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/375)
> Unify TLS config

- pkg/otel/config.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/465)
> Fix TLS config

- docs/content/reference/configuration/agent.md
- docs/content/reference/configuration/controller.md
- docs/gen/config/agent/config-swagger.yaml
- docs/gen/config/controller/config-swagger.yaml
- operator/config/crd/bases/fluxninja.com_agents.yaml
- operator/config/crd/bases/fluxninja.com_controllers.yaml
- operator/controllers/configmaps_test.go
- operator/controllers/controller_config_test.tpl
- operator/controllers/controller_reconciler.go
- pkg/net/tlsconfig/server.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/493)
> remove CertPath key from server TLS config

- README.md
- docs/content/reference/configuration/agent.md
- docs/content/reference/configuration/controller.md
- docs/gen/config/agent/config-swagger.yaml
- docs/gen/config/controller/config-swagger.yaml
- operator/config/crd/bases/fluxninja.com_agents.yaml
- operator/config/crd/bases/fluxninja.com_controllers.yaml
- operator/controllers/agent_config_test.tpl
- operator/controllers/configmaps_test.go
- operator/controllers/controller_config_test.tpl
- operator/controllers/controller_reconciler.go
- pkg/net/tlsconfig/server.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/498)
> rename some server tls config fields

- docs/content/get-started/blueprints.md
- docs/content/get-started/playground.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/508)
> Update playground docs

- docs/tools/mermaid/md_to_mmd.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/510)
> fix mermaid generator on macOS

- docs/content/get-started/supported-platforms.md
Upgraded the minimum Kubernetes version to 1.23.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/519)
> Upgraded minimum Kubernetes version to 1.23

- docs/content/get-started/installation/agent/kubernetes/daemonset.md
- docs/content/get-started/installation/agent/kubernetes/sidecar.md
- docs/content/get-started/installation/controller.md
- Added details on how to modify config for Agent and Controller in installation docs.
- Corrected one place where `plugins` config block was added at wrong place under controller.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/475)
> Added details on how to provide custom config for Agent and Controller in docs

- docs/content/get-started/installation/agent/envoy/istio.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/522)
> update envoy filter docs

- docs/content/get-started/installation/agent/kubernetes/daemonset.md
- docs/content/get-started/installation/agent/kubernetes/sidecar.md
- docs/content/get-started/installation/controller.md
Removed extra comma from the YAML examples
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/525)
> Fixed typos in the installation docs

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/527)
> Update chart versions before v0.2.2 release

- go.mod
- pkg/otel/config.go
- plugins/service/aperture-plugin-fluxninja/otel/otel_test.go
- plugins/service/aperture-plugin-fluxninja/otel/provide.go
This fixes two issues:
1. Global scrape config in Base OTEL config was modified by FN plugin
2. Scrape timeout in Base OTEL config was larger that the scrape interval, which is not allowed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/528)
> Fix Prometheus scrape config in OTEL

- playground/tanka/chartfile.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/532)
> revert istio chart changes

- manifests/charts/istioconfig/templates/envoy_filter.yaml
- playground/tanka/apps/demoapp/mixins.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/533)
> fix demo policy classifier rule

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
Helm chart version change to v0.2.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/543)
> helm chart version change for v0.2.2

- cmd/aperture-agent/Dockerfile
- cmd/aperture-controller/Dockerfile
- pkg/info/build.sh
- pkg/plugins/build.sh
Revert the changes made in #547 PR as aperture playground was breaking.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/550)
> reverse #547 PR as aperture playground is failing

- api/aperture/policy/language/v1/policy.proto
- api/gen/openapiv2/aperture.swagger.yaml
- api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
- docs/content/references/configuration/policies.md
- docs/gen/policies/gen.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/554)
> Small grammar fix in docs

- docs/content/get-started/playground.md
- playground/tanka/apps/aperture-controller/mixins.libsonnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/557)
> add pullPolicy for aperture-operator image

- .github/workflows/issues-notion-sync.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/569)
> Set up GitHub Action to sync Issues to Notion

- playground/tanka/apps/demoapp/mixins.libsonnet
- playground/tanka/jsonnetfile.lock.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/570)
> update playground policy file

- .github/workflows/issues-notion-sync.yml
* This should fix the sync from GitHub Issues to Notion
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/575)
> Update Notion Github Action

- docs/content/get-started/blueprints.md
Updated the example under the blueprints documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/583)
> Updated example in the blueprints docs

- playground/tanka/apps/aperture-agent/mixins.libsonnet
- playground/tanka/apps/aperture-controller/mixins.libsonnet
- playground/tanka/apps/demoapp/mixins.libsonnet
We had some of the unused imports in the tanka apps so removed them
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/584)
> Remove non-used imports from Tanka apps

- api/aperture/policy/language/v1/fluxmeter.proto
- api/gen/openapiv2/aperture.swagger.yaml
- api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
- docs/content/references/configuration/policies.md
- docs/gen/policies/gen.yaml
Minor change single quote to back tick in proto commets
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/588)
> FluxMeter doc update

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
helm chart version change to v0.3.0-rc.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/590)
> helm chart version change to v0.3.0-rc.2

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
Upgraded the helm chart versions to v0.3.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/592)
> Upgraded Helm charts versions to 0.3.0

- .circleci/post-release.yaml
Removed the workflow to tag the `aperture-go` repo on Aperture release as it is archived for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/591)
> Removed Ci pipeline to tag the aperture-go repo

- .circleci/post-release.yaml
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
Cherry-picked the changes from main.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/593)
> Cherry-picked changes from main for release 0.3.0

- pkg/k8s/provide.go
- pkg/otel/config.go
Closes: GH-330
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/449)
> Allow construction of OTEL collector outside of k8s environment

- pkg/log/log.go
- pkg/policies/controlplane/circuit-factory.go
- pkg/policies/controlplane/components/actuators/concurrency/concurrency-limiter.go
- pkg/policies/controlplane/components/actuators/concurrency/load-shed-actuator.go
- pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
- pkg/policies/controlplane/components/actuators/rate/rate-limiter.go
- pkg/policies/controlplane/components/ema.go
- pkg/policies/controlplane/components/promql.go
- pkg/policies/controlplane/iface/policy.go
- pkg/policies/controlplane/policy-factory.go
- pkg/policies/controlplane/policy.go
- pkg/policies/controlplane/resources/classifier/classifier.go
- pkg/policies/controlplane/resources/fluxmeter/flux-meter.go
- pkg/policies/controlplane/runtime/circuit.go
- pkg/policies/controlplane/validator.go
- pkg/policies/dataplane/actuators/concurrency/auto-tokens.go
- pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
1.  use default formatting for console logger
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/597)
> Logging improvements

- README.md
This just adds logos to badges in README.md. For Aperture docs it is a base64 verison of Aperture icon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/595)
> Add logos to badges in README

- .github/workflows/issues-notion-sync.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/599)
> Consecutiveness for Notion sync

- .github/workflows/issues-notion-sync.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/601)
> Post message on Slack webhook about notion sync failure

- api/aperture/common/selector/v1/selector.proto
- api/gen/openapiv2/aperture.swagger.yaml
- api/gen/proto/go/aperture/common/selector/v1/selector.pb.go
- docs/content/references/configuration/policies.md
- docs/gen/policies/gen.yaml
Documentation comments received additional comment marks when selectors were refactored; Those characters are removed in this PR
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/607)
> Fix Selector documentation misprints

- docs/content/get-started/installation/agent/envoy/istio.md
- docs/content/get-started/supported-platforms.md
See https://github.com/fluxninja/aperture/issues/483
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/605)
> Document supported Istio and Envoy versions

- .circleci/continue-workflows.yml
- README.md
Removed FOSSA from CircleCI pre-commit job and from README file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/610)
> Removed FOSSA from pre-commit and README

- .github/workflows/issues-notion-sync.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/612)
> Move github notion sync branch to fluxninja

- manifests/charts/aperture-controller/templates/controller.yaml
Removed unused field `operatorImage` from Controller Custom Resource template from helm chart.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/613)
> Removed unused spec from controller chart

- pkg/otelcollector/consts.go
- pkg/otelcollector/metricsprocessor/processor.go
- pkg/otelcollector/metricsprocessor/processor_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/616)
> Classification errors as attribute in OLAP telemetry

- pkg/policies/dataplane/engine.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/625)
> Add ControlPointInfo in CheckResponse

- .github/workflows/issues-notion-sync.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/648)
> Actions native Concurrency instead of Consecutiveness

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
Upgraded helm chart versions to v0.4.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/650)
> Upgraded chart versions to v0.4.0

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/651)
> Cherry-picked changes from main

- .pre-commit-config.yaml
Removing circleci pre-commit as of now . As it giving some error with CI and checking all the files.
Will fix it and raise another PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/652)
> remove circleci pre-commit

- .github/pull_request_template.md
Added a check box for blueprints changes and verification of the example.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/664)
> Updated PR template for blueprint changes

- docs/content/get-started/blueprints.md
Updated the blueprint example on the docs with working jsonnet.
Fixes #660 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/661)
> Fixed the blueprint example

- go.mod
- go.sum
- pkg/metrics/schema.go
- pkg/otelcollector/metricsprocessor/processor.go
- pkg/otelcollector/metricsprocessor/processor_test.go
- pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
- pkg/policies/dataplane/actuators/rate/rate-limiter.go
- pkg/policies/dataplane/engine.go
- pkg/policies/dataplane/engine_test.go
- pkg/policies/dataplane/iface/engine.go
- pkg/policies/dataplane/iface/limiter.go
- pkg/policies/dataplane/iface/rate-limiter.go
- pkg/policies/mocks/mock_engine.go
- pkg/policies/mocks/mock_limiter.go
Added metric counting how many times individual RateLimiters were hit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/655)
> Create metrics for RateLimiter

- pkg/policies/dataplane/iface/classification-engine.go
- pkg/policies/dataplane/iface/classifier.go
- pkg/policies/dataplane/iface/engine.go
- pkg/policies/dataplane/resources/classifier/classification-engine.go
* Classifier and ClassificationEngine interfaces
* Unblocks #459
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/689)
> Classification interfaces

- blueprints/lib/1.0/policies/latency-gradient/latency-gradient.libsonnet
- playground/tanka/apps/aperture-controller/mixins.libsonnet
* Remove const definitions of ports in the Blueprints 
* Create Ports in-place
* Better readability this way
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/692)
> Create ports in-place for better readability

- docs/content/concepts/flow-control/flow-classifier.md
- pkg/flowcontrol/envoy/baggage/baggage.go
- pkg/otelcollector/config.go
- pkg/policies/controlplane/components/ema.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/696)
> fix codespell issues

- pkg/otelcollector/metricsprocessor/processor.go
- pkg/otelcollector/metricsprocessor/processor_test.go
This adds missing log attributes at the output of metrics processor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/698)
> Fix missing log attributes

- docs/content/policies/blueprints.md
- scripts/precommit/check_tanka_show.sh
Fixes #704 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/708)
> fix tanka show pre-commit hook

- pkg/config/validator.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/712)
> remove redundant logs

- docs/content/get-started/installation/controller.md
- playground/tanka/apps/aperture-controller/mixins.libsonnet
* Refactor Controller install docs
* How to provide Controller config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/714)
> Replace Configuration with Controller CRD section

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/717)
> v0.5.0 Release

- .circleci/continue-workflows.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/727)
> circleci: set GOMAXPROCS using enviornment instead of BASH_ENV

- plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
- plugins/service/aperture-plugin-fluxninja/heartbeats/provide.go
> Fix missing policy factory pointer for agent

- blueprints/blueprints/latency-gradient/README.md
- blueprints/blueprints/latency-gradient/config.libsonnet
- blueprints/blueprints/latency-gradient/example/example.jsonnet
- blueprints/blueprints/latency-gradient/example/gen/dashboards/example-signals.json
- blueprints/blueprints/latency-gradient/main.libsonnet
- blueprints/blueprints/latency-gradient/metadata.yaml
- blueprints/lib/1.0/dashboards/signals/signals.libsonnet
- blueprints/scripts/blueprint-readme-generator.py
- playground/tanka/lib/apps/aperture-grafana/main.libsonnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/749)
> blueprints: add policy name filter to signals dashboard

- pkg/distcache/distcache-metrics.go
- pkg/distcache/provider.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/772)
> Readd Distcache metrics

- pkg/status/registry.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/774)
> platform: check nil when detaching registry

- docs/tools/jsonnet/generate_jsonnet.sh
This should help for circleci failure in #782
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/785)
> Run jb install also in generate-doc-assets hook

- sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/790)
> Java SDK: Accept flow in case of unresponsive agent

- playground/load_generator/scenarios/load_test.js
- playground/tanka/apps/aperture-controller/mixins.libsonnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/810)
> playground: revert scenario changes

- cmd/sdk-validator/main.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/818)
> Fix nil pointer error in runDockerContainer

- docs/content/tutorials/flow-control/basic-concurrency-limiting.md
- docs/content/tutorials/flow-control/workload-prioritization.md
- playground/demo_app/main.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/824)
> Fix tutorials and demo_app

- pkg/panichandler/panichandler.go
- playground/tanka/apps/aperture-agent/mixins.libsonnet
- playground/tanka/apps/aperture-controller/mixins.libsonnet
minor fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/825)
> platform: panic handler minor fix

- docs/content/concepts/flow-control/rate-limiter.md
- docs/content/get-started/policies/blueprints.md
- docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.jsonnet
- docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.jsonnet
- docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.jsonnet
- docs/content/tutorials/flow-control/basic-concurrency-limiting.md
- docs/content/tutorials/flow-control/static-rate-limiting.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/833)
> docs: add a note regarding dryrun mode

- manifests/charts/aperture-agent/Chart.lock
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.lock
- manifests/charts/aperture-controller/Chart.yaml
Update the bundled etcd and prometheus versions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/838)
> charts: bump prometheus and etcd

- pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
* Fixes: #346
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/840)
> Skip NaN auto-tokens

- .circleci/continue-workflows.yml
- .pre-commit-config.yaml
- .tool-versions
- scripts/manage_tools.sh
Fix all the minor issue that @hdkshingala mention . 
Earlier It was checking all the files inside `.circleci` dir.. Now it only checks the `*.*ml$` files . 
Add circleci cli install using asdf.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/663)
> add circleci pre-commit v2

- .pre-commit-config.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/845)
> circleci pre-commit version change

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/846)
> Added R/W keys for Helm chart release

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/847)
> Added ssh key usage for helm release

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/848)
> Changes from main to stable/0.8.x for rc.4

- docs/content/get-started/installation/controller.md
Added missing flag to pass additional values with helm command while installation of Aperture Controller. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/852)
> Added missing flag in the controller installation steps

- docs/content/get-started/installation/agent/envoy/istio.md
- docs/content/get-started/installation/agent/kubernetes/daemonset.md
- docs/content/get-started/installation/agent/kubernetes/sidecar.md
- docs/content/get-started/installation/controller.md
- manifests/charts/istioconfig/README.md
- manifests/charts/istioconfig/templates/envoy_filter.yaml
- manifests/charts/istioconfig/values.yaml
- Added installation steps for the istioconfig helm chart
- Added support for sidecar mode in the istioconfig helm chart
- Corrected some of the typos in the installation docs
Fixes #680 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/873)
> Added support for sidecar mode in istioconfig chart and added installation docs

- blueprints/examples/latency-gradient/gen/dashboards/example.json
- blueprints/lib/1.0/blueprints/latency-gradient/dashboard.libsonnet
Fixes #781 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/872)
> Set minimum interval to 1s for timeseries in Grafana

- docs/content/get-started/installation/agent/envoy/istio.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/877)
> Corrected typo in the docs

- docs/content/get-started/playground.md
Issue #850 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/851)
> Removed extra space from `Too many open files "warning"` FAQ section

- docs/content/tutorials/signal-processing/detecting-overload.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/887)
> Docs - Tip about applying FluxMeter to a single workload

- .github/CODEOWNERS
- README.md
- docs/content/tutorials/flow-control/basic-concurrency-limiting.md
- docs/content/tutorials/flow-control/workload-prioritization.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/888)
> docs: add demo video links

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/892)
> Prepare for v0.9.0 release

- pkg/otelcollector/helpers.go
- pkg/policies/flowcontrol/api/envoy/authz.go
- sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/TrafficFlow.java
Now CheckResponse is binary-encoded in protobuf wire format and stored
in DynamicMetadata as base64 string. This speeds up serialization, but
also deserialization (in metrics processor).
No changes in envoyfilter defition were needed as envoy's access logger passes
StringValue from dynamic meatadata as-is (previously, it was JSON-encoding a
StructValue into string) 
Note: metrics processor still accepts JSON-encoding, so other SDKs should
continue working without changes.
(Based on looking at pprof data)
* `createExtAuthzResponse` went from total 18% to total 2.6% (from about 50% of
authz.Check to about 10%).
* `GetStruct` went from total 6% to total 3% (from about 75% of
metricsprocessor.ConsumeLogs to about 40%)
* total ~20% improvement
* now agent's overhead is either comparable or …
> Speed up ser/deserialization of CheckResponse in envoy authz

- .circleci/continue-workflows.yml
- sdks/aperture-js/sdk/client.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/904)
> Update aperture-js fingerprint

- .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/907)
> Add pprof-related files to .gitignore

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/909)
> Fixed deployment sync issue for CRDs

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/916)
> Prepare for release 0.10.0

- .circleci/scripts/helm_release.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/917)
> Fixed Helm version check error on release

- operator/controllers/agent/agent_suite_test.go
- operator/controllers/agent/config_test.tpl
- operator/controllers/controller/config_test.tpl
- operator/controllers/controller/controller_suite_test.go
- operator/controllers/mutatingwebhook/mutatingwebhook_suite_test.go
- operator/controllers/mutatingwebhook/reconciler_test.go
- operator/controllers/namespace/namespace_suite_test.go
- operator/controllers/namespace/reconciler_test.go
After we divided the operator code in sub-modules, it was passing the tests but the actual tests in sub-modules were getting skipped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/930)
> Fixed the operator tests getting skipped issue

- sdks/aperture-java/build.gradle.kts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/932)
> Update opentelemetry exporter dependency

- sdks/aperture-java/version.gradle.kts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/936)
> Update Java SDK snapshot version to 0.4.0

- sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/940)
> Fix failing to start flow when passing null labels map

- sdks/aperture-java/build.gradle.kts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/942)
> Downgrade slf4j dependency

- sdks/aperture-java/build.gradle.kts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/941)
> Relocate all packages when creating a shadow jar

- .circleci/scripts/helm_release.sh
Currently when we release aperture, 3 pipelines make changes to same branch which leads to conflict and git push fails.
If  `git push` fails due to conflict the added check will retry it for 10 times.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/946)
> `git push` retry for Helm-release script  

- pkg/discovery/kubernetes/kubernetes_discovery.go
- pkg/peers/peers.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/953)
> Remove debug log

- docs/gen/config/controller/metadata
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/954)
> Fixed pre-commit failure on controller config docs

- .codespellignore
- pkg/otelcollector/helpers.go
- pkg/otelcollector/metricsprocessor/processor.go
- pkg/otelcollector/rollupprocessor/processor.go
This is a step towards #882.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/956)
> Avoid discarding whole batch if processing single log record fails

- docs/content/cloud/cloud.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/959)
> Changed the cloud beta link from waitlist to sign-in

- pkg/policies/flowcontrol/engine.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/962)
> flowcontrol: Remove spammy "Running limiters with labels" log

- docs/content/cloud/cloud.md
- pkg/policies/flowcontrol/engine.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/963)
> Cherry-picked changes for release 0.11.1-rc.1

- pkg/otelcollector/alertsreceiver/config.go
- pkg/otelcollector/alertsreceiver/factory.go
- pkg/otelcollector/enrichmentprocessor/factory.go
- pkg/otelcollector/metricsprocessor/factory.go
- pkg/otelcollector/rollupprocessor/config.go
- pkg/otelcollector/rollupprocessor/factory.go
- pkg/otelcollector/tracestologsprocessor/config.go
- pkg/otelcollector/tracestologsprocessor/factory.go
- pkg/otelcollector/tracestologsprocessor/processor.go
- Upgrade OTEL to v0.64.0
- Don't use deprecated stuff from OTEL
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/967)
> Don't use deprecated stuff from OTEL

- docs/content/introduction.md
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/971)
> Prepare for release v.0.12.x

- pkg/alerts/alert.go
- pkg/alerts/alert_test.go
- pkg/policies/controlplane/components/alerter.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/977)
> Hide postable alert object, add options to alert

- docs/content/introduction.md
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/994)
> Prepare for release v0.13.x

- cmd/aperture-agent/agent.go
- cmd/sdk-validator/main.go
- pkg/discovery/kubernetes/kubernetes_discovery.go
- pkg/discovery/kubernetes/provide.go
- pkg/discovery/static/provide.go
- pkg/discovery/static/static_discovery.go
- pkg/discovery/static/static_discovery_test.go
- pkg/entitycache/entity_cache.go
- pkg/metrics/schema.go
- pkg/mocks/mock-trackers.go
- pkg/notifiers/tracker.go
- pkg/policies/flowcontrol/provide.go
- pkg/policies/flowcontrol/service/check/check.go
- pkg/policies/flowcontrol/service/check/check_test.go
- pkg/policies/flowcontrol/service/check/provide.go
- pkg/policies/flowcontrol/service/envoy/authz.go
- pkg/policies/flowcontrol/service/envoy/authz_test.go
- pkg/policies/flowcontrol/service/provide.go
- pkg/policies/flowcontrol/servicegetter/metrics.go
- pkg/policies/flowcontrol/servicegetter/provide.go
- pkg/policies/flowcontrol/servicegetter/servicegetter.go
- test/aperture_suite_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/998)
> Cherry-picked changes for release 0.13.0-rc.2

- sdks/aperture-java/Dockerfile
- sdks/aperture-java/examples/armeria-example/src/main/java/com/fluxninja/example/ArmeriaServer.java
- sdks/aperture-java/examples/tomcat-example/build.gradle.kts
- sdks/aperture-java/examples/tomcat-example/src/main/java/com/fluxninja/example/filter/ApertureFilter.java
- sdks/aperture-java/examples/tomcat-example/src/main/java/com/fluxninja/example/servlet/ApertureServlet.java
- sdks/aperture-java/examples/tomcat-example/src/main/webapp/WEB-INF/web.xml
- sdks/aperture-java/lib/tomcat7/build.gradle.kts
- sdks/aperture-java/lib/tomcat7/src/main/java/com/fluxninja/aperture/tomcat7/ApertureFilter.java
- sdks/aperture-java/lib/tomcat7/src/main/java/com/fluxninja/aperture/tomcat7/ServletUtils.java
- sdks/aperture-java/settings.gradle.kts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/996)
> SDK tomcat support

- playground/tanka/apps/aperture-controller/mixins.libsonnet
Removing leftover test values for alertmanagers config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1004)
> Remove alertmanagers test config

- manifests/charts/aperture-controller/values.yaml
Closes: GH-905
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/992)
> Garbage collector in ETCD

- pkg/alerts/alert_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1008)
> Fix alert tests

- cmd/circuit-compiler/main.go
- pkg/policies/controlplane/circuit-factory.go
- pkg/policies/controlplane/circuitcompiler/compiler.go
- pkg/policies/controlplane/circuitcompiler/graph.go
- pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
- pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
- pkg/policies/controlplane/components/actuators/rate/rate-limiter.go
- pkg/policies/controlplane/components/alerter.go
- pkg/policies/controlplane/components/arithmetic-combinator.go
- pkg/policies/controlplane/components/component-factory.go
- pkg/policies/controlplane/components/component-factory_test.go
- pkg/policies/controlplane/components/component-stack-factory.go
- pkg/policies/controlplane/components/constant.go
- pkg/policies/controlplane/components/controller/controller-component.go
- pkg/policies/controlplane/components/controller/gradient.go
- pkg/policies/controlplane/components/decider.go
- pkg/policies/controlplane/components/ema.go
- pkg/policies/controlplane/components/extrapolator.go
- pkg/policies/controlplane/components/first-valid.go
- pkg/policies/controlplane/components/max.go
- pkg/policies/controlplane/components/min.go
- pkg/policies/controlplane/components/promql/promql.go
- pkg/policies/controlplane/components/sink.go
- pkg/policies/controlplane/components/sqrt.go
- pkg/policies/controlplane/components/switcher.go
- pkg/policies/controlplane/policy.go
- pkg/policies/controlplane/runtime/circuit.go
- pkg/policies/controlplane/runtime/component.go
- pkg/policies/controlplane/runtime/ports.go
- pkg/policies/controlplane/validator.go
Recommended reviewing commit-by-commit.
- Move component factory to components package
- Move circuit compiler (aka factory) to separate package
- Extract Ports from CompiledComponent's MapStruct
See individual commit messages for more description.
This is needed for https://github.com/fluxninja/aperture/issues/649
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1005)
> Misc Circuit and Components refactors

- pkg/alerts/alert.go
- pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
- pkg/policies/controlplane/components/alerter.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1009)
> Add GeneratorURL methods to alert

- docs/content/introduction.md
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1010)
> Changes for release v0.14.x

- pkg/alertmanager/client/client.go
- pkg/alerts/alert.go
- pkg/otelcollector/alertsexporter/exporter.go
* Add PostableAlert helpers to Alert. Those will help convert Alert from/to PostableAlert.
* Make AM client interface prometheus agnostic
* Drive-by: Fix Alertmanager exporter not sending full Alerts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1015)
> Alerts improvements

- docs/gen/config/agent/config-swagger.yaml
- docs/gen/config/controller/config-swagger.yaml
- operator/config/crd/bases/fluxninja.com_agents.yaml
- operator/config/crd/bases/fluxninja.com_controllers.yaml
- pkg/alertmanager/client/client.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1016)
> Make alertmanager base path configurable

- blueprints/lib/1.0/blueprints/latency-gradient/README.md
- blueprints/lib/1.0/blueprints/latency-gradient/config.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1021)
> Fix parameter type in latency gradient blueprints doc

- pkg/otelcollector/config.go
Closes: GH-999
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1037)
> Scrape otel metrics alongside aperture self scrape

- docs/content/introduction.md
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1040)
> Changes for release 0.15.x

- README.md
- docs/content/license-faq.md
- docs/content/tutorials/flow-control/basic-concurrency-limiting.md
- docs/content/tutorials/flow-control/dynamic-rate-limiting.md
- docs/content/tutorials/flow-control/graphql-rate-limiting.md
- docs/content/tutorials/flow-control/workload-prioritization.md
Added license FAQ
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1043)
> License faq

- docs/content/introduction.md
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1050)
> Changes for release v0.16.x

- cmd/aperture-agent/Dockerfile
- cmd/aperture-controller/Dockerfile
- nfpm.yaml
- packaging/aperture-agent.service
- packaging/aperture-agent.yaml
- packaging/post-install.sh
- pkg/config/config.go
- Fix color rendering in post-install script
- Don't overwrite the config file on upgrade
- Configure the agent by default to log properly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1048)
> Improve deb packaging

- .circleci/config.yml
- .circleci/continue-workflows.yml
- .circleci/scripts/setup_gcloud.sh
Added steps in CircleCi config to release deb packages on GCP for main and on GitHub releases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1052)
> Added CI steps to upload deb packages

- .circleci/continue-workflows.yml
- nfpm.yaml
Added support for generating RPM packages and uploading them to GCP on merge with main.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1055)
> Added support for generating rpm packages

- .circleci/continue-workflows.yml
- nfpm.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1056)
> Corrected package path in cloud artifacts upload

- docs/content/introduction.md
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1062)
> Changes required for release v0.17.x

- .circleci/post-release.yaml
- docs/content/get-started/installation/agent/bare_metal.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1065)
> Fixed the separator issue in bare metal installation docs and replaced ghr with gh CLI

- README.md
- docs/content/cloud/cloud.md
- docs/content/concepts/flow-control/flow-label.md
- docs/content/tutorials/flow-control/graphql-rate-limiting.md
- docs/content/tutorials/flow-control/workload-prioritization.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1085)
> docs: flow label preview api

- .circleci/config.yml
- .circleci/continue-workflows.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1092)
> Update ci executor

- pkg/config/validator.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1094)
> Remove spammy debug log

- playground/graphql_demo_app/graph/schema.resolvers.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1096)
> Fix pre-commit error in graphql_demo_app

- .circleci/continue-workflows.yml
`remote-docker-version` is updated on cloud repo. So updating it here also. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1097)
> update remote-docker-version in CI

- docs/content/introduction.md
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1098)
> Changes for release v0.18.x

- .circleci/post-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1099)
> Exposed the buf build username in environment variables

- .circleci/post-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1100)
> Cherry-picked changes from main for v0.18.0-rc.2

- cmd/aperture-agent/agent.go
- cmd/aperture-agent/agent/otel-component.go
- cmd/aperture-controller/controller.go
- plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
- plugins/service/aperture-plugin-fluxninja/heartbeats/provide.go
Closes: GH-1069
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1104)
> Remove ControlPointCache dependency in Controller

- .circleci/config.yml
- .circleci/continue-workflows.yml
There was a security incident at CircleCI side so for safety purposes, we have rotated all the environment variables and SSH Keys.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1101)
> Updated SSH Keys for other repos

- docs/content/tutorials/flow-control/basic-concurrency-limiting.md
- docs/content/tutorials/flow-control/dynamic-rate-limiting.md
- docs/content/tutorials/flow-control/graphql-rate-limiting.md
- docs/content/tutorials/flow-control/static-rate-limiting.md
- docs/content/tutorials/flow-control/workload-prioritization.md
- docs/content/tutorials/signal-processing/detecting-overload.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1106)
> Tutorials: Re-order YAML and Jsonnet tabs

- docs/content/assets/scripts/version-code.js
- docs/content/get-started/policies/applying-policies.md
- docs/content/get-started/policies/blueprints.md
- docs/content/get-started/policies/dynamic-configuration.md
- docs/content/get-started/policies/monitoring.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1107)
> Docs: Applying Policies section

- docs/content/get-started/policies/applying-policies.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1110)
> Docs: Update Applying Policies section

- docs/content/get-started/installation/controller.md
- docs/content/get-started/policies/applying-policies.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1111)
> Updated apply policy section on controller installation page

- operator/controllers/agent/reconciler.go
- operator/controllers/controller/reconciler.go
After change of ClusterRole for Agent and Controller, Kubernetes doesn't allow updating the role ref in ClusterRoleBinding and it starts throwing errors during upgrade.
Fixed this by recreating ClusterRoleBinding when error is thrown. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1114)
> Fixed the reconciler errors in operator due to ClusterRole name change

- docs/content/introduction.md
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1120)
> Prepare for release v0.19.x

- docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.jsonnet
- docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.yaml
- docs/tools/jsonnet/generate_jsonnet.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1124)
> docs: validate documented policies even when they don't change

- cmd/sdk-validator/README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1145)
> Add README for sdk-validator

- blueprints/examples/rate-limiter/gen/dashboards/example.json
- blueprints/lib/1.0/blueprints/rate-limiter/README.md
- blueprints/lib/1.0/blueprints/rate-limiter/bundle.libsonnet
- blueprints/lib/1.0/blueprints/rate-limiter/config.libsonnet
- blueprints/lib/1.0/blueprints/rate-limiter/dashboard.libsonnet
- blueprints/lib/1.0/blueprints/rate-limiter/metadata.yaml
- blueprints/lib/1.0/blueprints/rate-limiter/rate-limiter.libsonnet
- playground/tanka/lib/apps/aperture-grafana/main.libsonnet
Added dashboard for rate limit policy using the `rate_limit_counter` metrics as currently, visibility for the same was missing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1143)
> Added dashboard for rate limit policy

- docs/content/get-started/flow-control/sdk/java/auto-instrumentation.md
- sdks/aperture-java/examples/netty-example/build.gradle.kts
- sdks/aperture-java/examples/netty-example/src/main/java/com/fluxninja/example/HelloWorldHandler.java
- sdks/aperture-java/examples/netty-example/src/main/java/com/fluxninja/example/NettyServer.java
- sdks/aperture-java/examples/netty-example/src/main/java/com/fluxninja/example/ServerInitializer.java
- sdks/aperture-java/examples/standalone-example/build.gradle.kts
- sdks/aperture-java/javaagent/README.md
- sdks/aperture-java/javaagent/build.gradle.kts
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/ApertureInstrumentationAgent.java
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/InstrumentationModule.java
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/TransformerInstrumentation.java
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/armeria/ArmeriaClientAdvice.java
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/armeria/ArmeriaClientInstrumentation.java
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/armeria/ArmeriaInstrumentationModule.java
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/armeria/ArmeriaServerAdvice.java
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/armeria/ArmeriaServerInstrumentation.java
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/netty/NettyInstrumentationModule.java
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/netty/NettyServerAdvice.java
- sdks/aperture-java/javaagent/src/main/java/com/fluxninja/aperture/instrumentation/netty/NettyServerInstrumentation.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Constants.java
- sdks/aperture-java/lib/netty/build.gradle.kts
- sdks/aperture-java/lib/netty/src/main/java/com/fluxninja/aperture/netty/ApertureServerHandler.java
- sdks/aperture-java/lib/netty/src/main/java/com/fluxninja/aperture/netty/NettyUtils.java
- sdks/aperture-java/settings.gradle.kts
- sdks/aperture-java/version.gradle.kts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1154)
> Add Aperture Instrumentation Agent

- sdks/aperture-java/javaagent/build.gradle.kts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1156)
> Make java agent shadow jar maven-publishable

- docs/content/get-started/flow-control/sdk/java/auto-instrumentation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1162)
> Provide a proper link to java agent download

- blueprints/scripts/generate_all.sh
- docs/content/apertureVersion.js
- docs/content/aperture_version.md
- docs/content/concepts/flow-control/flow-control.md
- docs/content/get-started/flow-control/sdk/overview.md
- docs/content/get-started/installation/agent/bare_metal.md
- docs/content/get-started/policies/applying-policies.md
- docs/content/get-started/policies/blueprints.md
- docs/content/introduction.md
- docs/content/references/bundled-blueprints/latency-gradient-concurrency-limiting.md
- docs/content/references/bundled-blueprints/signals-dashboard.md
- docs/content/references/bundled-blueprints/static-rate-limiting.md
Update the current flow for aperture version. Now it will use the aperture_version.md file to get the version.
Raising this PR to Complete the 4 point mentioned in this [issue](https://github.com/fluxninja/aperture-tech-docs/issues/134)
for more info check https://github.com/fluxninja/aperture-tech-docs/pull/145
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1160)
> Change import file name from introduction.md to apertureVersion.js

- playground/tanka/apps/policy/mixins.libsonnet
This is useful when showing how alerts work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1170)
> Add alerts channel to playgroud policy

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1171)
> Changes for release v0.20.x

- .circleci/post-release.yaml
Add RACE parameter for bare metal CI 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1172)
> add RACE parameter for bare metal release CI

- api/buf.lock
- blueprints/lib/1.0/blueprints/latency-gradient-concurrency-limiting/README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1176)
> fix pre-commit issues

- .circleci/continue-workflows.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1185)
> circleci: use xlarge instance for pre-commit job

- docs/content/introduction.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1202)
> docs: add slug to intro page

- README.md
- blueprints/README.md
- docs/content/concepts/integrations/flow-control/components/concurrency-limiter.md
- docs/content/concepts/integrations/flow-control/components/rate-limiter.md
- docs/content/concepts/integrations/flow-control/flow-classifier.md
- docs/content/get-started/policies/blueprints/blueprints.md
- manifests/charts/aperture-agent/values.yaml
- manifests/charts/aperture-controller/values.yaml
- playground/README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1204)
> docs: update links

- pkg/policies/controlplane/components/holder_test.go
- pkg/policies/controlplane/components/logical_test.go
- pkg/policies/controlplane/components/pulse-generator_test.go
- pkg/policies/controlplane/runtime/circuit_test.go
- pkg/policies/controlplane/runtime/ports.go
- pkg/policies/controlplane/sim/circuit_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1209)
> Fix circuit UT

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1210)
> Changes for release v0.21.x

- pkg/alerts/alerter.go
Closes: GH-1146
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1225)
> Allow providing arbitrary Labels in alerter

- api/aperture/policy/language/v1/policy.proto
- api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
- docs/content/assets/openapiv2/aperture-controller.swagger.yaml
- docs/content/assets/openapiv2/aperture.swagger.yaml
- docs/content/references/configuration/policy.md
- docs/gen/policy/policy.yaml
- pkg/policies/controlplane/circuitfactory/aimd-concurrency-controller.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1250)
> aimd controller: change how we detect overload based on slope parameter

- blueprints/lib/1.0/policies/latency-aimd-concurrency-limiting/README.md
- blueprints/lib/1.0/policies/latency-aimd-concurrency-limiting/policy.libsonnet
- blueprints/lib/1.0/policies/static-rate-limiting/policy.libsonnet
- docs/content/introduction.md
- docs/content/references/bundled-blueprints/policies/latency-aimd-concurrency-limiting.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1251)
> docs: some tweaks

- cmd/aperture-agent/agent/otel-config.go
Previously we've used deprecated config format (which is shown in the processor docs).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1254)
> Update K8s attr processor config (#1254

- .tool-versions
This should fix the OOM problem - https://github.com/golangci/golangci-lint/pull/3414.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1265)
> Bump golanci-lint to 1.51.0

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1273)
> Changes for release v0.22.x

- cmd/aperturectl/cmd/blueprints/root.go
- cmd/aperturectl/cmd/compile.go
- docs/content/get-started/aperture-cli/aperture-cli.md
- docs/content/get-started/aperture-cli/aperturectl.md
- docs/content/get-started/aperture-cli/aperturectl_blueprints.md
- docs/content/get-started/aperture-cli/aperturectl_compile.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1275)
> Minor changes in format and wordings

- cmd/aperturectl/cmd/root.go
- docs/content/get-started/aperture-cli/aperture-cli.md
- docs/content/get-started/installation/agent/bare_metal.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1278)
> Updated installation steps for CLI

- .circleci/continue-workflows.yml
- .golangci.yaml
- .pre-commit-config.yaml
- .tool-versions
- cmd/aperture-agent/Dockerfile
- cmd/aperture-controller/Dockerfile
- cmd/aperturectl/cmd/blueprints/pull.go
- go.mod
- operator/Dockerfile
- playground/demo_app/Dockerfile
- playground/demo_app/go.mod
- playground/graphql_demo_app/Dockerfile
- playground/graphql_demo_app/go.mod
- sdks/aperture-go/Dockerfile
- sdks/aperture-go/go.mod
- tools/go/go.mod
Until we figure out how to properly build plugins, we need to stick to go 1.19.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1281)
> Get back to Go 1.19

- pkg/status/status-service.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1282)
> Handle crash when providing incorrect status path

- docs/content/reference/policies/bundled-blueprints/dashboards/signals-dashboard.md
- docs/content/reference/policies/bundled-blueprints/policies/latency-aimd-concurrency-limiting.md
- docs/content/reference/policies/bundled-blueprints/policies/static-rate-limiting.md
- scripts/blueprint-readme-generator.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1290)
> blueprints: fix default value in generated docs

- .circleci/continue-workflows.yml
- cmd/aperturectl/cmd/blueprints/generate.go
- cmd/aperturectl/cmd/blueprints/root.go
- docs/content/get-started/policies/assets/raw_values.yaml
- docs/content/get-started/policies/assets/validate.sh
- docs/content/get-started/policies/assets/values.yaml
- docs/content/get-started/policies/policies.md
- docs/content/reference/aperturectl/blueprints/blueprints.md
- docs/content/reference/aperturectl/blueprints/generate/generate.md
- docs/content/reference/aperturectl/blueprints/list/list.md
- docs/content/reference/aperturectl/blueprints/pull/pull.md
- docs/content/reference/aperturectl/blueprints/remove/remove.md
- docs/content/reference/aperturectl/blueprints/values/values.md
- docs/content/reference/policies/bundled-blueprints/dashboards/signals-dashboard.md
- docs/content/reference/policies/bundled-blueprints/policies/latency-aimd-concurrency-limiting.md
- docs/content/reference/policies/bundled-blueprints/policies/static-rate-limiting.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1291)
> blueprints: update getting-started

- api/aperture/policy/language/v1/selector.proto
- api/gen/proto/go/aperture/policy/language/v1/selector.pb.go
- docs/content/assets/openapiv2/aperture-controller.swagger.yaml
- docs/content/assets/openapiv2/aperture.swagger.yaml
- docs/content/reference/policies/spec.md
- docs/gen/policy/policy.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1295)
> docs: fix admonitions

- cmd/aperturectl/cmd/blueprints/generate.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1296)
> aperturectl: remove tempdir when done with apply (#1296

- cmd/aperturectl/cmd/blueprints/values.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1298)
> Minor fix in aperturectl doc indentation

- .pre-commit-config.yaml
- Makefile
- docs/Makefile
- docs/content/reference/aperturectl/blueprints/values/values.md
- scripts/precommit/generate_aperturectl_docs.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1300)
> precommit: bring back aperturectl docs step

- blueprints/policies/static-rate-limiting/dashboard.libsonnet
- playground/tanka/lib/apps/aperture-grafana/main.libsonnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1301)
> Fixed the rate limit dashboard issue

- docs/content/get-started/aperture-cli/aperture-cli.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1302)
> Updated commands per shell type for auto completion

- cmd/aperturectl/cmd/apply/root.go
Added the policy validate annotations for policies getting applied via aperturectl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1307)
> Added validate policy annotation for apply via aperturectl

- api/buf.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1308)
> Update  buf.lock

- docs/content/introduction.md
- docs/content/reference/policies/bundled-blueprints/policies/latency-aimd-concurrency-limiting.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1311)
> docs: minor fixes

- docs/content/architecture/architecture.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1312)
> add description on arch page

- api/buf.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1324)
> Update buf.build commit

- docs/content/sidebars.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1326)
> Add link to blog in sidebar

- api/aperture/policy/language/v1/policy.proto
- api/buf.lock
- api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
- blueprints/gen/v1/alerterparameters.libsonnet
- blueprints/gen/v1/loadactuator.libsonnet
- docs/content/assets/openapiv2/aperture-controller.swagger.yaml
- docs/content/assets/openapiv2/aperture.swagger.yaml
- docs/content/reference/policies/spec.md
- docs/gen/policy/policy.yaml
- pkg/policies/controlplane/circuitfactory/aimd-concurrency-controller.go
- pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
- pkg/policies/controlplane/components/alerter.go
Closes: GH-1306
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1325)
> Remove built-in alerter in LoadActuator, create as normal component

- docs/content/get-started/integrations/flow-control/sdk/java/auto-instrumentation.md
- sdks/aperture-java/dockerfiles/javaagent/armeria/Dockerfile
- sdks/aperture-java/dockerfiles/javaagent/netty/Dockerfile
- sdks/aperture-java/javaagent/README.md
- sdks/aperture-java/javaagent/agent/src/main/java/com/fluxninja/aperture/instrumentation/Config.java
- sdks/aperture-java/javaagent/agent/src/main/java/com/fluxninja/aperture/instrumentation/armeria/ArmeriaClientAdvice.java
- sdks/aperture-java/javaagent/agent/src/main/java/com/fluxninja/aperture/instrumentation/armeria/ArmeriaServerAdvice.java
- sdks/aperture-java/javaagent/agent/src/main/java/com/fluxninja/aperture/instrumentation/netty/NettyServerAdvice.java
- sdks/aperture-java/javaagent/agent/src/main/java/com/fluxninja/aperture/instrumentation/utils/ConfigReader.java
- sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPClient.java
- sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPService.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDKBuilder.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/TrafficFlow.java
- sdks/aperture-java/lib/netty/src/main/java/com/fluxninja/aperture/netty/ApertureServerHandler.java
- sdks/aperture-java/lib/tomcat7/src/main/java/com/fluxninja/aperture/tomcat7/ApertureFilter.java
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1321)
> Javaagent advanced config

- docs/content/reference/observability/flow-metrics/flow-metrics.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1335)
> Docs: Re-phrase introduction of flow metrics

- .circleci/config.yml
- .circleci/continue-workflows.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1332)
> Added CI for updating blueprints on customer demo environment

- docs/content/get-started/installation/agent/kubernetes/daemonset.md
- docs/content/get-started/installation/agent/kubernetes/sidecar.md
- docs/content/get-started/installation/controller/controller.md
- docs/content/reference/kubernetes-operator/_category_.yml
- docs/content/reference/kubernetes-operator/agent.md
- docs/content/reference/kubernetes-operator/controller.md
- manifests/charts/aperture-agent/templates/_helpers.tpl
- manifests/charts/aperture-controller/templates/_helpers.tpl
Added list of Kubernetes objects which is created as part of our installation process so users can refer it in case of conflicts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1338)
> Added doc for list of kubernetes objects created during installation

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1342)
> Changes for release v0.23.x

- blueprints/dashboards/signals-dashboard/dashboard.libsonnet
- docs/content/reference/policies/assets/monitoring/signals-dashboard.json
The dashboard was broken during refactoring done earlier this week.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1346)
> blueprints: fix datasource in signals dashboard

- api/buf.lock
- blueprints/policies/latency-aimd-concurrency-limiting/values.yaml
- scripts/blueprint-readme-generator.py
Fix indentation issue while rendering values.yaml files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1347)
> blueprints: fix indentation in values.yaml generator

- sdks/aperture-java/javaagent/agent/build.gradle.kts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1349)
> Make gradle assemble javaagent shadowJar

- pkg/net/grpc/server.go
This adds a way to add additional GRPC Server options with FX without the need to modify platform code. This should be useful when adding custom interceptors to the main platform GRPC server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1354)
> Allow additional options to GRPC server

- sdks/aperture-go/go.mod
- sdks/aperture-go/go.sum
- sdks/aperture-go/sdk/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1358)
> Made the maps write safe in SDK middle-ware helpers

- api/buf.lock
- sdks/aperture-go/go.mod
- sdks/aperture-go/go.sum
- sdks/aperture-go/sdk/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1359)
> Used zerolog in Go SDK instead of aperture log

- cmd/aperture-agent/Dockerfile
- cmd/aperture-controller/Dockerfile
- playground/Tiltfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1360)
> Add option to skip building plugins in playground

- blueprints/README.md
small fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1362)
> blueprints: fix readme links

- docs/content/get-started/aperture-cli/aperture-cli.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1366)
> Corrected aperturectl brew install command for linux

- api/buf.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1368)
> Update buf commit

- cmd/aperturectl/cmd/blueprints/values.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1376)
> Fix handling of EDITOR and VISUAL environment variables with spaces

- .circleci/continue-workflows.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1379)
> Update latest environment instead of customer-demo on changes from main

- cmd/aperturectl/cmd/blueprints/values.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1380)
> Backward compatibility for generating values file in aperturectl

- manifests/charts/aperture-agent/README.md
- manifests/charts/aperture-controller/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1381)
> Fixed the pre-commit due to new version of helm readme generator

- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1382)
> Changes for release 0.24.x

- api/aperture/policy/language/v1/policy.proto
- api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
- blueprints/gen/jsonschema/_definitions.json
- blueprints/policies/latency-aimd-concurrency-limiting/dashboard.libsonnet
- docs/content/assets/openapiv2/aperture-controller.swagger.yaml
- docs/content/assets/openapiv2/aperture.swagger.yaml
- docs/content/reference/policies/spec.md
- docs/gen/policy/policy.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1386)
> use a separate panel for accepted vs. rejected decisions

- scripts/blueprint-assets-generator.py
remove redundant statement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1395)
> blueprints asset generator: minor fix

- cmd/aperturectl/cmd/utils/utils.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1397)
> Handled minor change for backward compatibility in aperturectl

- .circleci/post-release.yaml
- .circleci/scripts/update_environment.sh
As discussed for the release process, added CI config to update the `demo` environment when a release is out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1399)
> Added CI config for updating demo on release

- pkg/status/status-service.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1400)
> Properly handle request to v1/status root

- .circleci/post-release.yaml
- .circleci/scripts/update_environment.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1402)
> Added missing asdf command in post-release script

- .circleci/post-release.yaml
- .circleci/scripts/update_environment.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1403)
> Cherry-picked changes for release 0.24.0-rc.3

- .circleci/post-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1405)
> Corrected environment variable name in post-release script

- .circleci/post-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1406)
> Cherry-picked changes for release 0.24.0-rc.4

- .opsninja.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1410)
> Fixed demo-app chart location

- .circleci/config.yml
- playground/scenarios/demo-app/manifests/main.jsonnet
- playground/scenarios/demo-app/manifests/mixins.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1411)
> Updated demo-app scenario to use mixins

- api/buf.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1420)
> fix pre-commit

- playground/scenarios/demo-app/policies/service1-demo-app-cr.yaml
- playground/scenarios/demo-app/policies/service1-demo-app.yaml
- playground/scenarios/graphql-example-1/policies/graphql-static-rate-limiting.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1421)
> playground: add yaml ls schema to values.yaml

- playground/scenarios/wavepool-generator/apps-v1.Deployment-wavepool-graphql-generator.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1425)
> Start wavepool generator by default

- go.mod
- go.sum
This fork contains fix for https://github.com/jsonnet-bundler/jsonnet-bundler/issues/169.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1427)
> Use forked jsonnet-bundler

- api/buf.lock
- blueprints/policies/latency-aimd-concurrency-limiting/config.libsonnet
- blueprints/policies/latency-aimd-concurrency-limiting/gen/definitions.json
- blueprints/policies/latency-aimd-concurrency-limiting/gen/values-required.yaml
- blueprints/policies/latency-aimd-concurrency-limiting/gen/values.yaml
- docs/content/reference/policies/bundled-blueprints/policies/latency-aimd-concurrency-limiting.md
- docs/content/tutorials/integrations/flow-control/concurrency-limiting/assets/basic-concurrency-limiting/basic-concurrency-limiting.jsonnet
- docs/content/tutorials/integrations/flow-control/concurrency-limiting/assets/basic-concurrency-limiting/values.yaml
- docs/content/tutorials/integrations/flow-control/concurrency-limiting/assets/rate-limiting-escalation/rate-limiting-escalation.jsonnet
- docs/content/tutorials/integrations/flow-control/concurrency-limiting/assets/rate-limiting-escalation/values.yaml
- docs/content/tutorials/integrations/flow-control/concurrency-limiting/assets/workload-prioritization/values.yaml
- playground/scenarios/demo-app/policies/service1-demo-app-cr.yaml
- playground/scenarios/demo-app/policies/service1-demo-app.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1429)
> latency aimd blueprint: make alert name optinal parameter

- blueprints/dashboards/signals-dashboard/gen/definitions.json
- blueprints/gen/jsonschema/_definitions.json
- blueprints/policies/latency-aimd-concurrency-limiting/gen/definitions.json
- blueprints/policies/latency-aimd-concurrency-limiting/gen/dynamic-config-definitions.json
- blueprints/policies/static-rate-limiting/gen/definitions.json
- blueprints/policies/static-rate-limiting/gen/dynamic-config-definitions.json
- docs/content/assets/openapiv2/aperture-controller.swagger.yaml
- docs/content/assets/openapiv2/aperture.swagger.yaml
- docs/content/reference/configuration/agent.md
- docs/content/reference/configuration/controller.md
- docs/content/reference/policies/spec.md
- docs/gen/config/agent/config-swagger.yaml
- docs/gen/config/aperture-plugin-fluxninja/plugin-swagger.yaml
- docs/gen/config/aperture-plugin-sentry/plugin-swagger.yaml
- docs/gen/config/controller/config-swagger.yaml
- docs/gen/policy/policy.yaml
- docs/tools/swagger/process-go-tags.go
- docs/tools/swagger/swagger-templates/config.gotmpl
- scripts/blueprint-assets-generator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1430)
> translate go defaults to swagger defaults

- blueprints/gen/jsonschema/_definitions.json
- docs/content/assets/openapiv2/aperture-agent.swagger.yaml
- docs/content/assets/openapiv2/aperture-controller.swagger.yaml
- docs/content/assets/openapiv2/aperture.swagger.yaml
- docs/content/reference/configuration/agent.md
- docs/content/reference/configuration/controller.md
- docs/content/reference/policies/spec.md
- docs/gen/config/agent/config-swagger.yaml
- docs/gen/config/aperture-plugin-fluxninja/plugin-swagger.yaml
- docs/gen/config/controller/config-swagger.yaml
- docs/gen/policy/policy.yaml
- docs/tools/swagger/process-go-tags.go
- docs/tools/swagger/swagger-templates/config.gotmpl
- scripts/jsonnet-lib-gen.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1431)
> translate go validates we use to swagger constraints

- playground/.tiltignore
- playground/Tiltfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1432)
> Enabled auto-reload of tilt for changes in scenarios

- api/aperture/policy/language/v1/fluxmeter.proto
- api/aperture/policy/language/v1/policy.proto
- api/aperture/policy/language/v1/selector.proto
- api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
- api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
- api/gen/proto/go/aperture/policy/language/v1/selector.pb.go
- blueprints/gen/jsonschema/_definitions.json
- docs/content/assets/openapiv2/aperture-agent.swagger.yaml
- docs/content/assets/openapiv2/aperture-controller.swagger.yaml
- docs/content/assets/openapiv2/aperture.swagger.yaml
- docs/content/reference/configuration/agent.md
- docs/content/reference/configuration/controller.md
- docs/content/reference/policies/spec.md
- docs/gen/config/agent/config-swagger.yaml
- docs/gen/config/aperture-plugin-fluxninja/plugin-swagger.yaml
- docs/gen/config/controller/config-swagger.yaml
- docs/gen/policy/policy.yaml
- docs/tools/swagger/process-go-tags.go
- docs/tools/swagger/swagger-templates/config.gotmpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1433)
> docs: replace pattern with human readable patterns

- .circleci/continue-workflows.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1436)
> circleci: add jsonnet vendor to daily cache

- operator/controllers/agent/configmaps_test.go
- operator/controllers/controller/configmaps_test.go
- operator/controllers/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1439)
> Removed map sorting from ConfigMap tests

- scripts/precommit/generate_playground_policies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1440)
> Fixed pre-commit failures on main

- docs/content/get-started/installation/agent/kubernetes/daemonset.md
- docs/content/get-started/installation/agent/kubernetes/sidecar.md
- docs/content/get-started/installation/controller/controller.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1441)
> Fixed format issues of installation pages

- .circleci/config.yml
- .circleci/continue-workflows.yml
- .circleci/post-release.yaml
- .gitignore
- api/aperture/flowcontrol/preview/v1/preview.proto
- api/aperture/policy/language/v1/policy.proto
- api/enrich-api-swagger.go
- api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.go
- api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
- blueprints/CONTRIBUTING.md
- blueprints/gen/jsonschema/_definitions.json
- docs/content/assets/openapiv2/aperture-agent.swagger.yaml
- docs/content/assets/openapiv2/aperture-controller.swagger.yaml
- docs/content/assets/openapiv2/aperture.swagger.yaml
- docs/content/get-started/policies/assets/validate.sh
- docs/content/reference/policies/spec.md
- docs/gen/policy/policy.yaml
- docs/tools/aperturectl/validate_all.sh
- docs/tools/aperturectl/validate_common.sh
- docs/tools/jsonnet/generate_jsonnet.sh
- scripts/build_aperturectl.sh
- scripts/precommit/generate_playground_policies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1442)
> api docs: remove gotags in the title in addition to description

- cmd/aperture-agent/Dockerfile
- cmd/aperture-controller/Dockerfile
- playground/Tiltfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1443)
> fix playground and build plugins on builder base

- blueprints/policies/static-rate-limiting/config.libsonnet
- blueprints/policies/static-rate-limiting/gen/definitions.json
- blueprints/policies/static-rate-limiting/gen/values-required.yaml
- blueprints/policies/static-rate-limiting/gen/values.yaml
- docs/content/get-started/policies/assets/raw_values.yaml
- docs/content/get-started/policies/assets/validate.sh
- docs/content/get-started/policies/policies.md
- docs/content/reference/policies/bundled-blueprints/policies/static-rate-limiting.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1450)
> Fixed limit_reset_interval not getting added in values.yaml

- cmd/aperturectl/cmd/apply/policy.go
- manifests/charts/aperture-agent/Chart.yaml
- manifests/charts/aperture-controller/Chart.yaml
- manifests/charts/istioconfig/Chart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1451)
> Prepare for 0.25.x

- .circleci/config.yml
- .circleci/continue-workflows.yml
- .circleci/post-release.yaml
- .golangci.yaml
- .pre-commit-config.yaml
- .tool-versions
- cmd/aperture-agent/Dockerfile
- cmd/aperture-controller/Dockerfile
- go.mod
- operator/Dockerfile
- playground/scenarios/demo-app/application/Dockerfile
- playground/scenarios/demo-app/application/go.mod
- playground/scenarios/graphql-example-1/application/graphql_demo_app/Dockerfile
- playground/scenarios/graphql-example-1/application/graphql_demo_app/go.mod
- scripts/go_mod_tidy.sh
- scripts/invalidate_asdf_ci_cache.sh
- scripts/update_go_version.sh
- sdks/aperture-go/Dockerfile
- sdks/aperture-go/go.mod
- tools/go/go.mod
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1454)
> Script to update go version everywhere

- cmd/aperture-agent/Dockerfile
- cmd/aperture-controller/Dockerfile
- plugins/service/aperture-plugin-sentry/main.go
- plugins/service/aperture-plugin-sentry/sentry/sentry.go
Fixed issue of docker build  complaining about permissions and Sentry plugin config not passing correctly due to key mismatch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1459)
> Fixed docker build and sentry plugin issues

- sdks/aperture-java/examples/standalone-example/src/main/java/com/fluxninja/example/App.java
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1467)
> Make feature name configurable in the feature example

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1477)
> use recursive go mod tidy script in the Makefile

- docs/content/concepts/integrations/flow-control/flow-label.md
- docs/content/concepts/integrations/flow-control/flow-selector.md
- docs/content/concepts/integrations/flow-control/resources/classifier.md
Follow-up to #1418 
Drive-by: Fixed some links.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1499)
> docs: Show that aperturectl can be used for live-preview

- playground/Tiltfile
- playground/resources/grafana-dashboard/main.libsonnet
- playground/scenarios/autoscaling/dashboards/main.jsonnet
- playground/scenarios/autoscaling/metadata.json
- playground/scenarios/demo-app/dashboards/main.jsonnet
- playground/scenarios/demo-app/metadata.json
- playground/scenarios/graphql-example-1/dashboards/main.jsonnet
- playground/scenarios/graphql-example-1/metadata.json
- playground/tanka/lib/apps/aperture-grafana/main.libsonnet
Generate signals dashboards per scenario so that the correct policy name can be passed to it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fluxninja/aperture/1500)
> Added support for generating signals dashboard with scenario

- playground/scenarios/basic_concurrency_limiting/load_generator
- playground/scenarios/static_rate_limiting/load_generator
- playground/scenarios/workload_prioritization/load_generator
> fix: make the symlink path relative in playground scenarios

- pkg/config/koanf-unmarshaller.go
- pkg/config/protobuf-unmarshaller.go
- pkg/config/unmarshaller.go
- pkg/entitycache/entity_cache.go
- pkg/etcd/notifier/key.go
- pkg/etcd/notifier/prefix.go
- pkg/filesystem/notifier/directory.go
- pkg/filesystem/notifier/file.go
- pkg/jobs/job.go
- pkg/notifiers/basic-notifier.go
- pkg/notifiers/fx-driver.go
- pkg/notifiers/notifier.go
- pkg/notifiers/notifier_test.go
- pkg/notifiers/tracker.go
- pkg/notifiers/unmarshal-notifier.go
- pkg/peers/peers.go
- pkg/policies/controlplane/components/autoscale/podscaler/scale-reporter.go
- pkg/policies/controlplane/policy-factory.go
- pkg/policies/controlplane/policy.go
- pkg/policies/flowcontrol/actuators/concurrency/auto-tokens.go
- pkg/policies/flowcontrol/actuators/concurrency/concurrency-limiter.go
- pkg/policies/flowcontrol/actuators/concurrency/load-actuator.go
- pkg/policies/flowcontrol/actuators/rate/rate-limiter.go
- pkg/policies/flowcontrol/resources/classifier/provide.go
- pkg/policies/flowcontrol/resources/fluxmeter/flux-meter.go
- pkg/policies/infra/actuators/podscaler/pod-scaler.go
- test/etcd_watcher_test.go
> platform: refactor notifiers a bit

- pkg/discovery/kubernetes/provide.go
- pkg/discovery/kubernetes/service-discovery.go
- pkg/mocks/mock-trackers.go
- pkg/notifiers/notifier_test.go
- pkg/notifiers/tracker.go
> add UpdateValue functonality in notifiers

- .circleci/continue-workflows.yml
- sdks/aperture-java/examples/spring-example/build.gradle.kts
- sdks/aperture-java/examples/spring-example/src/main/java/com/fluxninja/example/controller/AppController.java
- sdks/aperture-java/examples/spring-example/src/main/java/com/fluxninja/example/filter/ApertureFeatureFilter.java
> Downgrade spring example to work with Java 8

- .github/workflows/chatgpt-review.yml
- .github/workflows/openai-issue-labeler.yml
> github action: chatgpt code review

- .github/workflows/chatgpt-review.yml
**Chore:** Renamed repository used in a workflow job.
> chatgpt review: rename repository

- pkg/policies/flowcontrol/service/envoy/authz.go
New Feature: This pull request adds source and destination services array to the classifier input, creates flow labels from them, and updates telemetry accordingly.
> Add source/destination services array in classifier input

- .github/workflows/chatgpt-review.yml
This pull request updates the GitHub action workflow for ChatGPT. The changes include improving workflow concurrency and removing unnecessary path filters. These changes are intended to improve the efficiency and thoroughness of the review process.
> update github action

- .github/workflows/openai-review.yml
- pkg/config/koanf-unmarshaller.go
This pull request includes a new feature and a bug fix. The `openai` action has been updated to include `pull_request_review_comment` events and added a `cancel-in-progress` field to cancel in-progress workflows. Additionally, a typo in a comment has been fixed.
> update openai action

- docs/content/tutorials/integrations/auto-scale/load-based-auto-scaling.md
- docs/content/tutorials/integrations/flow-control/classification/graphql-rate-limiting.md
- docs/content/tutorials/integrations/flow-control/concurrency-limiting/basic-concurrency-limiting.md
- docs/content/tutorials/integrations/flow-control/concurrency-limiting/rate-limiting-escalation.md
- docs/content/tutorials/integrations/flow-control/concurrency-limiting/workload-prioritization.md
- docs/content/tutorials/integrations/flow-control/rate-limiting/static-rate-limiting.md
Documentation: Added circuit diagrams to various tutorials for better understanding of flow control and auto-scaling policies.
> Hide and link circuit diagrams in tutorials

- api/buf.lock
- docs/content/get-started/installation/agent/kubernetes/daemonset.md
- docs/content/get-started/installation/agent/kubernetes/sidecar.md
- docs/content/get-started/installation/controller/controller.md
- docs/content/get-started/policies/assets/values.yaml
Documentation: Minor changes to installation docs for Kubernetes daemonset and sidecar agents, as well as the Aperture Controller. Removed redundant lines of code and simplified installation commands. No new features or bug fixes were introduced.
> Minor changes for installation docs

- scripts/blueprint-assets-generator.py
- scripts/jsonnet-lib-gen.py
This pull request includes a formatting update for Python scripts. It adds a new function `withNameMixinFilter` and makes minor changes to the existing code in `scripts/jsonnet-lib-gen.py`. This is a "Refactor" change that improves the readability and maintainability of the codebase.
> Format python scripts

- api/buf.lock
- docs/content/get-started/installation/agent/kubernetes/daemonset.md
- docs/content/get-started/installation/agent/kubernetes/sidecar.md
- docs/content/get-started/installation/controller/controller.md
- docs/content/get-started/policies/assets/values.yaml
**Documentation:** This pull request contains cherry-picked changes for v1.0.0-rc.3, which remove redundant ":::" from markdown files and update the installation guide for Aperture Controller to refer to documentation instead of command line arguments.
> Cherry-picked changes for v1.0.0-rc.3

- .circleci/post-release.yaml
This pull request adds a new feature that ensures newly created branches are tracked properly when pushing changes to create a pull request. This should help prevent issues related to branch tracking and improve the overall stability of the system.
> Make sure to track newly created branch on homebrew update

- .circleci/post-release.yaml
- .dockerignore
- cmd/aperturectl/cmd/build/build.go
Here are the release notes for this pull request:
```
Cherry-picked changes for release v1.0.0-rc.4
- Chore: Adds a command to track all remote branches before pushing changes and creating a pull request.
- Chore: Adds `.git` to the list of files that should not be ignored by Docker.
- Refactor: Updates `getLdFlags` function to find git commit hash and branch separately.
```
These changes are focused on improving the development process by adding a command to track all remote branches, updating `.dockerignore`, and refactoring the `getLdFlags` function.
> Cherry-picked changes for release v1.0.0-rc.4

- .github/workflows/openai-review.yml
Chore: Update job name in `.github/workflows/openai-review.yml` from "test" to "review".
> update review job name

- README.md
This pull request removes thumbnail images from video links in the README.md file. This change is categorized as a "Documentation" update and improves the readability of the file for users.
> README: Remove video thumbnails

- docs/content/get-started/integrations/flow-control/sdk/go/manual.md
- docs/content/get-started/integrations/flow-control/sdk/java/armeria.md
- docs/content/get-started/integrations/flow-control/sdk/java/auto-instrumentation.md
- docs/content/get-started/integrations/flow-control/sdk/java/manual.md
- docs/content/get-started/integrations/flow-control/sdk/java/netty.md
- docs/content/get-started/integrations/flow-control/sdk/java/springboot.md
- docs/content/get-started/integrations/flow-control/sdk/java/tomcat.md
- docs/content/get-started/integrations/flow-control/sdk/javascript/manual.md
Documentation: Updated versions and links of various SDKs in the documentation to improve accuracy and usefulness for users. Changes include updating links to example apps, updating version numbers, and fixing URLs.
> Updated versions of SDKs in docs

- .circleci/post-release.yaml
- docs/content/get-started/integrations/flow-control/gateway/kong.md
- docs/content/get-started/integrations/flow-control/gateway/nginx.md
Release Notes:
- Documentation: Updates installation instructions for Aperture Lua module in Nginx gateway integration documentation, modifies Dockerfile for installing Aperture Custom plugin with Kong, and updates `post-release.yaml` file to modify `Attach package to release` job.
> "Code changes big or small,
> Documentation updated for all.
> Build process improved with care,
> Bugs fixed, we're happy to share."
> Fixes in aperture lua module installation docs

- .circleci/post-release.yaml
- docs/content/get-started/integrations/flow-control/gateway/kong.md
- docs/content/get-started/integrations/flow-control/gateway/nginx.md
- manifests/charts/aperture-agent/templates/agent.yaml
- manifests/charts/aperture-controller/templates/controller.yaml
Release Notes:
- Chore: Cherry-picked changes for v1.1.0-rc.2, including updates to CircleCI configuration and Dockerfiles for Aperture Custom plugin with Kong and Nginx integration with OpenTelemetry and Aperture.
> "Cherry-pick complete, 
> Deployment process now neat. 
> With Kong and Nginx in tow, 
> Our project's ready to go!"
> Cherry-picked changes for v1.1.0-rc.2

- .circleci/post-release.yaml
- docs/content/get-started/integrations/flow-control/gateway/kong.md
- docs/content/get-started/integrations/flow-control/gateway/nginx.md
Release Notes:
- Documentation: Minor corrections made to Lua module installation docs for Kong and Nginx.
> "Code reviewed, docs improved,
> Lua modules now rightly grooved.
> Bugs squashed, clarity gained,
> User experience now unchained."
> Minor corrections in Lua module installation docs

- .github/workflows/openai-review.yml
- Use GPT-4 for code reviews and limit max files to summarize
> 🎉 A new era has begun, with GPT-4 in tow,
> 🚀 Our code reviews will soar, as the summaries grow.
> 📚 With a limit set, we'll keep it concise,
> 🌟 And make our release notes ever so nice.
> use gpt-4 for code reviews

- playground/Tiltfile
**Bug fix:**
- Fixed passing local settings to Tilt by adjusting the order of function calls in the Tiltfile.
> 🎉 Hooray for the fix, so swift and neat,
> Local settings now take their rightful seat.
> Tilt's configuration sings with glee,
> For this pull request sets it free! 🚀
> Fixed passing local settings to tilt

- .circleci/config.yml
- .circleci/continue-workflows.yml
- .circleci/post-release.yaml
- .tool-versions
- blueprints/blueprint-assets-generator.py
- cmd/aperture-agent/Dockerfile
- cmd/aperture-controller/Dockerfile
- operator/Dockerfile
- playground/resources/demo-app/Dockerfile
- playground/resources/graphql-demo-app/Dockerfile
- scripts/invalidate_asdf_ci_cache.sh
- sdks/aperture-go/Dockerfile
Release Notes:
- Chore: Update Golang version and cache keys in various files across the repository.
> 🎉 Updating Golang,  
> 🚀 Keeping things up to date.  
> 🌟 Routine maintenance.
> blueprints: fix rendering of array objects

- pkg/policies/controlplane/validator.go
Reverts fluxninja/aperture#1713
**Revert:**
- Reverted handling of multiple FluxMeter definitions with the same name in `validator.go`, simplifying the code by removing mutex and map usage.
> 🎉 A simpler path we've found today,
> 🔄 Reverting changes, we're on our way.
> 🗺️ No more maps, no mutex strife,
> 🌟 A cleaner code to bring new life. 🎉
> Revert "Handle multiple definitions of FluxMeter with same name"

- .circleci/continue-workflows.yml
- .circleci/post-release.yaml
- cmd/aperturectl/cmd/blueprints/root.go
- cmd/aperturectl/cmd/root.go
- docs/content/get-started/aperture-cli/aperture-cli.md
- pkg/otelcollector/alertsreceiver/receiver.go
- pkg/policies/controlplane/validator.go
- playground/scenarios/graphql_query_static_rate_limiting/load_generator/test.js
- Added support for URI input (local path or remote git repository) for blueprints
**Bug fix:**
- Prevented potential panic in `otelcollector` package by adding a nil check
- Updated Aperture CLI documentation with instructions for downloading and installing the binary executable directly from GitHub
**Style:**
- Removed unnecessary escaping of forward slashes in the `sign` function
> 🎉 A new way to handle blueprint URIs we bring,
> 🛠️ Fixing bugs, making our codebase sing.
> 📚 Documentation improved, so users can see,
> 🌟 How to download and install with glee.
> Cherry-picked changes from main for release v1.3.0-rc.2

- .circleci/config.yml
- .circleci/continue-workflows.yml
- .circleci/post-release.yaml
**Chore:**
- Updated cache version numbers and keys for ASDF, Go, and CircleCI workflows to improve caching mechanism
> 🎉 Cache updates are here, hooray! 🥳
> With keys refreshed, we're on our way. 🚀
> ASDF, Go, and CircleCI too, 🔄
> Our workflow's swift, our cache anew! 💨
> Invalidate caches

- .vscode/ltex.dictionary.en-US.txt
- operator/main.go
- Improved spelling consistency in the dictionary file
- Updated comment capitalization for better readability
> 🎉 Hooray for consistency, we've made it right! 📚
> With words spelled well and comments bright. ✨
> A small but meaningful change, indeed, 🌟
> To make our codebase easier to read. 📖
> codespell: ignore words

- .github/styles/Vocab/FluxNinja/accept.txt
- .github/workflows/languagetool.yaml
- test.md
> langaugetool settings

- .github/workflows/languagetool.yaml
- test.md
@openai: ignore 
**Chore:**
- Updated LanguageTool GitHub action configuration for improved filtering and API usage
- Introduced a grammatical error in `test.md` for demonstration purposes
> 🎉 A change so grand, we've made our stand,
> With LanguageTool in hand, our grammar shall expand! 📚
> languagetool: update action

- blueprints/blueprint-assets-generator.py
- docs/content/reference/policies/bundled-blueprints/dashboards/signals.md
- docs/content/reference/policies/bundled-blueprints/policies/feature-rollout/average-latency.md
- docs/content/reference/policies/bundled-blueprints/policies/feature-rollout/base.md
- docs/content/reference/policies/bundled-blueprints/policies/feature-rollout/ema-latency.md
- docs/content/reference/policies/bundled-blueprints/policies/feature-rollout/percentile-latency.md
- docs/content/reference/policies/bundled-blueprints/policies/feature-rollout/promql.md
- docs/content/reference/policies/bundled-blueprints/policies/latency-aimd-concurrency-limiting.md
- docs/content/reference/policies/bundled-blueprints/policies/rabbitmq-queue-buildup.md
- docs/content/reference/policies/bundled-blueprints/policies/static-rate-limiting.md
> blueprints: tweak doc rendering

- blueprints/blueprint-assets-generator.py
- blueprints/policies/feature-rollout/average-latency/gen/values-required.yaml
- blueprints/policies/feature-rollout/average-latency/gen/values.yaml
- blueprints/policies/feature-rollout/base/gen/values-required.yaml
- blueprints/policies/feature-rollout/base/gen/values.yaml
- blueprints/policies/feature-rollout/ema-latency/gen/values-required.yaml
- blueprints/policies/feature-rollout/ema-latency/gen/values.yaml
- blueprints/policies/feature-rollout/percentile-latency/gen/values-required.yaml
- blueprints/policies/feature-rollout/percentile-latency/gen/values.yaml
- blueprints/policies/feature-rollout/promql/gen/values-required.yaml
- blueprints/policies/feature-rollout/promql/gen/values.yaml
**Bug fix:**
- Improved array rendering in blueprint assets generator
> 🎉 Array rendering, now so fine,
> Iterables checked, in every line.
> Indentation fixed, with great care,
> Our blueprint generator, now more fair! 🚀
> blueprints: improve rendering of arrays

- .github/styles/Vocab/FluxNinja/accept.txt
- blueprints/blueprint-assets-generator.py
- docs/content/parameterComponents.js
- docs/content/reference/policies/bundled-blueprints/dashboards/signals.md
- docs/content/reference/policies/bundled-blueprints/policies/feature-rollout/average-latency.md
- docs/content/reference/policies/bundled-blueprints/policies/feature-rollout/base.md
- docs/content/reference/policies/bundled-blueprints/policies/feature-rollout/ema-latency.md
- docs/content/reference/policies/bundled-blueprints/policies/feature-rollout/percentile-latency.md
- docs/content/reference/policies/bundled-blueprints/policies/feature-rollout/promql.md
- docs/content/reference/policies/bundled-blueprints/policies/latency-aimd-concurrency-limiting.md
- docs/content/reference/policies/bundled-blueprints/policies/rabbitmq-queue-buildup.md
- docs/content/reference/policies/bundled-blueprints/policies/static-rate-limiting.md
- Render default values as YAML in blueprint and policy documentation
- Update parameter descriptions and formatting for consistency
> 🎉 YAML shines bright, like stars in the night 🌟<br>
> Documentation now clear, users can cheer! 🥳<br>
> With values displayed, confusion's allayed 📚<br>
> A better experience, we've surely gained! 🚀
> blueprints: render default values as yaml in docs

- .tool-versions
- api/buf.lock
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/FlowControlServiceGrpc.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/checkhttp/v1/FlowControlServiceHTTPGrpc.java
> pre_commit: regenerate proto

- playground/scenarios/auto_scaling/load_generator/test.js
- playground/scenarios/demo-app-with-no-policy/load_generator/test.js
- playground/scenarios/feature_rollout/load_generator/test.js
- playground/scenarios/graphql_query_static_rate_limiting/load_generator/test.js
- playground/scenarios/rabbitmq_queue_buildup/load_generator/test.js
- playground/scenarios/rate_limiting_escalation/load_generator/test.js
- playground/scenarios/rate_limiting_escalation_kong/load_generator/test.js
- playground/scenarios/rate_limiting_escalation_nginx/load_generator/test.js
- Added randomization and sleep functionality to load generation logic in multiple scenarios.
> 🎉 A touch of randomness, a moment's rest, 🛌<br>
> Load generation now performs at its best. 🚀<br>
> With every scenario, we strive to improve, 📈<br>
> Our code evolves, as we continue to move. 🏃‍♂️💨
> playground: add back imports

- cmd/aperture-agent/agent/otel-component.go
- cmd/sdk-validator/README.md
- cmd/sdk-validator/main.go
- cmd/sdk-validator/validator/provide.go
- extensions/fluxninja/extconfig/extconfig.go
- extensions/fluxninja/heartbeats/heartbeats.go
- operator/config/crd/bases/fluxninja.com_agents.yaml
- operator/config/crd/bases/fluxninja.com_controllers.yaml
- pkg/agentfunctions/config/config.go
- pkg/agentfunctions/preview.go
- pkg/net/grpc/client.go
- pkg/net/grpc/server.go
- pkg/policies/flowcontrol/service/check/provide.go
- pkg/policies/flowcontrol/service/checkhttp/provide.go
- pkg/policies/flowcontrol/service/envoy/provide.go
- sdks/aperture-go/README.md
- sdks/aperture-go/example/main.go
- sdks/aperture-java/javaagent/README.md
- sdks/aperture-py/example/main.py
- Fixed typos related to "gRPC" in comments, log messages, and documentation across various files for improved consistency and readability.
> 🎉 Oh gRPC, your name now shines bright,
> Consistency restored, we've set it right.
> From comments to logs, and docs we've been through,
> A celebration of clarity, this PR's for you! 🥳
> fix typo gRPC

- .github/styles/Vocab/FluxNinja/accept.txt
- **Chore**: Updated `.github/styles/Vocab/FluxNinja/accept.txt` with new words to expand the accepted vocabulary for the project.
> 🎉 A pull request so grand,
> New words now join our band.
> LinkedIn, Nutanix, Zalando too,
> Our vocab grows, it's true! 📚✨
> add accepted words for aperture-tech-docs repo

- .circleci/scripts/asdf_install.sh
**Chore:**
- Removed `graphviz` package installation from CircleCI configuration script
- Updated Python installation process in CircleCI configuration script
> 🎉 Oh, rejoice and celebrate! 🥳
> For the changes we've made are truly great.
> No more `graphviz`, we're feeling fine,
> With Python updates, our code will shine! ✨
> remove redundant packages from asdf install step

- docs/content/get-started/installation/controller/namespace-scoped/namespace-scoped.md
- Removed redundant paragraph in `namespace-scoped.md` for better clarity
> 🎉 A paragraph gone, the docs now shine,
> With clarity improved, the change is divine.
> 📚 Our users rejoice, their path now clear,
> Embracing the update, they all cheer! 🥳
> remove redundant para

- .circleci/config.yml
- .circleci/continue-workflows.yml
- .circleci/post-release.yaml
- Chore: Updated CircleCI workflow and executors, including adding a new Python executor, updating executor images, and altering step order for improved build performance.
> 🎉 A CircleCI update we bring,
> With Python executors taking wing. 🐍
> Executor images now shine bright,
> And altered steps make builds take flight! ✨
> Use python CircleCI executor where python is used

- cmd/aperturectl/cmd/installation/utils.go
**Bug fix:**
- Improved error handling for forbidden errors in installation utils
- Corrected error messages for better clarity
- Added check for empty endpoints before fetching the controller client certificate
> 🎉 Oh, rejoice and celebrate! 🥳
> For we've squashed bugs, no more to wait. 🐛
> Error handling now refined, ✨
> And clearer messages we shall find. 📜
> With endpoints checked, we're feeling great! 🚀
> Corrected error messages for namespace scoped installation

- .circleci/continue-workflows.yml
- sdks/aperture-go/example/main.go
- sdks/aperture-go/sdk/client.go
- Check if timeout is 0, then use the given context. Otherwise, construct a new context with given timeout.
- Refactor middleware function
- Format code
**Refactor:**
- Improved middleware function in `sdks/aperture-go/example/main.go` and `sdks/aperture-go/sdk/client.go`
- Enhanced context handling with timeout checks and context construction
- Code formatting updates
> 🎉 Middleware's now refined, 🛠️
> Contexts checked, aligned. 🌟
> With formatting neat, 📝
> This PR's quite a treat! 🍬
> Respect request context

- .circleci/continue-workflows.yml
**Optimization**: Improved CircleCI pipeline performance
- Added remote Docker environment setup and layer caching
- Modified the executor used in a pipeline job
**New Feature**: Added `FLOW_STATUS_SUCCESS` constant to Aperture Java SDK
- Introduced a new constant in the `Constants` class
> 🎉 A pipeline optimized, so swift and neat,
> New constants added, making our code complete.
> With every change, we strive for the best,
> Our software evolves, never at rest. 🚀
> Added docker in SDK pipelines

- go.mod
- operator/controllers/agent/hook.go
- operator/controllers/controller/hook.go
- pkg/net/grpcgateway/grpcgateway.go
- pkg/policies/controlplane/circuitfactory/flow-control-components.go
- Added backward compatibility checks for older default addresses
- Updated field mappings for component conversion
> 🎉 A step back in time we take, 🕰️
> To ensure compatibility we make. 🛠️
> Field mappings now renewed, 🔄
> For a future that's well-reviewed. 🌟
> Made the gateway address change backward compatible

- docs/content/get-started/integrations/flow-control/gateway/kong.md
- docs/content/get-started/integrations/flow-control/gateway/nginx.md
- gateways/lua/aperture-plugin/access.lua
- gateways/lua/kong/handler.lua
- gateways/lua/kong/schema.lua
- playground/resources/kong/kong.yaml
- playground/resources/nginx/nginx_config.conf
- playground/scenarios/rate_limiting_escalation_kong/policies/service1-demo-app-cr.yaml
- playground/scenarios/rate_limiting_escalation_kong/policies/service1-demo-app.yaml
- playground/scenarios/rate_limiting_escalation_nginx/policies/service1-demo-app-cr.yaml
- playground/scenarios/rate_limiting_escalation_nginx/policies/service1-demo-app.yaml
Nginx:
Kong:
- Added a configurable control point for the Aperture plugin in Kong and Nginx, enhancing flexibility for users.
> 🎉 A new feature takes the stage,
> Configurable control points engage.
> Kong and Nginx now unite,
> With flexibility taking flight. 🚀
> Made the control point configurable in gateways integration

- manifests/charts/istioconfig/README.md
- manifests/charts/istioconfig/templates/envoy_filter.yaml
- manifests/charts/istioconfig/values.yaml
- playground/tanka/apps/istio/mixins.libsonnet
- Added workload selection and control points for inbound and outbound requests in Istio EnvoyFilter
> 🎉 A new dawn for Istio, we cheer! 🥳
> Workload selection now is here. 🚀
> Inbound and outbound, we control, 🌐
> With this PR, we're on a roll! 💫
> Made control point configurable and added workload selector in Istio EnvoyFilter

- .pre-commit-config.yaml
> pre-commit: use markdownlint binary

- .circleci/continue-workflows.yml
- docs/content/concepts/policy/policy.md
> provide large machine for docs

- .github/workflows/languagetool.yaml
> re-add languagetool action

- .github/styles/Vocab/FluxNinja/accept.txt
> add Interdependencies word

- .github/styles/Vocab/FluxNinja/accept.txt
- .github/workflows/languagetool.yaml
- .github/workflows/openai-review.yml
- .github/workflows/vale.yml
Remove/add words to accept.txt
- Refactor: Updated `accept.txt` file in FluxNinja vocabulary style
- Removed and added words
- Modified regular expressions
> 🎉 A change so small, yet profound,
> In the realm of words, we're unbound.
> Regex shifts, a new dance,
> FluxNinja's vocab, enhanced! 📚
> update vale dict

- .github/workflows/languagetool.yaml
- .github/workflows/openai-review.yml
- .github/workflows/vale.yml
- languetool
- openai-reviewer
- vale
**Chore:**
- Updated GitHub workflows to trigger on `pull_request` instead of `pull_request_target`
- Modified concurrency group and added branch filter in `openai-review.yml`
> 🎉 Oh, the workflows we've refined,
> With triggers and filters aligned! 🚀
> Concurrency groups now set,
> A smoother CI, you bet! ✨
> Update GitHub workflows

- docs/content/arc/arc.md
```
Documentation:
- Updated URL in FluxNinja ARC documentation
```
> 🌐 A link once broken, now restored,
> In the docs of FluxNinja, we move forward.
> With every change, big or small,
> We strive to make it better for all. 🎉
> update url to product

- .circleci/continue-workflows.yml
- docs/tools/aperturectl/validate_all.sh
- docs/tools/jsonnet/generate_jsonnet.sh
- docs/tools/mermaid/generate_mermaid.sh
- scripts/build_aperturectl.sh
- scripts/generate_blueprints.sh
- scripts/go_build.sh
- scripts/go_build_plugins.sh
- scripts/go_generate.sh
- scripts/go_generate_swagger.sh
- scripts/go_mod_tidy.sh
- scripts/precommit/generate_playground_policies.sh
- scripts/precommit/install_tools.sh
- Added `--force-build` option to build script for `aperturectl`
**Optimization:**
- Increased parallel jobs from 4 to 8 in various scripts and configuration files
> 🎉 A forceful build, we now embrace,
> With parallel jobs, we pick up the pace.
> Optimized and ready, our code takes flight,
> Celebrate these changes, both day and night! 🚀
> use cached aperturectl

- blueprints/dashboards/signals/config.libsonnet
- blueprints/dashboards/signals/dashboard.libsonnet
- blueprints/dashboards/signals/gen/definitions.json
- blueprints/dashboards/signals/gen/values-required.yaml
- blueprints/dashboards/signals/gen/values.yaml
- docs/content/reference/policies/assets/monitoring/signals-dashboard.json
- docs/content/reference/policies/bundled-blueprints/dashboards/signals.md
- Updated function signature and configuration object in dashboard blueprints
- Modified IDs and names of elements in policy dashboard documentation
> 🎉 A new dawn for dashboards, we greet,
> With updated code, our goals to meet.
> In docs and configs, changes we sow,
> For better user experience, we bestow. 🌟
> fix signals dashboard

- cmd/aperture-agent/Dockerfile
- cmd/aperture-controller/Dockerfile
- scripts/build_aperturectl.sh
- scripts/install_go_tools.sh
> always build aperturectl

- playground/resources/java-demo-app/src/main/java/com/javademoapp/javademoapp/RequestController.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java
Also remove unused java SDK additions
```
Refactor:
- Remove unused endpoints in Java demo app
- Remove unused Java SDK addition
- Move `apertureFeatureFilter` method to the end of the class
- Remove unused `addBaggage` method and its dependencies
```
> 🎉 Unused code, now it's gone,
> 🧹 Sweeping clean, we carry on.
> 🚀 Refactored, lean and tight,
> ✨ Our codebase shines so bright.
> Remove unused endpoints from java demo app

- blueprints/policies/auto-scaling/base/README.md
- blueprints/policies/auto-scaling/base/config-defaults.libsonnet
- blueprints/policies/auto-scaling/base/dashboard.libsonnet
- blueprints/policies/auto-scaling/base/dynamic-config.libsonnet
- blueprints/policies/auto-scaling/base/policy.libsonnet
- blueprints/policies/auto-scaling/pod-auto-scaler/README.md
- blueprints/policies/auto-scaling/pod-auto-scaler/bundle.libsonnet
- blueprints/policies/auto-scaling/pod-auto-scaler/config.libsonnet
- blueprints/policies/auto-scaling/pod-auto-scaler/dashboard.libsonnet
- blueprints/policies/auto-scaling/pod-auto-scaler/dynamic-config.libsonnet
- blueprints/policies/auto-scaling/pod-auto-scaler/gen/definitions.json
- blueprints/policies/auto-scaling/pod-auto-scaler/gen/dynamic-config-definitions.json
- blueprints/policies/auto-scaling/pod-auto-scaler/gen/dynamic-config-values-required.yaml
- blueprints/policies/auto-scaling/pod-auto-scaler/gen/dynamic-config-values.yaml
- blueprints/policies/auto-scaling/pod-auto-scaler/gen/values-required.yaml
- blueprints/policies/auto-scaling/pod-auto-scaler/gen/values.yaml
- blueprints/policies/auto-scaling/pod-auto-scaler/metadata.yaml
- blueprints/policies/auto-scaling/pod-auto-scaler/pod-auto-scaler.libsonnet
- blueprints/policies/auto-scaling/pod-auto-scaler/policy.libsonnet
- blueprints/policies/policies.libsonnet
- docs/content/reference/policies/bundled-blueprints/policies/auto-scaling/auto-scaling.md
- docs/content/reference/policies/bundled-blueprints/policies/auto-scaling/pod-auto-scaler.md
- docs/content/reference/policies/bundled-blueprints/policies/service-protection/service-protection.md
- docs/content/reference/policies/bundled-blueprints/policies/static-rate-limiting.md
Fixes #1647 
- Added auto-scaling module with default values, Grafana dashboard, and PodAutoScaler blueprint
- Created new documentation files for auto-scaling blueprints and updated sidebar positions
**Refactor:**
- Updated `policies.libsonnet` to import `PodAutoScaler`
> 🎉 Auto-scaling takes the stage, 🚀
> A new feature we proudly engage. 🌟
> With docs and code refined, ✍️
> Our users' needs in mind. 💡
> Let's celebrate this milestone, 🥳
> As our software further has grown! 📈
> Blueprint for Auto-scale

- playground/resources/java-demo-app/src/main/java/com/javademoapp/javademoapp/ApertureFeatureFilter.java
- playground/resources/java-demo-app/src/main/java/com/javademoapp/javademoapp/JavaDemoAppApplication.java
- playground/resources/java-demo-app/src/main/java/com/javademoapp/javademoapp/RequestController.java
- playground/resources/java-demo-app/src/main/java/com/javademoapp/javademoapp/Subrequest.java
- playground/scenarios/java_rate_limiting_escalation/load_generator/test.js
```
New Feature:
- Added request destination check in RequestController
Refactor:
- Minor variable modifications in RequestController
Style:
- Code formatting and import reordering in ApertureFeatureFilter, JavaDemoAppApplication, and Subrequest
Test:
- Updated load testing configuration in test.js
```
> 🎉 A new check we've brought to light,
> Ensuring our requests take flight.
> With code refined and tests updated,
> Our app's performance is elevated. 🚀
> Improvements in Java demoapp

- blueprints/policies/auto-scaling/base/policy.libsonnet
```
New Feature:
- Updated auto-scaling blueprints with new gradient libraries
- Replaced `GradientController` with `IncreasingGradient` and `DecreasingGradient`
- Adjusted input ports accordingly
```
> 🎉 A change so grand, we must celebrate,
> New gradients in place, auto-scale's fate.
> With increasing, decreasing, the system thrives,
> Our code now evolves, like bees in their hives. 🐝
> Updated specific gradient libraries in auto-scaling blueprints

- blueprints/dashboards/signals/dashboard.libsonnet
- docs/content/reference/policies/assets/monitoring/signals-dashboard.json
> Update titles in signals dashboard

- docs/content/get-started/policies/policies.md
```
Documentation:
- Updated policy list in `docs/content/get-started/policies/policies.md`
```
> 🎉 A new dawn for policies, we see,
> With fresh updates, our docs now agree.
> 📚 Knowledge grows, as changes appear,
> Embrace the shift, and have no fear. 🌟
> update output: aperturectl blueprint list

- cmd/aperturectl/cmd/installation/utils.go
**Refactor:**
- Updated `getTemplets` function to handle `isNamespaceScoped` differently for `controller` and `agent`
- Enhanced error message in `applyObjectToKubernetesWithRetry` function for better failure information
> 🎉 A refactor we did make,
> To improve the code we take.
> With better scope and clearer errors,
> Our progress soars like birds with feathers. 🦅
> Fixed aperturectl install istioconfig

- cmd/aperturectl/cmd/blueprints/common.go
- cmd/aperturectl/cmd/blueprints/dynamic-values.go
- cmd/aperturectl/cmd/blueprints/globals.go
- cmd/aperturectl/cmd/blueprints/root.go
- cmd/aperturectl/cmd/blueprints/values.go
- cmd/aperturectl/cmd/installation/utils.go
- docs/content/get-started/policies/policies.md
- docs/content/reference/aperturectl/blueprints/blueprints.md
- docs/content/reference/aperturectl/blueprints/dynamic-values/dynamic-values.md
> Cherry-picked changes for release v2.1.1-rc.2

- go.mod
- go.sum
- pkg/policies/controlplane/validator_test.go
- pkg/policies/flowcontrol/actuators/rate/ratetracker/rate-tracker_test.go
- playground/scenarios/java_rate_limiting_escalation/policies/rate-limit-escalation-cr.yaml
- playground/scenarios/java_rate_limiting_escalation/policies/rate-limit-escalation.yaml
- playground/scenarios/rate_limiting_escalation/policies/service1-demo-app-cr.yaml
- playground/scenarios/rate_limiting_escalation/policies/service1-demo-app.yaml
- playground/scenarios/rate_limiting_escalation_kong/policies/service1-demo-app-cr.yaml
- playground/scenarios/rate_limiting_escalation_kong/policies/service1-demo-app.yaml
- playground/scenarios/rate_limiting_escalation_nginx/policies/service1-demo-app-cr.yaml
- playground/scenarios/rate_limiting_escalation_nginx/policies/service1-demo-app.yaml
- Updated rate limit policies with `DESIRED_LOAD_MULTIPLIER` signal
- Enhanced OlricLimiter functionality and added cluster support
**Test:**
- Added two test cases for OlricLimiter cluster behavior
> 🎉 A new dawn breaks, the limits we reshape,
> With clusters strong, our OlricLimiter takes shape.
> DESIRED_LOAD_MULTIPLIER, a signal so fine,
> Together we celebrate, this PR's code divine. 🚀
> playground: update rate limit policies

- docs/content/concepts/flow-control/flow-control.md
- docs/content/get-started/integrations/flow-control/flow-control.md
also including this pr changes https://github.com/fluxninja/aperture/pull/1935
- Added integration with API gateways (Kong, NGINX) in documentation
- Updated introductory paragraph in flow-control.md
- Described Aperture Agent's traffic management processes
> 🎉 A gateway to manage the flow,
> With Kong and NGINX, we're good to go.
> Aperture Agent takes the stage,
> In our docs, a brand new page! 📖
> update and add gateway section

- docs/content/architecture/architecture.md
- docs/content/reference/policies/assets/monitoring/signals-dashboard.json
- Remove AIMD & PID Message as suggested by Harjot
- Simplify Controller Description
- Mention any signal instead of only golden signals
- Simplified Aperture Controller description
- Removed AIMD and PID message details
- Updated signal handling to include any signal, not just golden signals
- Added flow control and graceful degradation information
> 🎉 A clearer path we've paved today,
> With docs refined in every way.
> Signals broadened, flow controlled,
> Graceful degradation stories told. 🚀
> Rework Docs Architecture page

- docs/content/get-started/integrations/flow-control/sdk/javascript/manual.md
- sdks/aperture-js/example/routes/use_aperture.js
- sdks/aperture-js/package.json
- sdks/aperture-js/sdk/client.js
- sdks/aperture-js/sdk/consts.js
- sdks/aperture-js/sdk/flow.js
- Added `FlowResult` constant and updated `Flow` class to use it
- Implemented timeout for check requests in `ApertureClient`
- Updated example code in the JavaScript SDK manual
> 🎉 A new era dawns, with FlowResult in hand,
> Timed checks now stand, as Aperture expands. 🚀
> Aperture JS SDK changes

- docs/content/applying-policies/quota-scheduler/with-external-api-calls-prioritization.md
```
Documentation:
- Fixed broken links in Quota Scheduler documentation
```
> 🎉 Broken links no more, our docs restored! 📚
> With paths corrected, knowledge shall be explored. 🌐
> In Quota Scheduler's land, users now can stride, 🚶‍♂️
> Confident and clear, with guidance by their side. 🌟
> fix broken link

- docs/Makefile
- docs/content/integrations/flow-control/sdk/java/armeria.md
- docs/content/integrations/flow-control/sdk/java/netty.md
- docs/tools/mermaid/generate_all.sh
- docs/tools/mermaid/generate_mermaid.sh
- docs/tools/otel_collectors/generate_otel_docs.sh
- Updated URLs in Armeria and Netty integration documentation
**Refactor:**
- Modified Mermaid diagram generation scripts for better decoupling
- Updated `generate_otel_docs.sh` script with improved file handling and formatting
> 🎉 A PR so fine, it makes our docs shine! 🌟
> With Mermaid diagrams refined, 🧜‍♀️
> And OpenTelemetry docs aligned. 📚
> Celebrate the changes, oh so grand, 🥳
> For they make our project truly well-planned! 🚀
> decouple mermaid image generator

- docs/content/introduction.md
- Updated introduction documentation for FluxNinja Aperture project
> 🎉 A new dawn for FluxNinja's tale,
> With an intro that's clear and never stale.
> For devs, engineers, and those who care,
> The updated docs are now laid bare. 📚
> fix introduction doc

- .github/styles/Vocab/FluxNinja/accept.txt
- docs/content/get-started/installation/agent/agent.md
- docs/content/get-started/installation/agent/docker.md
- docs/content/get-started/installation/controller/controller.md
- docs/content/get-started/installation/controller/docker.md
- docs/content/get-started/installation/controller/kubernetes/kubernetes.md
- docs/content/get-started/installation/controller/kubernetes/namespace-scoped/namespace-scoped.md
- docs/content/get-started/installation/controller/kubernetes/operator/operator.md
- Updated Aperture Agent and Aperture Controller installation instructions
- Added Docker installation option for Aperture Agent
- Exposed etcd and Prometheus services in the installation process
- Fixed import paths in Kubernetes installation documentation
**Style:**
- Updated regex pattern in `.github/styles/Vocab/FluxNinja/accept.txt`
> 🎉 A new way to install, with Docker we trust,
> 🚀 Aperture Agent, now robust and just.
> 🌐 Exposing services, etcd and Prometheus,
> 📚 Documentation fixed, our path to success.
> Added installation docs for Aperture on Docker

- docs/content/applying-policies/quota-scheduler/quota-scheduler.md
```
Documentation:
- Updated sidebar label in quota-scheduler.md from "Quota Scheduler" to "Quota Scheduling"
```
> 🎉 A simple change we've made today,
> In docs, a word swap's underway.
> From "Scheduler" to "Scheduling" we glide,
> For clarity's sake, we take this stride. 📚
> update sidebar top level heading

- docs/content/introduction.md
- Updated introduction section in `introduction.md`
- Modified list of load management capabilities
- Added hyperlinks to relevant sections
- Updated list of features with bullet points
- Added emojis to headings
> 🎉 A fresh new look, we've made some tweaks,
> To our docs, where knowledge seekers peek.
> With updated features and links that shine,
> Our introduction's now polished and fine. 🌟
> update introduction with new description

- docs/content/integrations/flow-control/sdk/go/manual.md
- docs/content/integrations/flow-control/sdk/java/armeria.md
- docs/content/integrations/flow-control/sdk/java/manual.md
- docs/content/integrations/flow-control/sdk/java/netty.md
- docs/content/integrations/flow-control/sdk/java/springboot.md
- docs/content/integrations/flow-control/sdk/java/tomcat.md
- docs/content/integrations/flow-control/sdk/sdk.md
- Updated links to example apps in various SDK documentation files
- Added new sections for middleware in SDK documentation
**Chore:**
- Updated title and sidebar label of a documentation page
- Modified PR description checklist
> 🎉 A new dawn for our docs, we cheer,
> Middleware sections now appear.
> Links updated, examples shine bright,
> Our users' journey takes flight. ✈️
> update sampe app links and add middleware section

- docs/content/integrations/flow-control/sdk/java/armeria.md
- docs/content/integrations/flow-control/sdk/java/auto-instrumentation.md
- docs/content/integrations/flow-control/sdk/java/manual.md
- docs/content/integrations/flow-control/sdk/java/netty.md
- docs/content/integrations/flow-control/sdk/java/springboot.md
- docs/content/integrations/flow-control/sdk/java/tomcat.md
- Updated links to example apps and specific files in the repository for various Java SDK integrations
- Added a download link for the Aperture Instrumentation Agent JAR file in `auto-instrumentation.md`
- Updated priority order for configuration lookup in `auto-instrumentation.md`
- Removed redundant download link in `auto-instrumentation.md`
> 🎉 A new release is here, with docs refined,
> Links updated, and clarity combined.
> The JAR file's ready, just one click away,
> Configuration improved, without delay. 🚀
> update with code links

- docs/content/applying-policies/applying-policies.md
- docs/content/applying-policies/quota-scheduler/external-rate-limiting.md
- docs/content/introduction.md
- Updated title and description in applying-policies.md and introduction.md for better focus on use cases and added new keywords
- Modified policy description in external-rate-limiting.md for improved clarity and readability
> 🎉 A clearer path we pave today,
> With words refined, we're here to say,
> Our docs now shine with purpose bright,
> To guide our users through the night. 🌟
> Update applying policies doc

- docs/content/get-started/setting-up-application/service-mesh-and-gateways.md
```
Documentation:
- Fixed typo in PR title and throughout the document, changing "API Getaways" to "API Gateways"
```
> 🎉 API Gateways, no more delays,
> 📚 Documentation now displays,
> ✅ The right term, we've come a long way,
> 🌐 Connecting services, here to stay!
> fix a typo

- pkg/rate-limiter/global-token-bucket/global-token-bucket.go
- Added `Deadline` field to `takeNRequest` struct in global-token-bucket
- Implemented deadline-based rejection for token requests exceeding wait time
> 🎉 A deadline we set, to keep things fair,
> ⏰ No more waiting, when tokens are rare.
> 🚀 With global token bucket's new might,
> ✨ Our rate limiter shines ever so bright!
> global token bucket: decide based on deadline

- docs/content/get-started/setting-up-application/manual-control-points.md
- docs/content/get-started/setting-up-application/middleware-insertions.md
- docs/content/get-started/setting-up-application/service-mesh-and-gateways.md
- docs/content/introduction.md
- playground/scenarios/quota-scheduler/policies/quota-scheduler-cr.yaml
- playground/scenarios/quota-scheduler/policies/quota-scheduler.yaml
Remove custom cards in Docusaurus.
- Simplified Docusaurus custom card components in various documentation files, replacing them with links or simpler lists for better readability.
> 🎉 Hooray for simplicity, we've made a stride,
> Removing custom cards, with links by our side.
> Docs now more readable, a change we embrace,
> Celebrate this PR, as clarity takes place! 📚
> docs: remove Cards

- README.md
- docs/tools/mermaid/generate_all.sh
Fix the mermaid generation script.
```
Documentation:
- Updated feature description in README.md
- Fixed script path in generate_all.sh
```
> 🎉 A small change, yet so grand,
> In docs and scripts, we understand.
> With clarity now, our paths align,
> This update shines, oh so divine! 🌟
> docs: fix mermaid generation script

- api/buf.gen.aperture-grpc-ecosystem.yaml
- api/buf.lock
- pkg/dist-cache/provider.go
- pkg/dist-cache/service-discovery.go
- playground/scenarios/quota-scheduler/policies/quota-scheduler-cr.yaml
- playground/scenarios/quota-scheduler/policies/quota-scheduler.yaml
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/CheckRequest.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/CheckResponse.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/ClassifierInfo.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/FluxMeterInfo.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/LimiterDecision.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/checkhttp/v1/CheckHTTPRequest.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/checkhttp/v1/CheckHTTPResponse.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/checkhttp/v1/DeniedHttpResponse.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/checkhttp/v1/OkHttpResponse.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/checkhttp/v1/SocketAddress.java
> Cherry-picked changes for release v2.3.3-rc.1

- .circleci/continue-workflows.yml
- sdks/aperture-java/dockerfiles/aperture-java-all/Dockerfile
- sdks/aperture-java/dockerfiles/trafficflow/Dockerfile
- sdks/aperture-java/examples/standalone-traffic-flow-example/build.gradle.kts
- sdks/aperture-java/examples/standalone-traffic-flow-example/src/main/java/com/fluxninja/example/App.java
- sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPClient.java
- sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPService.java
- sdks/aperture-java/lib/armeria/src/main/java/com/fluxninja/aperture/armeria/HttpUtils.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/TrafficFlowRequest.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/TrafficFlowRequestBuilder.java
- sdks/aperture-java/lib/netty/src/main/java/com/fluxninja/aperture/netty/ApertureServerHandler.java
- sdks/aperture-java/lib/netty/src/main/java/com/fluxninja/aperture/netty/NettyUtils.java
- sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ApertureFilter.java
- sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/jakarta/ServletUtils.java
- sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ApertureFilter.java
- sdks/aperture-java/lib/servlet/src/main/java/com/fluxninja/aperture/servlet/javax/ServletUtils.java
- sdks/aperture-java/settings.gradle.kts
- Added Traffic Flow Builder and standalone example
- Integrated Traffic Flow Request into existing SDK components
**Refactor:**
- Replaced CheckHTTPRequest with TrafficFlowRequest in various classes
> 🚀 A new feature takes flight, 🌟
> Traffic flows now shining bright. ✨
> With builders strong and examples clear, 🏗️
> Our SDK evolves, bringing cheer! 🎉
> Add traffic flow builder and traffic flow example

- blueprints/policies/auto-scaling/base/dashboard.libsonnet
- blueprints/policies/rate-limiting/dashboard.libsonnet
- blueprints/policies/service-protection/base/dashboard.libsonnet
- blueprints/policies/service-protection/jmx/README.md
- blueprints/policies/service-protection/jmx/bundle.libsonnet
- blueprints/policies/service-protection/jmx/config.libsonnet
- blueprints/policies/service-protection/jmx/dashboard.libsonnet
- blueprints/policies/service-protection/jmx/dynamic-config.libsonnet
- blueprints/policies/service-protection/jmx/gen/definitions.json
- blueprints/policies/service-protection/jmx/gen/dynamic-config-definitions.json
- blueprints/policies/service-protection/jmx/gen/dynamic-config-values-required.yaml
- blueprints/policies/service-protection/jmx/gen/dynamic-config-values.yaml
- blueprints/policies/service-protection/jmx/gen/values-required.yaml
- blueprints/policies/service-protection/jmx/gen/values.yaml
- blueprints/policies/service-protection/jmx/jmx.libsonnet
- blueprints/policies/service-protection/jmx/metadata.yaml
- blueprints/policies/service-protection/jmx/policy.libsonnet
- docs/content/reference/policies/bundled-blueprints/policies/service-protection/jmx.md
- playground/resources/java-demo-app/src/main/java/com/javademoapp/javademoapp/RequestController.java
- playground/scenarios/java-jmx-based-service-protection/dashboards/main.jsonnet
- playground/scenarios/java-jmx-based-service-protection/load-generator/test.js
- playground/scenarios/java-jmx-based-service-protection/metadata.json
- playground/scenarios/java-jmx-based-service-protection/policies/jmx-service-protection-cr.yaml
- playground/scenarios/java-jmx-based-service-protection/policies/jmx-service-protection.yaml
- playground/scenarios/java-jmx-based-service-protection/values.yaml
- playground/scenarios/java-service-protection/policies/service-protection-cr.yaml
- playground/scenarios/java-service-protection/policies/service-protection.yaml
- playground/tanka/apps/java-demo-app/mixins.libsonnet
- playground/tanka/charts/java-demo-app/templates/deployment.yaml
- playground/tanka/charts/java-demo-app/values.yaml
```
New Feature:
- Added CPU stress simulation option to Java demo app
- Implemented JMX overload confirmation policy and dashboard
Bug fix:
- Fixed typos in dashboard panel configurations
```
> 🎉 A new feature we bring, with stress tests to sing,
> JMX policies take flight, as dashboards shine bright.
> Typos fixed, panels aligned, a better experience you'll find. 🚀
> Add policy for jmx overload confirmation

- api/aperture/policy/language/v1/policy.proto
- api/buf.lock
- api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
- docs/content/assets/openapiv2/aperture-controller.swagger.yaml
- docs/content/assets/openapiv2/aperture.swagger.yaml
- tools/go/go.mod
- tools/go/go.sum
Fix API docs generation
@openai: ignore
> docs: fix controller API docs

- blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency/README.md
- blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency/average-latency.libsonnet
- blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql/README.md
- blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql/promql.libsonnet
- Added imports for configuration, policy, dashboard, and bundle files in jsonnet files to improve service protection with load-based pod auto-scaler
> 🎉 A new dawn rises, code weaves its tale,
> With imports added, our service shall not fail.
> Scaling pods with grace, as the load does grow,
> A better future awaits, this PR does show. 🚀
> Fixed auto scaling with service protection blueprints for use in jsonnet

- blueprints/blueprint-assets-generator.py
- blueprints/policies/auto-scaling/pod-auto-scaler/gen/values.yaml
- blueprints/policies/feature-rollout/average-latency/gen/values.yaml
- blueprints/policies/feature-rollout/base/gen/values-required.yaml
- blueprints/policies/feature-rollout/base/gen/values.yaml
- blueprints/policies/feature-rollout/ema-latency/gen/values.yaml
- blueprints/policies/feature-rollout/percentile-latency/gen/values.yaml
- blueprints/policies/feature-rollout/promql/gen/values.yaml
- blueprints/policies/quota-scheduler/gen/values-required.yaml
- blueprints/policies/quota-scheduler/gen/values.yaml
- blueprints/policies/rate-limiting/gen/values.yaml
- blueprints/policies/service-protection-with-load-based-pod-auto-scaler/average-latency/gen/values.yaml
- blueprints/policies/service-protection-with-load-based-pod-auto-scaler/promql/gen/values.yaml
- blueprints/policies/service-protection/average-latency/gen/values.yaml
- blueprints/policies/service-protection/jmx/gen/values.yaml
- blueprints/policies/service-protection/promql/gen/values.yaml
- docs/content/get-started/policies/assets/raw_values.yaml
**Bug fix:**
- Prevent rendering empty mappings in blueprint assets generator
> 🎉 No more empty maps, we've fixed the lapse,
> A cleaner blueprint, no unnecessary gaps! 🚀
> Fix blueprint defaults for maps

- api/buf.lock
- docs/content/concepts/flow-control/selector.md
- docs/content/integrations/gateway/gateway.md
- docs/content/integrations/gateway/nginx.md
- gateways/lua/aperture-plugin/access.lua
- gateways/lua/aperture-plugin/headers.lua
- gateways/lua/aperture-plugin/log.lua
- gateways/lua/kong/handler.lua
- gateways/lua/kong/schema.lua
- playground/resources/kong/kong.yaml
- playground/resources/nginx/nginx_config.conf
- playground/scenarios/service-protection-rl-escalation-kong/load-generator/test.js
- playground/scenarios/service-protection-rl-escalation-kong/policies/service1-demo-app-cr.yaml
- playground/scenarios/service-protection-rl-escalation-kong/policies/service1-demo-app.yaml
- playground/scenarios/service-protection-rl-escalation-nginx/policies/service1-demo-app-cr.yaml
- playground/scenarios/service-protection-rl-escalation-nginx/policies/service1-demo-app.yaml
Nginx:
Kong:
- Added integration documentation for Aperture with Gateways
**Bug fix:**
- Fixed issues with destination service name in gateways integration
- Simplified server address and port logic
- Updated plugin's configuration schema
**Refactor:**
- Removed unused imports and variables in gateways integration
- Replaced `destination_hostname` and `destination_port` with hardcoded values
> 🎉 A gateway shines, the traffic flows,
> Integrations fixed, our confidence grows.
> Unused code gone, simplicity shows,
> With each update, our software glows! 🌟
> Fixed the destination service name issue in gateways integration

- README.md
- docs/content/introduction.md
- Documentation: Improved introduction of Aperture platform in README.md and docs/content/introduction.md, providing a more detailed description of features, capabilities, and integration options.
> 🎉 A platform's tale, now better told 📖
> With features grand and integrations bold 🌟
> Aperture shines, its story unfolds 🚀
> In docs refined, our users behold! ✨
> Improve introduction

- README.md
- docs/content/introduction.md
- Improved introduction and README wording, sentence structure, and hyperlink
- Fixed broken link and typos in documentation
- Updated links in docs
> 🎉 A PR with changes so grand,
> Docs refined, links now withstand.
> Clarity shines, words rephrased,
> In this update, we're all amazed! 🌟
> Improve introduction and readme

- docs/content/faq.md
- docs/content/get-started/installation/agent/agent.md
- docs/content/get-started/installation/agent/bare_metal.md
- docs/content/get-started/installation/supported-platforms.md
- docs/content/integrations/istio/istio.md
```
Documentation:
- Updated various documentation pages with minor changes
- Modified a link in agent.md to ensure correct behavior
Bug fix:
- Fixed potential issues with the modified link in agent.md
```
> 🎉 Hooray for docs, they guide our way,
> With links now fixed, we're here to stay.
> A PR of change, so clear and bright,
> Let's celebrate this update tonight! 🥳
> level up in hierarchy supported platforms page

- playground/resources/java-demo-app/Dockerfile
```
- Update base image version for Java demo app
- Install `wget` in the Dockerfile
```
> 🎉 A new base image we embrace,
> With `wget` installed, we keep pace.
> Our app now stands on stronger ground,
> As improvements in this PR are found. 🚀
> fix: update java demo app image version

- blueprints/dashboards/flow-control/adaptive-load-scheduler/dashboard.libsonnet
- blueprints/policies/service-protection/base/config-defaults.libsonnet
- blueprints/policies/service-protection/postgresql/bundle.libsonnet
```
New Feature:
- Added agent_group argument to kubeletstats_infra_meter function in config-defaults.libsonnet
- Updated syntax for adding config.kubeletstats_infra_meter based on condition in bundle.libsonnet
- Modified graph panel title format in dashboard.libsonnet
Bug fix:
- Fixed floating-point number display in graph panel title
```
> 🎉 A new feature's born, a bug we've slain,
> With code refined, our progress gains.
> In graphs and meters, changes made,
> Together, we march in this grand parade. 🚀
> Fixed adding of kubeletstat infra_meter

- .circleci/continue-workflows.yml
- .tool-versions
using c++ implementation caused lot's of issue. changing it to go implementation
**Chore:**
- Switched dependency from `jsonnet` to `go-jsonnet`
- Added checks for older version of `jsonnet` in cache
- Updated build process with new ASDF plugin installation and version checks
> 🎉 A change in tools, a step we take,
> From `jsonnet` to `go-jsonnet`, a choice we make.
> Build process refined, with checks in place,
> Embracing progress, as we embrace the chase. 🚀
> change jsonnet to go-jsonnet

- playground/scenarios/service-protection-auto-scale-escalation/dashboards/main.jsonnet
- Simplified dashboard generation by using `apertureDashboard` function with external variable input
> 🎉 A simpler path we've found,
> To generate dashboards all around.
> With `apertureDashboard` in hand,
> Our code is cleaner, just as planned. 🌟
> Fixed scenarios

- blueprints/main.libsonnet
- Added support for Grafana dashboards by importing three new libraries in blueprints main
> 🎉 A new dawn breaks, Grafana in sight,
> With dashboards shining, oh so bright!
> Three libraries join the fray,
> Enhancing our blueprints, come what may! 🌟
> Updated list of available objects in blueprints main

- .circleci/config.yml
- .circleci/post-release.yaml
> Added step to copy tools-version (#2203)

- blueprints/grafana/utils/bar_gauge_panel.libsonnet
- blueprints/grafana/utils/stat_panel.libsonnet
- cmd/aperture-agent/agent.go
- cmd/aperture-controller/controller.go
> Cherry-picked changes for release v2.7.0-rc.2

- docs/content/reference/aperturectl/aperturectl.md
- docs/tools/aperturectl/generate-docs/generate-docs.go
> Generate install note in top-level reference for aperturectl

- cmd/aperturectl/cmd/utils/controller.go
- docs/content/architecture/architecture.md
- docs/content/concepts/auto-scale.md
- docs/content/concepts/classifier.md
- docs/content/concepts/flow-lifecycle.md
- docs/content/concepts/infra-meter.md
- docs/content/concepts/rate-limiter.md
- docs/content/concepts/scheduler/scheduler.md
- docs/content/concepts/selector.md
- docs/content/concepts/service.md
- docs/content/get-started/installation/agent/agent.md
- docs/content/get-started/installation/controller/controller.md
- docs/content/reference/aperturectl/agents/agents.md
- docs/content/reference/aperturectl/apply/apply.md
- docs/content/reference/aperturectl/apply/dynamic-config/dynamic-config.md
- docs/content/reference/aperturectl/apply/policy/policy.md
- docs/content/reference/aperturectl/auto-scale/auto-scale.md
- docs/content/reference/aperturectl/auto-scale/control-points/control-points.md
- docs/content/reference/aperturectl/blueprints/generate/generate.md
- docs/content/reference/aperturectl/decisions/decisions.md
- docs/content/reference/aperturectl/delete/delete.md
- docs/content/reference/aperturectl/delete/policy/policy.md
- docs/content/reference/aperturectl/discovery/discovery.md
- docs/content/reference/aperturectl/discovery/entities/entities.md
- docs/content/reference/aperturectl/flow-control/control-points/control-points.md
- docs/content/reference/aperturectl/flow-control/flow-control.md
- docs/content/reference/aperturectl/flow-control/preview/preview.md
- docs/content/reference/aperturectl/policies/policies.md
- docs/content/use-cases/adaptive-service-protection/adaptive-service-protection.md
- docs/content/use-cases/rate-limiting/graphql-rate-limiting.md
> Docs: consistent casing of Aperture Controller & Agent

- docs/content/use-cases/adaptive-service-protection/assets/workload-prioritization/policy.yaml
- docs/content/use-cases/adaptive-service-protection/assets/workload-prioritization/values.yaml
- docs/content/use-cases/managing-quotas/assets/client-side-rate-limiting/policy.yaml
- docs/content/use-cases/managing-quotas/assets/client-side-rate-limiting/values.yaml
> Fix priorities in docs

- go.mod
- go.sum
> Tidy go.mod file

- manifests/charts/aperture-agent/templates/agent-deployment.yaml
> Fixed the error during the namespace scoped installation

- .github/styles/Vocab/FluxNinja/accept.txt
> vocab additions

- .tool-versions
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/CheckResponse.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/FlowControlServiceGrpc.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/LimiterDecision.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/checkhttp/v1/CheckHTTPRequest.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/checkhttp/v1/CheckHTTPResponse.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/checkhttp/v1/FlowControlServiceHTTPGrpc.java
- sdks/aperture-java/lib/core/src/main/java/com/fluxninja/generated/aperture/flowcontrol/checkhttp/v1/OkHttpResponse.java
> fix pre-commit hook

- sdks/aperture-js/package.json
> Bump js sdk version to 1.1.0

- blueprints/jsonnetfile.json
- blueprints/jsonnetfile.lock.json
- playground/tanka/jsonnetfile.json
- playground/tanka/jsonnetfile.lock.json
Pin grafonnet version as they just pushed a breaking change in main branch - https://github.com/grafana/grafonnet/pull/111#discussion_r1317333355
> pin grafonnet version

- blueprints/jsonnetfile.json
- blueprints/jsonnetfile.lock.json
- playground/tanka/jsonnetfile.json
- playground/tanka/jsonnetfile.lock.json
Pin grafonnet version as they just pushed a breaking change in main
branch -
https://github.com/grafana/grafonnet/pull/111#discussion_r1317333355
> Combined PR with cherry-picks for 2.14.1

- sdks/aperture-js/package-lock.json
- sdks/aperture-js/package.json
> aperture-js: bump version

- playground/resources/wavepool-generator/apps-v1.Deployment-wavepool-graphql-generator.yaml
> Use grafana/k6 image

- pkg/policies/controlplane/components/flowcontrol/rate-limiter/rate-limiter.go
> Fix query for ACCEPT_PERCENTAGE signal

- api/buf.lock
> Update buf lock

- api/buf.lock
> Update buf.lock with new commit and digest values

- api/aperture/policy/language/v1/flowcontrol.proto
- api/gen/proto/go/aperture/policy/language/v1/flowcontrol.pb.go
- blueprints/gen/jsonschema/_definitions.json
- docs/content/assets/openapiv2/aperture-controller.swagger.yaml
- docs/content/assets/openapiv2/aperture.swagger.yaml
- docs/content/reference/configuration/spec.md
- docs/gen/policy/policy.yaml
- pkg/dmap-funcs/concurrency-limiter/global-token-counter.go
- pkg/policies/controlplane/circuitfactory/component-factory.go
- pkg/policies/flowcontrol/actuators/concurrency-scheduler/concurrency-scheduler.go
- pkg/policies/flowcontrol/actuators/workload-scheduler/scheduler.go
- pkg/policies/flowcontrol/engine.go
- sdks/aperture-js/docs/interfaces/Flow.md
- sdks/aperture-js/example/routes/use_aperture.ts
- sdks/aperture-js/sdk/client.ts
- sdks/aperture-js/sdk/flow.ts
- Update the flowcontrol.proto, flowcontrol.pb.go, aperture-controller.swagger.yaml, and aperture.swagger.yaml files. The changes include fixing a typo in a comment and improving the description of a field.
> Add FlowEnd support in SDKs

- go.mod
- go.sum
This is a cleanup after the previous PR.
> Use tagged Olric version

- README.md
> Update caching section in README

- go.mod
- go.sum
> Update olric version to v0.5.4-fn.patch.18

- playground/scenarios/postgres-concurrency/load-generator/test.js
- sdks/aperture-go/examples/manual/init.sql
> Update load generator target duration and primary key constraint
